### ISSUE TITLE
2D tile map idea

### ISSUE THREAD

**Issue by tsr8** [castle-engine/castle-engine#10]
It would be great to have some TiledMap component. It should be compatible with ["Tiled Map Editor"] (http://www.mapeditor.org/) file format. Which class should be an ancestor to "TCastleTiledMap"?

**Comment by michaliskambi** [comment]
Looks cool! Contributions would be most welcome!

It's a 2D control, so it should descend from TUIControl. The unit CastleControls contains many examples of creating 2D controls, and http://castle-engine.sourceforge.net/tutorial_player_2d_controls.php has some (very) introductory info, although I guess you know them already:)
