### ISSUE TITLE
QT5 and PBR supported

### ISSUE THREAD

**Issue by DimitriyPS** [castle-engine/castle-engine#102]
1. Castle Game Engine + Lazarus + QT5... is it supported?
2. Implementation of PBR materials available?

**Comment by michaliskambi** [comment]
AD 1. I'm afraid not. Our TCastleContol relies on TOpenGLControl implementation from Lazarus. We support all Lazarus widgetsets that implement TOpenGLControl properly. But looking at https://github.com/graemeg/lazarus/tree/upstream/components/opengl , there is no Qt5 implementation, only Qt4. You can submit a feature request (or a patch :) ) to Lazarus developers to implement TOpenGLControl for Qt5, once this will work -- Castle Game Engine TCastleContol will automatically work with Qt5 too.

AD 2. Not yet. I have plans to implement PBR along with glTF 2 in 2018, see my plans: https://castle-engine.io/wp/2017/12/23/plans-6-4-release-asap-visual-editor-soon-2018-roadmap/ and see my PBR notes about how it will fit with existing materials: https://github.com/michaliskambi/x3d-tests/wiki/Include-PhysicalMaterial-and-PhysicalEnvironmentLight-in-the-official-X3D-specification .

    So, I have PBR planned in my head and it will definitely happen, most probably in 2018. But it's not ready yet.

    See also https://github.com/castle-engine/castle-engine/wiki/How-to-make-rendering-prettier%3F .

I'm closing this issue -- one half should be submitted to Lazarus, the other half is already recorded in other plans:)
