### ISSUE TITLE
Investigate motion events

### ISSUE THREAD

**Issue by michaliskambi** [castle-engine/castle-engine#104]
Testcase from @eugeneloza , check is everything OK.
[MouseIssue.lpi.tar.gz](https://github.com/castle-engine/castle-engine/files/2380223/MouseIssue.lpi.tar.gz)

The report on Discord:

Eugene: A short and unimportant question about Window.MousePosition. I've been doing some mouse related stuff, and to my surprise found out that Window.MousePosition changes 10 times faster than OnMouseMotion(Event). I.e. if I record mouse position each frame through reading Window.MousePosition I get a distance value 10 times larger than if I record mouse position in each Window.OnMouseMotion event by reading Event.Position. Could it mess something up because of my mouse DPI? I'm seemingly doing the same thing in both variants.
If there is no direct reason for such behavior, I'll try making a simple test example.

Michalis: Hm, not sure how can this happen. Our MousePosition is just updated at the same time we handle OnMotion events, in a very trivial way: https://github.com/castle-engine/castle-engine/blob/master/src/window/castlewindow.pas#L3606 . So I don't see how they could get desynchronized in any way. Please submit a testcase to reproduce and I'll investigate:)

Eugene: Hmmm.... maybe it has something to do with "limit FPS" and "VSYNC". How often does Window.MousePosition gets updated? At every frame or at every OnMouseMotion event (which happens at my PC about 1.5-2 times more often)?
UPD: Hmm... I guess the events "can" fire more or less frequently than FPS and that might introduce some error due to averaging by slower FPS, however, that shouldn't provide for up to 10x changes.(edytowane)
However, I manually store the last mouse position, so it should work almost flawlessly even with frameskips.
eugeneloza13.09.2018
Numbers:
In Decoherence(UltraScientia):
If measured through onMouseMove event: 30-600 pixels/second average speed peaking at 4000.
If measured through onRender event: 2000-5000 pixels/second average peaking at 50000.

I've updated the testcase.
Now it calculates average speed values in pixels per day:

Average onRender speed =  5.2980897551680857E+008
Average onMouseMove speed =  2.0931250841929906E+006

**Comment by michaliskambi** [comment]
@eugeneloza Finally, I looked into this issue!

To recap, in your testcase you

- observe the mouse motion speed from `OnRender` (looking at `Window.MousePosition` changes)

- and mouse motion speed from `OnMotion` (looking at `Event.Position`).

They *should* be equal, but instead you observe much higher speed from `OnRender`.

My answer, in short:

- I found 3 "suspicious details" in how you calculate the speeds. I am not 100% sure what is the main culprit of the observed difference (`OnRender` seems to see a much faster mouse movement than `OnMotion`), I suspect it is a conjuction of "suspicious issue 1" and "suspicious issue 3" described below.

- I modified the code to calculate the speeds differently, removing all these "suspicious details". And now I get almost equal speeds observed by both `OnRender` and `OnMotion`.

1. You divide by a very small number when you do:

    ```
    WindowSpeed := Sqrt(
      Sqr(WindowLastPos.Data[0] - Window.MousePosition.Data[0]) +
      Sqr(WindowLastPos.Data[1] - Window.MousePosition.Data[1])) / (Now - WindowLastTime);
    ```

    and

    ```
    EventSpeed := Sqrt(
      Sqr(EventLastPos.Data[0] - Event.Position.Data[0]) +
      Sqr(EventLastPos.Data[1] - Event.Position.Data[1])) / (Now - EventLastTime);
    ```

    I added some logging to display

    ```
    WriteLn('Average window speed = ', (SumWindow/WindowUpdates):1:6, ' = ', SumWindow:1:4, '/', WindowUpdates);
    WriteLn('Average event speed = ', (EventSpeed/WindowUpdates):1:6, ' = ', EventSpeed:1:4, '/', WindowUpdates);
    ```

    and the results look like this:

    ```
    Average window speed = 35783568.484103 = 35783568.4841/1
    Average event speed = 35783568.484103 = 35783568.4841/1
    Average window speed = 114487733.309241 = 228975466.6185/2
    Average event speed = 37776447.576378 = 75552895.1528/2
    Average window speed = 240079937.195434 = 720239811.5863/3
    Average event speed = 87149028.285359 = 261447084.8561/3
    Average window speed = 278214264.339537 = 1112857057.3581/4
    Average event speed = 131844647.702104 = 527378590.8084/4
    ```

    So your `SumWindow` and `EventSpeed` are quickly huge numbers. This is suspicious, since the mouse doesn't move that fast.

2. (UNSURE IF THIS MATTERS):

    Note that the code ignores OnMotion events with `Now = EventLastTime`. But multiple motion events may be reported at the same time. Logging confirms it:

    ```
    Average window speed = 232716446.705767 = 6748776954.4672/29
    Average event speed = 4391904.293551 = 127365224.5130/29
    OnMotion: Now: 43478.6581919444 Time increase: 0.0000001852 Non-zero time increase: TRUE Event.Position: 420.00 488.00
    OnMotion: Now: 43478.6581919560 Time increase: 0.0000000116 Non-zero time increase: TRUE Event.Position: 428.00 483.00
    OnRender: Window.MousePosition: 428.00 483.00 Time increase: 0.0000001968
    Average window speed = 227128711.797332 = 6813861353.9200/30
    Average event speed = 27165230.834109 = 814956925.0233/30
    OnMotion: Now: 43478.6581921412 Time increase: 0.0000001852 Non-zero time increase: TRUE Event.Position: 449.00 474.00
    OnMotion: Now: 43478.6581921412 Time increase: 0.0000000000 Non-zero time increase: FALSE Event.Position: 481.00 467.00
    OnMotion: Now: 43478.6581921412 Time increase: 0.0000000000 Non-zero time increase: FALSE Event.Position: 529.00 465.00
    OnRender: Window.MousePosition: 529.00 465.00 Time increase: 0.0000001852
    Average window speed = 237672503.076073 = 7367847595.3583/31
    Average event speed = 3979802.036978 = 123373863.1463/31
    ```

    (The lines with `Non-zero time increase: FALSE` indicate OnMotion events skipped by `if Now - EventLastTime > 0 then` check.)

    Your code is waiting for the next OnMotion with `Now > EventLastTime`, but some movement could be missed this way. E.g. if we move from (0,0) to (0,10) then back to (0,0), all during the same `Now` value, then the distance we traveled is 20, but your code would see distance 0.

    However, I'm unsure whether this has any noticeable effect on the observed difference. While the OnMotion events with equal `Now` happen regularly (as above log shows), missing them should not have a drastic effect on the observed speed (as we will typically miss some intermediate points only -- this should not cause an observed speed to differ by a magnitude like 100x). In any case, `OnRender` would also miss such lighting-fast mouse travel.

3. (UNSURE IF THIS MATTERS):

    The calculation of "window speed" (which is "mouse speed as seen from OnRender") and "event speed" (which is "mouse speed as seen from OnMotion") is somewhat inconsistent:


    ```
    WriteLn('Average window speed = ', SumWindow/WindowUpdates);
    WriteLn('Average event speed = ', EventSpeed/WindowUpdates);
    ```

    I realize that you could not take `SumEvent` in 2nd line (as `EventSpeed` remains constant when the mouse doesn't move, so `SumEvent` doesn't really contain any meaningful value). But this means that, as the application runs, `EventSpeed/WindowUpdates` deteriorates into `0` (since `EventSpeed` should stay more-or-less constant, while `WindowUpdates` grows into infinity). In contrast `SumWindow/WindowUpdates` behaves differently, it should deteriorate into the actual overall speed.

4. I attach a code where I calculate the `WindowDistance` and `EventDistance` instead of `WindowSpeed` and `EventSpeed`. This way things are simpler, and I *know* they are correct :)

    - I avoid the need for `if Now - EventLastTime > 0 then`.
    - I avoid dividing by very small numbers.
    - And the final speed calculation is consistent,

    ```
    WriteLn('Average window speed = ', WindowDistance/WindowUpdates);
    WriteLn('Average event speed = ', EventDistance/WindowUpdates);
    ```

    So in both cases I calculate the speed as `XxxDistance/WindowUpdates`. `WindowUpdates` basically serves as a way to measure time here, which is OK since in this application we should have almost perfectly stable 60 FPS.

    Now I get quite similar speeds:

    ```
    Average window speed = 11.484922 = 2296.9844/200
    Average event speed = 11.514328 = 2302.8655/200

    Average window speed = 24.951382 = 9980.5530/400
    Average event speed = 25.012383 = 10004.9533/400

    Average window speed = 23.090773 = 13854.4639/600
    Average event speed = 23.143869 = 13886.3212/600
    ```

    Sometimes one (speed from OnRender), sometimes the other (speed from OnMotion) is slightly larger, which I guess is simply due to floating point errors.

    While the floating point errors should be smaller in this approach (we do not operate on wildly small/large numbers), the errors still exist. Distance calculation is a sum of a lot of small numbers, calculated by Sqrt and Sqr.

    In theory (if we ignore floating point errors) the distance seen by OnMotion could be very slightly larger, since OnMotion "registers" all changes to MousePosition, while OnRender "registers" only some of them (OnRender misses changes that are shorter than the time between 2 frames, usually 1/60 of second). But in this case, I guess that floating-point errors matter more, and sometimes WindowDistance, sometimes EventDistance is larger after some movement.

**Comment by michaliskambi** [comment]
This is my modified code that calculates `EventDistance` and `WindowDistance`: 
[MouseIssue.pas.txt](https://github.com/castle-engine/castle-engine/files/2753234/MouseIssue.pas.txt)

**Comment by eugeneloza** [comment]
Thanks a lot for looking into that issue! I'm trying to make a good note of all the points but overall it looks like the problem is solved completely. In Decoherence I've been using CGE-based timer, which is much more accurate than `Now` function, so that also explains why I had smaller errors in Decoherence, than in plain FPC example.

As I should have mentioned (I hope I didn't forget :)) - I want to try to research "mouse psychology" a bit, i.e. relation of mouse movements peculiarities (such as speed, direction, accuracy, etc.) to player's mood. So that the game would detect if the player is bored, tired, happy, excited or anything else and will try to propose a respective gameplay variation (e.g. give something to cheer up an upset player :) or provide a challenge for eager one) - i.e. "adaptive gameplay". Of course this is the "far-away" goal. Now I want just to record mouse speed and angle and try to connect those to some reference (a questionnaire is a good start), e.g. by means of a neural network.

P.S. I've run into possibly related issue some time ago https://gitlab.com/EugeneLoza/decoherence/issues/970 when running a profiler in `OnMouseMotion` causes a major slow-down. I didn't have the opportunity to investigate it deeper, I'll report when I do.

**Comment by michaliskambi** [comment]
> So that the game would detect if the player is bored, tired, happy, excited or anything else and will try to propose a respective gameplay variation (e.g. give something to cheer up an upset player :) or provide a challenge for eager one) - i.e. "adaptive gameplay".

I did some version of "adaptive gameplay" in "Escape from the Universe" :) But I didn't try to measure the "mood" looking at input, instead I measured "tension" (how much stress is right now) looking at how much fight is going on the screen.

- Each time player gets hurt (is hit by a rocket), the "tension" increases by some value, around 20% as far as I remember.
- The tension decreases (decays) automatically as time passes (so if you manage to not get hit for a couple of seconds, the tension drops to 0).
- Also some enemies cause minimum tension by a mere appearance on the screen (e.g. a boss -- during a boss fight tension is high even if you manage to dodge the rockets).
- And the "tension" determines spawning. Some enemies, or dangerous map parts (as even the map is generated "at runtime", while you fly through), are spawned only when tension is <= some number (otherwise nothing is spawned at some point, causing the map to be filled more with harmless decorations/power-ups).

In effect, enemies/dangers typically come in waves. Enemies appear, you get hit, more enemies appear, you get hit more, and you get a calmer moment -- for some time (until tension drops) the enemies are not spawned. It nicely adaps to your skill 

-  if you are a skilled player and dodge rockets, then your tension stays low (until you encounter a boss) and you are constantly surrounded by shooting enemies. So a good player has more challenge. 

- If you are a poor player, and constantly get hurt, then you can more often "catch a breath" in between, so the game is a (little) easier on you. 

It required some tweaking overall, to balance the game and keep it challenging, but overall if was a Great Success in my eyes :) We didn't design spawn points of enemies, and yet the gameplay feels engaging.

**Comment by eugeneloza** [comment]
> but overall if was a Great Success in my eyes

Actually yes! That was a really neat solution, and I thought it was pre-designed, but now it makes much more sense.

I haven't come up with the total amount of instruments yet, but I wanted to use as many as possible, like including color preferences, e.g. Lüscher color test, mouse movements (as in some references here https://gitlab.com/EugeneLoza/decoherence/issues/842 ), overall gameplay efficiency (does the player makes errors?), gameplay preferences (how the player wants to deal with problems, or which problems he chooses to deal with), local time of the day (and regular playing schedule - is it weekend? Isn't that too late? Doesn't the player play for too long?), etc. Thou, not being too well acquainted with psychology, most of those were just experimental ideas - to try to record data and somehow process it with hope that it'll eventually be possible to get correlation coefficient somewhere above 0.5.
