### ISSUE TITLE
TTF Font Issue on Windows, Cannot load FreeType library, loading font files not possible

### ISSUE THREAD

**Issue by LovelyA72** [castle-engine/castle-engine#108]
When I tried to use
`UIFont := TTextureFont.Create(ApplicationData('something.ttf'), 20, true);`
to customise the font of my game, the engine just thrown me this error message:
`Cannot load FreeType library, loading font files not possible.`
I tried to place freetype.dll in my programme's directory, but it does not help.

Thank you

**Comment by eugeneloza** [comment]
Hi, @LovelyA72 !
What system are you using. Namely, you need different DLLs for 32 bit and 64 bit OS.
You can download the correct DLLs for your system here: https://castle-engine.io/documentation.php#section_libraries
Alternatively, they are already available in your Castle Game Engine installation in this folder: `castle-engine/tools/build-tool/data/external_libraries/`
You may set those to your OS PATH variable, or alternatively copy `freetype-6.dll` (and `zlib1.dll` too if I remember correctly) to your project folder.

**Comment by LovelyA72** [comment]
It works! It turns out that the name of my dll was `freetype.dll` instead of `freetype-6.dll`. However, none-English(e.g. Chinese) letters still can not work.

Should I create a new issue for that problem?

Thank you
