### ISSUE TITLE
Qt can't use "examples/library/qt_library_tester/"

### ISSUE THREAD

**Issue by Sakyaa** [castle-engine/castle-engine#109]
Qt can't use "examples/library/qt_library_tester/"

**Comment by Sakyaa** [comment]
Qt 5.9

**Comment by Sakyaa** [comment]
How to make castleengine.dll

**Comment by michaliskambi** [comment]
To compile the CGE library, go to `src/library/` and execute `./castleengine_compile.sh` there.

See also the comments at the beginning of `examples/library/lazarus_library_tester/cge_dynlib_tester_form.pas` , https://github.com/castle-engine/castle-engine/blob/master/examples/library/lazarus_library_tester/cge_dynlib_tester_form.pas . The `qt_library_tester` is quite similar to `lazarus_library_tester` , but it uses the library from a Qt application in C++.

**Comment by DBtester1** [comment]
When  i go to src/library/ and execute ./castleengine_compile.sh ,
find:'castle-engine':no such file
./castleengine_compile.sh : fpc : No command found
how can i do?

**Comment by eugeneloza** [comment]
> fpc : No command found

This means Free Pascal compiler is not available at your `$PATH` global variable. If you install it through "normal package" (e.g. a *.deb package or official repository in Debian/Ubuntu) it should be done automatically, otherwise, follow https://castle-engine.io/documentation.php#section_bare_fpc

> find:'castle-engine':no such file

It reports the same problem. Castle Game Engine build-tool is not available at your `$PATH` global variable. See here https://github.com/castle-engine/castle-engine/wiki/Build-Tool#quick-installation-instructions

**Comment by michaliskambi** [comment]
P.S. See e.g. https://www.computerhope.com/issues/ch000549.htm if you're not sure how to set environment variables on Windows:)

**Comment by DBtester1** [comment]
Thank you！

**Comment by DBtester1** [comment]
Thank you so much！
I have compiled the CGE library and generated `libcastleengine-so`.
I put it in the project directory and add `LIBS +=./ castleengine-so` in .pro，the 3d file cannot be opened after the project runs，Am I missing something?
After the project runs,it has one `Gtk-message:GtkDialog maooed without a transient parent. This is discouraged.`,Does this have anything to do with it?
Thank you very much for your answer！

**Comment by michaliskambi** [comment]
I tested the Qt example on Linux, and it works fine.

- I compile the library by `src/library/ && ./castleengine_compile.sh`.
- Then I compile the Qt example from QtCreator, by opening `examples/library/qt_library_tester/qt_library_tester.pro`.
- I run it by `export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/$CASTLE_ENGINE_PATH/src/library/" && ./qt_library_tester`
- I can open just fine various models e.g. from https://castle-engine.io/demo_models.php .

If you seem to be unable to load anything, then probably you don't load the dynamic library correctly. See my notes above, and in README linked below. On Linux, you can define `LD_LIBRARY_PATH`. On Windows, you can copy the dll file alongside exe.

I have written a README documenting this on https://github.com/castle-engine/castle-engine/blob/master/examples/library/qt_library_tester/README.md .

The message `Gtk-message:GtkDialog mapped without a transient parent` is unrelated. It's a message from GTK that relatedsto how GTK open dialog is used, but it has no negative consequences (as far as I know, you can search the Internet for it) and I'm not sure whether we can avoid it when using Qt 5.

**Comment by DBtester1** [comment]
Thank you so much！
Realized, can open display 3d file.
