### ISSUE TITLE
How to compile view3dscene and castle_game_engine on arm64? Does it support compiling on arm?

### ISSUE THREAD

**Issue by DBtester1** [castle-engine/castle-engine#112]
target os:Linux for AArch64
Free Pascal Compiler version 3.0.0
I downloaded the view3dscene source code, castle_game_engine_6.4 source code, installed GtkGLExt, FreeType and so on.
I enter view3dscene source code, execution ./compile.sh 
Error:/usr/bin/ppca64 can't be executed,error message : Failed to execute "/usr/bin/ppca64",error code : -139.
How can I do?

**Comment by michaliskambi** [comment]
This means you did not install FPC cross-compiler for AArch64. Follow the FPC compilation instructions to compile FPC that is able to target AArch64 processor (this will result in `ppca64` binary). I would advice to use fpcupdeluxe ( https://github.com/castle-engine/castle-engine/wiki/fpcupdeluxe ) to easily get FPC and create cross-compilers.

Also, I would advice to rather try Castle Game Engine 6.5 and latest view3dscene sources from GitHub. CGE is on https://github.com/castle-engine/castle-engine/ , view3dscene on https://github.com/castle-engine/view3dscene/ . I'm not sure whether CGE 6.4 is ready for AArch64 of Linux. CGE 6.5 definitely is.

P.S. If you want to study view3dscene source code, please note that it is ugly and complicated :) View3dscene is very full-featured, but if you want to learn how to create a simple 3D viewer using CGE it's much better to start from a simple example like examples/3d_rendering_processing/view_3d_model_basic.lpr (in CGE source code). There is also much simpler code of view3dscene-mobile, on https://github.com/castle-engine/view3dscene-mobile (it is directed for Android/iOS, but will work on desktop too).

P.P.S. If you have questions how to use the engine, it is better to ask on forum https://forum.castle-engine.io/ , or Discord https://castle-engine.io/talk.php . This way the question is visible to more people, and they may help too :)

**Comment by DBtester1** [comment]
Compiling ./src/castlescript/castlescriptcorefunctions.pas
Assembling castlescriptcorefunctions
Assembling castlescript
castlescript.pas(2883) Error: Can't call the assembler, error -1 switching to external assembling
castlescript.pas(2883) Fatal: There were 2 errors compiling module, stopping
Fatal: Compilation aborted
Error: /home/firefly/fpcupdeluxe/fpc/bin/aarch64-linux/ppca64 returned an error exitcode

**Comment by michaliskambi** [comment]
I'm afraid that this error line still indicates some problem with FPC configuration for Linux/AArch64 combination, which is unrelated to CGE:

```
castlescript.pas(2883) Error: Can't call the assembler, error -1 switching to external assembling
```

Unless FPC has some problem specific to castlescript.pas, but that would be weird. I succuessfully compile this unit for Android/AArch64 (with FPC 3.3.1) and Darwin/AArch64 (using FPC 3.0.4), although I didn't try for Linux/AArch64 (as I never needed it).

1. Can you compile any program using your FPC for Linux/AArch64?

2. Try latest FPC 3.3.1 in case the problem is already fixed there. You can install it with fpcupdeluxe.
