### ISSUE TITLE
Android time issue

### ISSUE THREAD

**Issue by and3md** [castle-engine/castle-engine#131]
I did a small investigation regarding the problem of time errors on Android. And I found that Android provides three clocks. And most likely we use the wrong one. More information in https://developer.android.com/reference/android/os/SystemClock.html .
I don't know how to fix it in FreePascal at the moment. So I add this as an issue. Maybe @michaliskambi knows how to fix it :)

**Comment by and3md** [comment]
Ok, I found solution, I make PR, after more testing.

**Comment by michaliskambi** [comment]
Closing, further discussion in #132 .
