### ISSUE TITLE
Non-informative error message if not all OpenAL dlls arefound

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#141]
When running `simplest_play_sound` with only `OpenAL32.dll` in the project folder it reports `OpenAL's audio device "" is not available` which can be rather confusing, as what really happens is that it cannot find `wrap_oal.dll`.

![Clipboard-1](https://user-images.githubusercontent.com/10726162/66712226-1daef180-eda2-11e9-8993-6be865d19805.jpg)

**Comment by michaliskambi** [comment]
That is OpenAL problem, I'm afraid. In CGE we don't open `wrap_oal.dll`, it is only opened internally by main OpenAL dll. And it's a deliberate architecture as far as I know. Other implementations could provide their audio devices this way, although I don't know if anything is actually using this feature. It is also possible to get a different OpenAL implementation on Windows, in theory.

**Comment by eugeneloza** [comment]
Yeah, I understand that, but maybe we could extend the error message to something like this:
```
raise EOpenALError.CreateFmt(
        'OpenAL''s audio device "%s" is not available'
        {$IFDEF Windows}+ '. This may be caused by missing wrap_oal.dll in the PATH folder.'{$ENDIF}
        , [ADevice])
```
or
```
if ADevice = '' then
  ....'It seems like the OpenAL wasn't properly initialized; Check that all corresponding libraries are available for current architecture'
```

**Comment by michaliskambi** [comment]
You're absolutely right, I extended the error message in https://github.com/castle-engine/castle-engine/commit/81ad7215acba3f242acb30c69856d7eed1c3d815 . Thanks!
