### ISSUE TITLE
[Enhancement] DrawPrimitive2D

### ISSUE THREAD

**Issue by damianday** [castle-engine/castle-engine#151]
In Asphyre engine we have the following:
```
    procedure DrawIndexedTriangles(const Vertices: PPoint2; const Colors: PIntColor; const Indices: PLongInt;
      const VertexCount, TriangleCount: Integer;
      const BlendingEffect: TBlendingEffect = TBlendingEffect.Normal); virtual; abstract;
```

In Castle we have something close:
`procedure DrawPrimitive2D(const Mode: TPrimitiveMode; const Points: array of TVector2; const Color: TCastleColor; const BlendingSourceFactor: TBlendingSourceFactor = bsSrcAlpha; const BlendingDestinationFactor: TBlendingDestinationFactor = bdOneMinusSrcAlpha; const ForceBlending: boolean = false; const LineWidth: Single = 1; const PointSize: Cardinal = 1);`

The problem is with DrawPrimitive2D I can only specify 1 color for all vertices, while I really want a different color for each vertice without falling back to opengl.

**Comment by michaliskambi** [comment]
For more advanced usage (like color per-vertex), I would prefer to not extend the `DrawPrimitive2D` -- it is a helper routine that has already a lot of parameters :) Instead you can use X3D nodes like `IndexedFaceSet` with `Color` node to achieve this.

You create X3D nodes, place them in `TCastleScene`, and render using `TCastleViewport`. It is a longer code to write -- but it's also much more flexible. Here's a ready example how to specify triangles with color-per-vertex:

https://gist.github.com/michaliskambi/268557c5b5c9e1607755406d3a086b78

These nodes can be changed (e.g. you could call `Coordinate.SetPoint` and/or `Color.SetColor` every frame, to change the rendered coordinates and colors every frame, you can add/remove scene by `Viewport.Items.Add`/`Viewport.Items.Remove` or `Scene.Exists` etc.) so it is still dynamic. So it's a different API than `DrawPrimitive2D`, but you can achieve the same (and more) stuff this way.

See other examples of composing scene from nodes, on https://castle-engine.io/x3d_implementation_geometry2d.php and https://castle-engine.io/x3d_implementation_geometry3d.php .
