### ISSUE TITLE
castle engine for bleder

### ISSUE THREAD

**Issue by Reaper10** [castle-engine/castle-engine#152]
It'd be cool to see  the castle engine built for bleder.
https://www.blender.org/
like armory 3d
https://armory3d.org/
this bring more people the castle engine

**Comment by michaliskambi** [comment]
The documentation how to use Blender with Castle Game Engine is on https://castle-engine.io/creating_data_blender.php . Basically:

- You can export from Blender to glTF, X3D, castle-anim-frames and some other formats ( https://castle-engine.io/creating_data_model_formats.php ).
- Animation export is supported through:

  -  castle-anim-frames (supports animating everything, but has a large loading time and memory consumption) 

    - and glTF (supports for now only animation of transformations, see https://castle-engine.io/creating_data_model_formats.php ).

My plan for integration is simple: rely on Blender -> glTF exporter (actively developed by Khronos), and support all glTF features possible. This is planned for 2020 on https://castle-engine.io/wp/2019/12/30/big-engine-plans-for-2020-trello-boards-x3d-pbr/ ("Support glTF skinned animation", "Physical-Based Rendering" -- both these feature mean that we rely on Blender -> glTF export).

I'll leave this ticket open for now -- I want to play with https://armory3d.org/ to decide more :)

But for now, my plan for Blender integration is just : implement 100% of glTF, and let Blender export to glTF.

**Comment by michaliskambi** [comment]
Closing. We now have excellent glTF support, with PBR, skinned animation, and it exports nicely from Blender :)

See https://castle-engine.io/creating_data_model_formats.php , https://castle-engine.io/creating_data_blender.php .
