### ISSUE TITLE
shadowVolumes dosen't work on Nvidia (or I failed)

### ISSUE THREAD

**Issue by pieomy** [castle-engine/castle-engine#164]
Hi, shadowVolumes dosen't work on Nvidia (or I failed)

Uncommented fps_demo example_level_final.x3dv SpotLight with shadowVolumesMain and shadowVolumes but shadows doesn't appear (Nvidia enable)

if Nvidia disabled on device manager, shadows appears (Intel HD Graphic)
(shadowVolumes and Nvidia working good on view3dscene.exe but fps_demo.exe and my project exe failing )

Thank you.

![on](https://user-images.githubusercontent.com/49295522/86372118-743ec180-bc8a-11ea-8eda-625c3fe475d6.png)
![off](https://user-images.githubusercontent.com/49295522/86372140-79037580-bc8a-11ea-95d6-a6cfe31142b4.png)

**Comment by michaliskambi** [comment]
Did you add `Window.StencilBits := 8` call, as the comments in `example_level_final.x3dv` instruct to?

```
# Remember to add "Window.StencilBits := 8;" before "Window.Open;"
# if you want to use shadow volumes.
```
You can do it e.g. in `gameinitialize.pas` e.g. by adding it after the window creation, like this:

```pascal
  Window := TCastleWindowBase.Create(Application);
  Window.StencilBits := 8;
```

Without `Window.StencilBits`, some GPUs may return stencil buffer anyway (which explains why it worked on Intel), but it's not guaranteed. view3dscene does does, so it would make sense that all cases work in view3dscene.

P.S. I just noticed that knights do not cast shadows. This will be fixed soon. (I was recently tweaking this model, for glTF export, and I must have broken the "2-manifold" property of it. The 2-manifold requirement is described on https://castle-engine.io/x3d_extensions_shadow_volumes.php .)

**Comment by pieomy** [comment]
Window.StencilBits := 8; fixed

sorry my bad I miss that comment 
thank you

**Comment by michaliskambi** [comment]
I have updated https://castle-engine.io/x3d_extensions_shadow_volumes.php to mention it also there.

**Comment by michaliskambi** [comment]
> P.S. I just noticed that knights do not cast shadows. This will be fixed soon. (I was recently tweaking this model, for glTF export, and I must have broken the "2-manifold" property of it. The 2-manifold requirement is described on https://castle-engine.io/x3d_extensions_shadow_volumes.php .)

Update to this comment: I checked, actually knight was never 2-manifold. It would require quite some changes to make it 2-manifold. I started doing them, but both mesh and texture mapping would have to be updated to do it. So, not something I can do easily. For now deferred. This is just a problem with this particular 3D model -- new 3D models, if you think about 2-manifold when creating them, will work :) E.g. `examples/third_person_camera/data/enemy/soldier1.gltf` is a 2-manifold and would cast shadow volumes nicely (but it doesn't have all the animations I wanted to show in fps_game...).

Shadow maps don't have this requirement, and with them -- knight casts shadows OK. (Although shadow maps have different limitations -- poor resolution / limited area.)

**Comment by pieomy** [comment]
Thanks for explaining, my models 2-manifold and have shadows now. I selected shadowVolumes because it's easy for usage, I don't know yet which method is better for performance (especially for CPU usage)
I am ok with shadowVolumes now 

thank you
