### ISSUE TITLE
TSSLSocketHandler

### ISSUE THREAD

**Issue by RamazanGeven** [castle-engine/castle-engine#170]
file: castledownload_url_http_fphttpclient
Line: 253
//rgdikkat ->    TSSLSocketHandler.GetDefaultHandler.Free;

**Comment by michaliskambi** [comment]
Ups, I broke compilation with FPC 3.0.4 last night. Thank you, fixed! I was testing with FPC 3.2.0, so I didn't realize it.

Jenkins is also testing CGE automatically, with various FPC versions, so it would catch it, but you were faster :)

P.S. Consider upgrading to latest FPC 3.2.0, see https://castle-engine.io/wp/2020/06/21/fpc-3-2-0-released-compatible-with-cge-docker-images-updated/ . It features various improvements, and allows https downloading too.
