### ISSUE TITLE
Lazarus Project Templates

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#172]
Transcribed from CGE Discord describing the problem and solution

@peardox 2020-07-20 at 13:42
Is there some way to add some basic CGE Application templates to the Lazarus 'New Project' dialog? I'm just creating a 'Trivial Application' that has all the boilerplate with some extra basic navigation key bindings to load a model and display it and it'd be cool to be able to add it to to the default Lazarus templates.
Ooh - never mind, writing the Q prompted me to change my Google search and I found https://wiki.freepascal.org/Project_Templates
Project Templates

@michalis 2020-07-20 at 13:47
Indeed, Lazarus packages (installed at design-time) can add new templates. And yes we should use it :slight_smile: 

They should show the same templates as CGE editor.

And CGE editor templates should have an LCL versions too.

IOW, in both cases (CGE editor and Lazarus), the same "New project" templates should be available, and there should be options for TCastleWindowBase and TCastleControlBase approach. Note that we advise in CGE to use TCastleWindowBase approach, as this works on all platforms, and allows to use our Android/iOS services.

@peardox 2020-07-20 at 14:03
I'll go read and experiment

@peardox 2020-07-20 at 14:22
Hmm, the documentation is as up-to-date as usual - 08-08-2012 :frowning:

@michalis 2020-07-20 at 14:23
Multiple existing packages should show this :slight_smile: Like pas2js.

@peardox 2020-07-20 at 15:40
I'm following the instructions in the Lazarus Wiki for now. I've got a decent does slightly more than nothing project (the scene rotates in Y every 4 seconds) I'm gonna try converting to a template.

Once I've done that I'll ask in Laz Forums about adding it to the default 'New Project...' options. There are bound to be some useful features added in the last 8 years so that's a good place to ask I guess.

Once everything is working I'll have a bash at adding the CGE editor templates as well.

@michalis 2020-07-20 at 15:46
For the LCL project template, please keep it similar to existing CGE editor templates, just converted to LCL :slight_smile: I designed them carefully to showcase the most CGE possiblities :)

For adding new projects to Lazarus, I'm guessing it's easiest to look at examples: lazarus/components/pas2js/pjsdsgnregister.pas shows how pas2js adds a new project.

Remember that we'd like to show the same projects in both options. So our package should allow to create (through Lazarus "New Project")  the same templates as CGE editor. This way we maintain only one set of templates, not separate templates for Lazarus vs CGE editor.

@peardox 2020-07-20 at 16:31
The template registration stuff looks very back-to-front

pjsdsgnregister.pas is a unit that writes other files then registers the template - how extremely primitive.

Why not have an application that takes a set of templates then outputs the equivalent of pjsdsgnregister.pas instead?

I'm going back to the Wiki to try to get my test template working then I'll think about writing an application that turns my little template into a unit (but first I'll ask if anyone's already written it)

@michalis 2020-07-20 at 16:38
We have file_to_pascal_string when we have to convert a unit into a Pascal string.

But for this Lazarus package, our package should just determine the CGE engine location, and copy files from there (just like the editor is doing). This will require setting up environment variable CASTLE_ENGINE_PATH, which we can make more user-friendly (using Windows installer, and have an option for this in CGE editor).

IOW, do not follow the lazarus/components/pas2js/pjsdsgnregister.pas approach of "embedding" the template in Pascal source code, as it's not maintainable for us -- our inital templates are just larger pieces. Instead our equivalent of TProjectPas2JSWebApp.CreateProjectSource should just copy files from CastleEnginePath.

CastleEnginePath is in ToolCommonUtils unit. I would say that for package, it can be adjusted (so do not use ToolCommonUtils , instead define in package registration something similar). Package should not use caching (CastleEnginePathIsCached), it should use function GetCastleEnginePathFromEnv: String; from there, adjusted to report warnings using Lazarus-standard way.
In general, in my approach I want very much to avoid generating a Pascal unit based on other units :slight_smile: We can make it simpler, we can just copy files in our equivalent of TProjectPas2JSWebApp.CreateProjectSourc.

@peardox 2020-07-20 at 16:56
Ahaaa - components/projecttemplates/README.txt

@michalis 2020-07-20 at 16:57
( Oh, and Lazarus package can also ask user "where is your CGE located" when user tries to use sthg like "New Project -> Application -> Game (Castle Game Engine)" and other methods to determine  CastleEnginePath failed. 

That's just my addendum to above :slight_smile:  )

**Comment by peardox** [comment]
Another note to self...

@peardox Sure, you can reuse code between TCastleWindowBase and TCastleControlBase versions of the applications. Practically allCGE classes are the same in both approaches, it's only that in one case you insert UI stuff in TCastleWindowBase , in the other case you insert it into TCastleControlBase.

Note that this is not just about CastleEngineManifest.xml. You can use CastleEngineManifest.xml with LCL-based (TCastleControlBase) applications too, see lazarus_project and build_using_lazbuild description on https://github.com/castle-engine/castle-engine/wiki/CastleEngineManifest.xml-examples . In this case CGE build tool compiles using lazbuild under the hood, not direct fpc calls, and thus it can use LCL and other Lazarus packages out-of-the-box.

**Comment by peardox** [comment]
Despite what Trello thinks I've used it several times in the last month...:)

**Comment by peardox** [comment]
This now has a repo at https://github.com/peardox/templates

It should be noted that project templates itself is broken so a forked fixed version with CGE specific options is on my ToDo list (e.g. don't produce the Lazarus / Mac versions)

It should be noted that the current test template is a recent TrivialApp with some of un-required code

My constantly-evolving TrivialApp repo is the basis of the templates, the template itself is designed to be as Lazarus AND build-tool friendly as possible.

The template is at the Castle-Editor friendly stage whereby the sample apps in Editor could be trivially adapted to work with the templates (but templates fork is also required - catch 22...)

**Comment by michaliskambi** [comment]
1. The fact that you need to copy `data` manually makes it problematic. 

    The templates are aimed for people who are beginners in CGE. This may be their first contact with the engine, so it should work out-of-the-box.

    I wonder whether just adding all data files to the Lazarus project will fix this? The Lazarus project may contain any files, not only Pascal.

2. Ideally, templates should also be available as part of our `castle_components.lpk` package, as that is what many people will install, as https://castle-engine.io/documentation.php says so`. That is, "New Project -> ..." should offer new CGE-related options as soon as you install `castle_components.lpk`.

    For this reason, I still advise to research how to do it like in Pas2Js packages I referenced long time ago. It has to setup whole project, all files, in a way that is ready to work.

3.  The approach in your TrivialApp (combined TCastleWindowBase + TCastleControlBase) is not something I'd like to advise to users of the engine. So I would not like it to be a template we offer for new engine users.

    For all normal game development, it is advised to just use TCastleWindowBase. If you need integration with existing application done using LCL, then TCastleControlBase is the way to go. A combined approach, like in your TrivialApp, is not something I'd advise -- as it inherently makes a non-portable application, since you want to add some functionality using LCL, knowing that it will not be visible in TCastleWindowBase. I realize that you spend time making this "combined" approach and it works for you, but it's just not something I see recommending for normal engine usage.

    The templates installed by `castle_components.lpk`  should just refer to the existing 4 templates, the same ones as available using the CGE editor. We can also extend these templates to have (separate) TCastleControlBase-based templates. In any case, both CGE editor "New Project" and Lazarus "New Project" should expose the same templates -- otherwise we confuse users.

**Comment by peardox** [comment]
1) As I said, this is on my ToDo list
2) So is this
3) TrivialApp is not a combined TCastleWindowBase + TCastleControlBase. The (optional) Lazarus form stuff is in its own unit. Essentially **Project**Laz.lpr / guiinitialization.pas and **Project**App.lpr / appinitialization.pas are just the Lazarus and Application startup code for maingameunit.pas which is the actual naib project entry point.

**Comment by michaliskambi** [comment]
I'm closing this -- I don't see activity on this, and realistically we don't need integration with Lazarus templates. 

CGE editor allows to create "New Project" using templates that we recommend (using TCastleWindow).
