### ISSUE TITLE
Castle-Editor can create bad files

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#173]
To replicate

Create a new project from any template and name it, for example 3d_fps_game. The generated CastleEngineManifest.xml looks like this...

`<?xml version="1.0" encoding="utf-8"?>
<project name="3d_fps_game"
  standalone_source="project3d_fps_game_standalone.lpr"
  game_units="GameInitialize"
  qualified_name="com.mycompany.project3dfpsgame">
</project>
`
However the editor creates 3d_fps_game_standalone.lpr that starts with...
`program 3d_fps_game_standalone;`
so it won't compile

Work around - don't name a project with a leading numeric

**Comment by michaliskambi** [comment]
This should be fixed since a ~month in https://github.com/castle-engine/castle-engine/commit/98dda15a9c4632e5525947412bffe487bfd75b85 . Can you update to the latest version and recheck?

**Comment by peardox** [comment]
git pull-ed to bring in TCastleDownload on Monday

git pull-ed just now ...

`From https://github.com/castle-engine/castle-engine
   c348039fb..f1f84328b  master     -> origin/master
Updating c348039fb..f1f84328b
Fast-forward
 tools/build-tool/code/castle-engine.lpr | 14 ++++++++++----
 tools/build-tool/code/toolproject.pas   | 21 +++++++++++++++------
 tools/common-code/toolcommonutils.pas   |  5 +++++
 3 files changed, 30 insertions(+), 10 deletions(-)`

These were getting live version from Git after I played with them early in the AM

Same issue persists

**Comment by michaliskambi** [comment]
I have retested this, and it's definitely fixed. Using `3d_fps_game` as project name results in `project3d_fps_game_standalone.lpr` file (note the `project` prefix) and it contains 

```
program project3d_fps_game_standalone;
```

inside. So all is correct.

From your symptoms, it looks like you have new CGE editor, but you did not recompile the build tool from new CGE code. The build tool generates LPR contents under the hood. I'm closing this issue -- please recompile the build tool (and make sure that this is used by CGE editor, i.e. it exists on `PATH`) and test. If the problem remains, please reopen.
