### ISSUE TITLE
Reset / Rebuild Editor 'Open Recent Project' 

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#174]
I'm testing a lot ATM so for me this 'feature' is annoying but its something that can affect normal use as well

When displaying the 'Open Recent Project' dialog Editor blindly shows a list from some config file

It would be better to check if the paths shown actually exist and offer to remove any missing entries

There are issues with the simplistic approach described above - the most obvious being that user may have some projects on some form of external storage (USB stick / network drive etc) that are not currently available therefore three options spring to mind...

1) As-is (no changed)
2) Simplistic remove everything not found (which works fine in my case)
3) Display list of missing projects with checkboxes - delete marked items

Optionally have a never ask me / always ask me option

This could live on the preferences page as you don't actually want to change the options often / ever after initial selection

**Comment by michaliskambi** [comment]
Agreed. I'll do something about it.

I'm leaning toward a solution where we

- Detect whether project still exists, and if not -> it is still available on the list of recent projects but with a suffix like "(project files missing)"

- Choosing to open a project that does not exist just offers you an option to remove it from recent projects.

This is something like AD 3, but with a simplistic UI :)

I'll look at what others do too (Unity, Visual Studio, Android Studio).

Personally I'm using Emacs + Projectile for "projects" management and it removes non-existent directories at run (but I had to configure it explicitly to do it).

**Comment by michaliskambi** [comment]
Done:)

**Comment by peardox** [comment]
One small comment on this one

The button says 'Open Recent Project' - which it does (plus removes dead options)

If you have several recent projects I'd expect the order or the projects to reflect the most recently opened one. It doesn't do this - the list remains in the same order if you open an older one, edit it and save it (making it the most recent project)

**Comment by michaliskambi** [comment]
Indeed the order should change, will fix this :)
