### ISSUE TITLE
examples\2d_standard_ui\zombie_fighter bug

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#175]
I've started compiling up the examples so I can document them

I got to examples\2d_standard_ui\zombie_fighter and we get this screen

![zombie_fighter_1](https://user-images.githubusercontent.com/1549219/88466854-8c3fe480-cec8-11ea-8d91-a1f006610f15.png)

It says 'Click on a zombie sprite to show a dialog', if you do so you get this screen

![zombie_fighter_2](https://user-images.githubusercontent.com/1549219/88466882-d4f79d80-cec8-11ea-87b4-d283c4eda76d.png)

Well, it's a dialog, sure enough. I doubt it's the intended one though :)

The above also applies to examples\2d_standard_ui\zombie_fighter_alternative_short_lived_states

There are some depreciation notices on compiling

I also experienced the Access Violation yesterday when trying out Model Viewer from Editor but this was on Android and I couldn't replicate the issue

**Comment by michaliskambi** [comment]
Thanks! Fixed both `examples\2d_standard_ui\zombie_fighter` and `examples\2d_standard_ui\zombie_fighter_alternative_short_lived_states`.

I also updated the code to not use deprecated API.

**Comment by peardox** [comment]
Cool, I'll go do a pull and get to see the proper dialog :)
