### ISSUE TITLE
examples\3d_rendering_processing bug

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#176]
You're not handling the case of example being called with no arguments

Usage if missing is usually expected

examples\3d_rendering_processing> .\placeholder_names.exe
Available placeholder detection methods (2):
  blender
  x3dshape
An unhandled exception occurred at $00000001000511E8:
EInvalidParams: Expected 2 more parameters
  $00000001000511E8
  $0000000100001C85
  $0000000100001F46
  $0000000100014E10
  $0000000100001A90
  $00007FFC85876FD4
  $00007FFC85B1CEC1

**Comment by peardox** [comment]
Oh - stick the attached in examples\3d_rendering_processing will you while you're fixing?

[compile-all.txt](https://github.com/castle-engine/castle-engine/files/4976945/compile-all.txt)

Rename it compile-all.bat (Git won't let me upload a bat file)

It's simply a very basic Win/DOS batch file to compile all the examples in examples\3d_rendering_processing - saves typing

**Comment by michaliskambi** [comment]
Fixed.

Note that this example (like all other single-file examples) has a documentation at the beginning of the source code.

> Rename it compile-all.bat (Git won't let me upload a bat file)

I'm afraid I don't want to maintain such file. You can already compile all the examples with one command: `make examples` at the CGE top-level (it requires having Cygwin and some Cygwin tools, but this is something you set up one time, see `Makefile` comments). This command is also used+checked by Jenkins on all the systems (Linux, Windows, macOS) so it really covers all the examples.
