### ISSUE TITLE
Example asynchronous_download memory leaks

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#180]
Tested on Win10 Pro x64, Ubuntu 20 x64 + Android Aarch64 (compiled via Docker image, deployed to Huawei P Smart 2019) all using FPC 3.2.0 and latest unstable CGE

Eventual changes to original - downloaded smaller files to see if that was an issue for Android

Windows 10 - Killing program while downloads in progress run from Lazarus IDE results in External SIGSEGV

Linux x64 - Compiled using "castle-engine compile --mode=debug", run from cmd using "./asynchronous_download > debug.log 2> error.log" appears to function but the error log shows the problem (files attached)

Android Aarch64 - Built with docker image, deployed to device. When the "Start Downloads" button is pressed the app appears to close, further inspection reveals it's still there in the background as in the same state as before the button was pressed. Bringing it back to front and repeating results in the same results.

When testing on Win10 under Lazarus with debugging enabled frequent reports mention castledownload_url_http_fphttpclient.inc which (after MANY dialog boxes) eventually come back to the start button click event.

[debug.log](https://github.com/castle-engine/castle-engine/files/5066693/debug.log)
[error.log](https://github.com/castle-engine/castle-engine/files/5066694/error.log)

**Comment by michaliskambi** [comment]
Memory leak on Linux is indeed a known thing, it's a TODO in https://github.com/castle-engine/castle-engine/blob/master/src/files/castledownload_url_http_fphttpclient.inc . I was fighting with it, but with no success so far, so I just postponed it. I didn't notice any negative side-effects, I mean your program will eat more and more memory but everything works as expected (unlit the RAM ends, I guess :), but the leak isn't large, it's not the stream contents).

On Android, the TCastleDownload for now doesn't do asynchronous downloading. So it will just hang in `Start` and wait for download to finish. So it should work (but by hanging your application), although I didn't test it now. Of course the plan is to adjust  the code on https://github.com/castle-engine/castle-engine/blob/master/src/files/castledownload_url_http_android.inc to also do asynchronous downloading. It requires completely new code from desktops, there was just no time to do it yet :) Ping me (create new ticket) when this is priority for you.

> Windows 10 - Killing program while downloads in progress run from Lazarus IDE results in External SIGSEGV

I didn't see it, but I didn't test on Windows now. Will take a look.

**Comment by peardox** [comment]
I just built the Windows version with build-tool in release mode and there's no SIGSEGV reported. The memory link is reported (in a myriad of dialogs) if built using Lazarus with heaptrc turned on,

The Mac version will presumably have the same issues as Linux but I've got to get that one not using X11 (alternate lcl unit build?)

I guess a really awful option is to have a separate downloader sub-program I could call when wanting download facilities (god that option sucks)

iOS starts the first download then does nothing - same story as Android I presume?

Does the blocking Download work on mobile? Can you set headers / read responses with blocking? At least that way mobile would have a sucky way to work.

As for timeframe - product's running late as it is and the government may stop my only income (unemployment) soon (hence alternate mobile method idea). There's not a lot of cash in writing free software :(

**Comment by michaliskambi** [comment]
> iOS starts the first download then does nothing - same story as Android I presume?

No, iOS should be a very different story. On iOS we use FpHttpClient asynchronously, exactly like on desktops. On iOS, it should just work already. 

> Does the blocking Download work on mobile? Can you set headers / read responses with blocking? At least that way mobile would have a sucky way to work.

Blocking should work on both Android and iOS. In case of iOS, the headers can be set, in case of Android no.

That said, I didn't test the above statements recently. I didn't yet run asynchronous_download on Android or iOS myself, so new changes (after TCastleDownload) are now tested yet there. I'll test them, and post a new answer when I know :)

**Comment by peardox** [comment]
I've just tested blocking - using Download rather than TCastleDownload using an old project that worked perfectly before TCastleDownload but now gives an Access Violation under Windows.

The project functions OK under Linux, dies horribly on Windows - Mac, still setting it up (again - must go finish the setup now)

Any test will most likely fail on any non-Linux platform but just in case...

The currently non-working project (used to) download a load of data from three sites then analyse it (partially - more to do there yet)

Project is here if you want something more complex than a Download equivalent of Hello World to test https://github.com/peardox/MTGADownloader - note that it uses Download only. Its a bit confusing, especially the wizards domains parts, as it has to build a download list from a complex endpoint.

**Comment by michaliskambi** [comment]
1. I confirmed and fixed the problem with synchronous download failing in https://github.com/peardox/MTGADownloader . 

2. I hoped that it would also solve the "SEGFAULT when interrupting asynchronous_download on Windows", but it didn't. I was not yet able to fix it properly.

    Note that the problem seems to disappear when running without debugger, and without heaptrc. In my tests:
    - Running in Lazarus debugger exhibits the problem. 
    - Compiling with the build tool like `castle-engine compile --compiler-option=-gl  --compiler-option=-gh` also exhibits the problem. 
    - But compiling with the build tool, in debug or release modes (`castle-engine compile`, `castle-engine compile --mode=debug`) seems to produce a version that doesn't show the problem.

**Comment by peardox** [comment]
That's weird... Is it possible that the debugger is what's causing the issue? I note in the comments in TCastleDownload that a race condition can occur. The debugger does introduce quite a lot of overhead so it's not inconceivable that the race fails if debugged.

I noticed another issue this morning with Download randomly raising an exception regarding name resolution (couldn't find https://mtgjson.com every so often). Would this kind of thing happen in the section you just fixed (i.e. no longer be the case)?

I was about to write a test that downloads many hundreds of files and stick it in a loop to see what was going on (I need the methods anyway) - I should have some way to handle to attempt repeat-if-fail anyway...

**Comment by michaliskambi** [comment]
There is already a code in place to prevent this race, it can be activated by defining a symbol now. However, my experiments show it is unrelated to the bug we're observing.

The name resolution shouldn't be related to this. It's performed inside FpHttpClient early before any downloading, and I didn't change the way it works, and it works OK for me. If it fails for you, make sure your DNS servers are working.

**Comment by peardox** [comment]
In the case of MTGDownloader Windows and Linux both work now (Apple next) using Download - I'll try TCastleDownload tomorrow.

The situation with the SIGSEGV no longer happens and the debugger is usable as long as heaptrc isn't enabled. As we know there's a small leak it's something that can at least be worked around now - use local files when checking the help during development. This way it's possible to check nothing ELSE is leaking (which, of course, needs to be checked) but use remote files as required for production...

I want to do some Patreon checking with TCastleDownload as well - that should be a good real-world test of Asynch as it'll use OAuth to access the Patreon API.

**Comment by peardox** [comment]
`On iOS, it should just work already.`

As I just got iOS building again I tried out asynchronous_download with the newest version

It starts then sulk... i.e. displays the first download message then nothing further happens.

This screengrab is my iPad Pro running asynchronous_download where I've changed the first URL to something I can watch. The server log reports no accesses for the requested file while running the test - i.e. the app displayed something but never actually got as far as the server.

![ipad](https://user-images.githubusercontent.com/1549219/90671350-79f96200-e24c-11ea-99bb-64a951030148.png)

**Comment by peardox** [comment]
Hmm - odd new revelation regarding the memory leak

I've just been setting up some of my AArch64 boxes with dev systems

My Jetson Nano runs asynchronous_demo fine - no heap errors reported after the run

I've got 2 Raspberry Pis as well but the one I've been testing on complains about the bit-depth (can't create 16 bit, but I am running it over VNC)

**Comment by michaliskambi** [comment]
Memory leaks with TCastleDownload and FPC are fixed now by https://github.com/castle-engine/castle-engine/pull/581 .

**Comment by peardox** [comment]
Ohh, thisa is an old one :)
