### ISSUE TITLE
Download Memory Leak

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#188]
I'm getting bigger memory leaks and I've found out where it appears to be starting

More files downloaded = more memory leaks and I'm currently grabbing 311 files (306 come from URLs in 2 json files) so  had a look around...

In castledownload_url_http_fphttpclient.inc on lines 259 - 261 you've got this...

```
        HttpResponseHeaders := TStringList.Create;
        HttpResponseHeaders.NameValueSeparator := ':';
        HttpResponseHeaders.Assign(Client.ResponseHeaders);

```

If I comment out those three lines then HttpResponseHeaders is never populated and the leak vanishes. Therefore it looks like that stuff can't be being freed properly.

Tried it with just the TStringList.Create -> memory leak, no create -> no memory leak (just in case something was happening with the Assign)

The downside of this, of course, is that now I don't have access to the response headers

**Comment by michaliskambi** [comment]
The `HttpResponseHeaders` leak was trivial to fix, many thanks for catching this.

Testing on Linux now, I still have memory leaks unfortunately, and the `HeapTrc` output only tells me it's "somewhere in `TFpHttpClientJob.Execute`". I didn't test it now. Leaving https://github.com/castle-engine/castle-engine/issues/180 open.
