### ISSUE TITLE
Camera.EffectiveProjectionFar return 0

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#192]
I noticed this when I was developing SSR (hence the reason for fixed values in pull request).

If I load a X3D file in view3dscene without setting Viewpoint or Fog, Camera.EffectiveProjectionFar return 0. Maybe there's another way to access default far value that I was not aware of? Tried with Camera.ProjectionFar & Viewport.Projection.ProjectionFar but those properties also return 0.

**Comment by michaliskambi** [comment]
I will look into it. `Camera.EffectiveProjectionFar` is the right one to look at, it should work.

`Camera.ProjectionFar` is the user-specified far value. That is, it overrides the automatic detection. So it's normal that it stays zero, if never assign there a non-zero value explicitly.

`Viewport.Projection.ProjectionFar`, while it should work (be non-zero) , it accesses deprecated `Viewport.Projection` (while I'm not yet 100% decided yet, it seems that all practical use-cases of accessing it are covered by something else that is simpler, so for now I'm leaning towards deprecating it and hiding from public API in the future, to keep API simpler).

Maybe you're accessing them before they get calculated? Do you have a testcase? If that's the problem, then I can easily fix it:)

**Comment by Kagamma** [comment]
I access it inside TGLSLScreenEffect.SetupUniforms

Here's the screenshot of the value I got when access it inside TCastleViewport.TSSAOScreenEffect.SetupUniforms:
![test](https://user-images.githubusercontent.com/7451778/91509639-0d91f900-e905-11ea-8de5-7d96803469d1.png)

**Comment by michaliskambi** [comment]
Ah, this is actually `ZFarInfinity`, and correct.

As the docs say https://castle-engine.io/apidoc-unstable/html/CastleCameras.TCastleCamera.html#EffectiveProjectionFar , it may be equal to `ZFarInfinity`, which is zero. This indicates we use a projection matrix that has no far clipping plane. Which we do by default, for perspective projection, when `Viewport.ShadowVolumes` = true (default). It causes no noticeable loss of precision (proof of it in one paper about shadow volumes :) ).

`Viewport.Camera.EffectiveProjectionFar` and `Viewport.Projection.ProjectionFar` will be equal to `ZFarInfinity` in this case.

If you really need some finite value, you can use `Viewport.Projection.ProjectionFarFinite`. But note that it is *not* actually used, i.e. only the `Viewport.Camera.EffectiveProjectionFar` and `Viewport.Projection.ProjectionFar` are real values. The `ProjectionFarFinite` is just for information.

That is also why the commented lines in SSAO code, visible also on your screenshot, use `ProjectionFarFinite`. Understandably, if you use `ProjectionFarFinite` as some "estimate of scene size", then `ProjectionFarFinite` makes sense.
