### ISSUE TITLE
CGE 'Kitchen Sink' demo

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#194]
Awkward title, I know and here's the reason why I called it the Kitchen Sink demo.

This is for illustration of a very helpful reference example - See https://examples.sencha.com/extjs/7.2.0/examples/kitchensink - This demos every control available in SenchaJS (there are similar demos for other JS libs)

If CGE had a similar example this would be extremely useful for reference. Note that the 'kitchen sink' demos one control per page making clear the expected resultant design of using that component.

I should also point out that the 'kitchen sink' component demos are, in reality, often variations on a theme - i.e. using one control with different calling arguments.

Borrowing this concept and implementing it in CGE-Editor therefore provides clear layout and example code for any given UI component.

I realise that this is a never-ending task but it's a highly desirable educational tool.

**Comment by michaliskambi** [comment]
I am going to call this component_gallery or user-_interface_components_gallery and this is an excellent idea. A number of pages, almost everything done by CGE editor, each page focused on 1 UI component, showing this component a few times in some typical variations 

- viewport (perspective, Ortho, with and without transparent)

- button (default look, customized colors, customized by 3x3 images)

- label (various alignments, HTML text...)

- horizontal and vertical groups

- image (various alpha treatment, various scaling ways)

- base stuff (at TCastleUserInterface, this page would show border, fullsize, etc)

- scrolling area

I'm writing this on phone from my head. Final version would have good order of pages. On the left a way to choose current page (as buttons in vertical group), and also next/previous page buttons. On top of each page a header telling what it is about.

**Comment by michaliskambi** [comment]
Oh and this will make obsolete https://github.com/castle-engine/castle-engine/tree/master/examples/2d_standard_ui/show_various_ui_controls , so it will get removed.

It has a similar purpose ("gallery of UI controls") but was not updated with many controls and features (because without the idea of "pages" I run out of space :) ) and doesn't use editor.

**Comment by peardox** [comment]
Can I suggest that in cge-component-gallery when you click on a sample the app shows the properties that were used to achieve that specific look. These can be just the ones that ain't the default values.

e.g, on 'buttons -> Custom Background Image' show the properties that set the image and the border.

This way a user can easily know that to create the same kind of effect as shown they only need to set some image + border properties.

The main advantage of adding this is that someone can have cge-component-gallery open at the same time as castle-editor and/or a text editor and know exactly what's required.

When the app is more complete (it'll never be finished...) it would also be advisable to release it on Android + iOS so a second-screen becomes convenient for reference

**Comment by michaliskambi** [comment]
You can already see it in the CGE editor, select the component and in "All" tab the properties displayed bold have non-default values.  That's just like in Lazarus / Delphi when designing forms.


![Zrzut ekranu z 2020-11-29 00-31-33](https://user-images.githubusercontent.com/1076978/100528195-437f9b80-31da-11eb-8af7-4abd686fbf3e.png)

**Comment by peardox** [comment]
So you have to constantly save your project, switch to component_gallery, write down the properties you're after for your project, switch back to your project and set the properties...

Not exactly user-friendly?

**Comment by michaliskambi** [comment]
If you want to experiment with component_gallery in another window, while also playing with your own project, you can have them both open at the same time. It is OK to have 2 instances of editor open.

**Comment by michaliskambi** [comment]
You can also copy components from one project's design to another (whether they are in 2 editor instances running simultaneously, or you have 1 instance of editor and you switch back and forth).

**Comment by michaliskambi** [comment]
Although I can also use existing Tooltip mechanism, to show info at runtime. So we can have both ways:)

**Comment by michaliskambi** [comment]
12 pages done, see https://castle-engine.io/wp/2022/01/30/example-component_gallery-12-pages-showcasing-user-interface-components-new-example-transform_primitives-showcasing-primitives-in-viewport/ . All screenshots on https://castle-engine.io/user_interface .

**Comment by michaliskambi** [comment]
Closing, as practically speaking I like the current state: `examples/component_gallery` shows all important user-interface components. Other components (like stuff inside a viewport, or physics joints) have their own demos.
