### ISSUE TITLE
Set StencilBits to non-zero value for castle-editor

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#197]
I think this field should be set to non-zero value for castle-editor so that Shadow Volume could work out-of-box

**Comment by michaliskambi** [comment]
Absolutely, done :)

![Zrzut ekranu z 2020-09-13 01-48-21](https://user-images.githubusercontent.com/1076978/93006972-4e277e80-f563-11ea-8bb1-34e10888af82.png)
