### ISSUE TITLE
Typo in build tool tutorial

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#20]
https://github.com/castle-engine/castle-engine/wiki/Build%20Tool#create-manifest

```
  <package>
    <include path="documentation/*" recursive="True" />
    <include path="README.txt" />
    <include path="COPYING.GPL2.txt" />
    <exclude path="*.xcf" />
    <exclude path="data/internal/*" />
  <package>
```

Last one should be a closing tag:

```
  <package>
...
  </package>
```

**Comment by michaliskambi** [comment]
Fixed, thanks!

**Comment by michaliskambi** [comment]
In related news, I have also added you to the castle-engine team on GitHub:) You should be able now to make changes (to wiki, or code...) directly. You have contributed a lot to improving the engine, so this isn't any surprise:) Welcome!

**Comment by eugeneloza** [comment]
Thanks a lot Michalis! I really hope I'll be of some use :)
