### ISSUE TITLE
Correct UTF-8 characters (e.g. Russian) when pasting using Ctrl+V in TCastleWindowBase

### ISSUE THREAD

**Issue by IldusEps** [castle-engine/castle-engine#200]
Russian (and possibly other non-English characters) are not displayed correctly when using Paste with Clipboard (Ctrl + V).

**Comment by michaliskambi** [comment]
Adding info from the Discord: This ocurs on Windows (10?), with TCastleWindowBase, and any edit control like TCastleEdit.

**Comment by IldusEps** [comment]
Yes, Windows 10.
