### ISSUE TITLE
Way to detect if component is running in "design mode" or "run mode"

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#204]
This problem arise when I am working with custom components for castle-editor.

Basically, if the component contains logic code that make changes to publish properties, these changes also make its way to save file which is not a desired effect. I think we should have some sort of flag (a global variable maybe?) to determine if the current working environment is in "design mode" or in "run mode".

**Comment by michaliskambi** [comment]
We have this :) For now, just a trivial global Boolean `CastleDesignMode`, in `CastleUtils` unit.

**Comment by Kagamma** [comment]
Thanks. Didn't notice we already have it :)
