### ISSUE TITLE
Wiki addition: "adb devices" shows no connected devices

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#21]
in https://github.com/castle-engine/castle-engine/wiki/Android "Test compiling and running android_demo" -> "p.5"

I think it's a good idea to mention that running
`adb devices`
shows no devices unless USB debugging is "on" on the device (had a lot of trying-and-failing until I've figured out this simple requirement :)).
e.g. "In order to install and run the device from the destop PC you have to enable USB debugging mode on your Android phone/tablet"

**Comment by michaliskambi** [comment]
Absolutely, agreed. I added a paragraph about it to https://github.com/castle-engine/castle-engine/wiki/Android#test-compiling-and-running-android_demo . Thanks!
