### ISSUE TITLE
Can Viewport.Projection be un-depreciated please?

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#212]
The very fact that it's depreciated essentially means it'll eventually vanish

I'm using it to calculate mouse to plane intersection. Initially I just wanted where's the mouse in X/Z when Y = 0 but I just re-used it (yesterday) to get a where X/Y are for Z = 0

**Comment by michaliskambi** [comment]
You can use `TCastleViewport.PositionToRay` (non-deprecated) now to implement such routines. It is used by `PositionToCameraPlane`, `PositionToWorldPlane` already. This way you get a ray (two 3D vectors, origin and direction) and can use our collision routines to do anything with it.

That is why I hesitated, but eventually decided to keep `TCastleViewport.Projection` deprecated. As the engine API is bigger than it should be, I'm trying to limit it :)

Closing it. Let me know if you have a use-case for `TCastleViewport.Projection` that is not satisfied by existence of `TCastleViewport.PositionToRay`.

**Comment by peardox** [comment]
Yeah, I modified my YPlane intersection code - basically the WorldPlane version using Y rather than Z and everything seems OK
