### ISSUE TITLE
iOS: Undefined symbols for architecture arm64: "FPC_RESSYMBOL"

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#219]
Building using latest XCode for iOS I get that error

Log file attached

[Build target Trivial Mobile App_2020-11-02T06-48-10.txt](https://github.com/castle-engine/castle-engine/files/5473247/Build.target.Trivial.Mobile.App_2020-11-02T06-48-10.txt)

**Comment by michaliskambi** [comment]
On first glance, please test is it related to your resource usage. Surround `{$R *.lfm}` with `{$ifndef cgeapp}...`.

I'm not sure why they fail at linking, but the lfm is definitely not necessary for TCastleWindowBase variant. It would also explain why compiling iOS applications works OK for me, using CGE examples.

**Comment by peardox** [comment]
Argh...

Yep, {$ifndef cgeapp}...{$endif} fixed it nicely

Odd that Android worked with that in - I'd better check that build out with the alteration

That makes my Trivial template work on four platforms by the look of it, five if you count linux-arm and I imagine it'd also work on the Switch as it just de-Lazarus-es the project
