### ISSUE TITLE
Bad normals in GLTF export

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#225]
At least that's what you recon at the mo...

Attachments as requested
Blender File - https://peardox.co.uk/blender.rar
You'll also need this addon... Godot Game Tools - https://peardox.co.uk/Godot_Game_Tools.zip

Before you open the .blend you'll need to install this addon so extract Godot_Game_Tools.zip then in blender install thee addon you'll find in Godot_Game_Tools/blender/godot_game_tools.zip. With the addon installed and activated you'll see the following screen when you load the .blend

![blender](https://user-images.githubusercontent.com/1549219/99326335-0d542a80-2870-11eb-8e89-f416df6175e6.png)

In the Godot Game Tools menu at the bottom of the panel you'll see 'Export Character'. Expand that panel, enter a name in the Character Name edit box then select an export path in the file selector below. 

A new option appears allowing you to export the project to GLTF or GLB  - click the 'Export Character File' button and a new .glb or .gltf will be created in the export path you chose.

The other thing worth looking at is the Animations panel, select one and hit the Play Animation button to see the animations I chose for this test, you can switch between them at will while it's playing.

For proper usage instructions I'll have to write up a proper how-to as there are basically zero instructions relevant to the current release (it took me over a day to get it working this far but I had been trying with a custom model which I couldn't get to work).

The addon allows you to take a load of Mixamo animation rigs and apply them all to a Mixamo model resulting in a GLTF/GLB with all the animations you chose. The plugin is really useful and (almost) works with CGE. As everything is combined you've only got the mesh + textures stored once along with all the animation rigs making for a nice compact solution.

As noted above I've only been able to get it working with the Mixamo models so far (hopefully I'll work the rest of it out)

Once I write up the CGE-friendly how-to (soon - like after my next todo on the list) you can try this from scratch. You may get it working without a guide but it's far from obvious - the most recent instructions are here https://www.youtube.com/watch?v=kwMB_486xaU (May 12th 2020)

**Comment by michaliskambi** [comment]
After quick testing, I can reproduce the problem also straight using glTF exporter from Khronos (that is, the "stock" glTF exporter in Blender, that you use by Blender _File -> Export -> glTF 2.0_ menu).

So the problems is also without Godot Game Tools. So at least we know GDT are not to blame.

BTW, I see GDT export applies some transformation to the data (to select some animations), and then simply calls the regular Khronos glTF exporter. So, that is good, and no wonder it will share both features (and eventual problems, although in this case we most probably have CGE bug).This is a piece of code from GDT that just calls standard glTF or Collada exporter with predefined options:

```
        # GLTF
        if (character_export_format == 0):
            bpy.ops.export_scene.gltf(filepath=fileName, export_format="GLTF_EMBEDDED", export_frame_range=False, export_force_sampling=False, export_tangents=False, export_image_format="JPEG", export_cameras=False, export_lights=False)

        # GLB
        if (character_export_format == 1):
            bpy.ops.export_scene.gltf(filepath=fileName, export_format="GLB", export_frame_range=False, export_force_sampling=False, export_tangents=False, export_image_format="JPEG", export_cameras=False, export_lights=False)

        # Better Collada
        if (character_export_format == 2):
            bpy.ops.export_scene.dae(check_existing=True, filepath=fileName, filter_glob="*.dae", use_mesh_modifiers=True, use_active_layers=True, use_anim=True, use_anim_action_all=True, use_anim_skip_noexp=True, use_anim_optimize=True, use_copy_images=True
```
