### ISSUE TITLE
TTouchSensor events not being called reliably

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#227]
As per Discord

**Problem**

The TTsouchSensorNode events are not firing in a reliable manner. This issue occurs on every build platform I've tried - Windows, Mac, Linux, Android and iOS

The only version that works as expected is Windows Standalone

Every other version requires...
Desktop - move the mouse between clicks
Mobile - click twice

**Recreating the issue**

Build and run the following repo (simplest with castle-engine compile followed by ./HoverApp)

Sample project - https://github.com/peardox/Trivial

Load HoberLaz.lpi for Lazarus or use castle-engine compile for standalone / mobile versions (these use HoverApp.lpr + gameinitialize.pas). The code is all in maingameunit.pas and makes use of multiple ifdef cgeapp / ifndef cgeapp to make the unit Lazarus and Standalone capable.

There are four routines starting at line 116 that handle / set up the events. I've placed all of these in one block at the top-end of the source as nothing after SetSensor (i.e. line 200+) is relevant to this issue.

**Comment by michaliskambi** [comment]
Fixed :)

Things not really related to this issue that caught my attention in your code:

1. It's way easier (and sometimes, also way more efficient) to make the transformation of X3D graph right at loading, if you don't really need to do it afterwards. Currently your `TCastleApp.SetSensor` searches for 'HoverRacer' and 'TextureColor' each time, and is prepared to create touch sensor on-demand. It is usually simpler to just find/create necessary nodes when loading scene.

    In case of this code, this would be `TCastleApp.LoadScene`. So inside there, instead of `Scene.Load(filename);` you would do

    ```
    RootNode := LoadNode(FileName);
    // process RootNode, to find 'HoverRacer' and create TTouchSensorNode 'TextureColor'
    Scene.Load(RootNode, { owns RootNode } true);
    ```

    and the `TCastleApp.SetSensor` could just rely on a field like `MySensor: TTouchSensorNode` being set by last `LoadScene` call.

2. Recoloring the image as in `TCastleApp.RecolorImage`, which does it by processing image pixels on CPU, is a very inefficient approach.

   The efficient way is to write a GLSL effect that applies a color over the image. The GLSL effect can take a parameter (GLSL uniform variable) that influences what it does. I just did a demo of it for you: https://github.com/castle-engine/castle-engine/tree/master/examples/3d_rendering_processing/shader_effects .

   This will be way, way faster. Practically changing the color will be zero-cost. And shaders like this are really cheap, and it's all done on GPU.

3. In your CastleWindow-version, `TCastleApp` descends from `TWindowContainer`. This doesn't make the `TWindowContainer` features actually work.

    To use your own `TWindowContainer`, you should also create `TCastleWindowBase` descendant, and override there `TCastleWindowBase.CreateContainer` to create and return your custom `TWindowContainer` descenant.

    That said, it is hard to imagine a use-case for this now. The idea of "you can override `TWindowContainer`" made sense long time ago, when we didn't have better approach with overriding TUIState or other TCastleUserInterface.

    I have improved the docs of `TWindowContainer` to mention it all, and to deprecate `TWindowContainer`.

    In your application, your `TCastleApp` should just descend from `TComponent` -- you were not really relaying at all on it being related to `TWindowContainer`.

4. In general, you can probably make your approach (trying to use both `TCastleWindowBase` and `TCastleControlBase`) simpler by moving most of your functionality to `TUIState`, that can work both inside TCastleWindowBase and TCastleControlBase, and that can process events.

    It would also mean that LCL form can just "live" in a unit that isn't compiled at all by the TCastleWindowBase version of the application.

    I would heavily advise this, it would avoid a lot of `{$ifdefs ...}` you have now. The LCL form, and the TCastleWindowBase-specific gameinitialize.pas, would mainly just create your TUIState descendant. See manual, templates and examples for many TUIState usage examples.

5. I see you use `CastleGetTickCount64` to measure time. Instead, it is usually more comfortable (and is used throughout CGE code) to use [Timer](https://castle-engine.io/apidoc-unstable/html/CastleTimeUtils.html#Timer) or [TCastleProfiler, through Profiler singleton](https://castle-engine.io/apidoc-unstable/html/CastleTimeUtils.TCastleProfiler.html). They both offer more comfortable API to do time measurements.

    `CastleGetTickCount64` will stay public, but it's really only for internal use, or for people coming and expecting "just give me something like good, old `GetTickCount` that I know" :) Once you learn them, `Timer` and/or `Profiler` offer more comfort.

6. Note that you don't need a separate `TMyEventListener` class. You can most probably just move the `ReceivedTouchTime` and `ReceivedIsActive` inside `TCastleApp`.

    Some examples indeed define something like `TEventListener`, because simple examples don't use `TUIState` to handle events, and there's no "obvious class" where to define event-handling methods. This is essentially an error/confusion of the examples, that are planned to be all updated before 7.0 release -- most of them will use `TUIState`, and the need for `TEventListener` classes will disappear.

**Comment by peardox** [comment]
Well, I moved everything to TUIState and it ALMOST works

The App version (build with tool) raises an exception about Application.MainWindow needing to be set (which I've already done - twice)

https://github.com/peardox/TrivialApp

**Comment by michaliskambi** [comment]
( Leaving a comment here, for anyone who finds this by web search: the above is solved, see https://discord.com/channels/389676745957310465/389676745957310467/783813258992812074 and https://github.com/peardox/TrivialApp/pull/1/ )
