### ISSUE TITLE
TouchFix broke TextureChange

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#229]
While https://github.com/peardox/Trivial.git now changes on Touch properly it appears to have broken something else (or it just never appeared before owing to problem TouchSensor, can't decide which is broken)

If you compare pre-touchfix to post-touchfix you will see that the earlier version re-colors the model (this being the intended result), the later version no longer recolors anything, it cycles between four states going {do} defined in gltf -> un-textured -> use map texture as texture -> un-textured {repeat}

**Comment by michaliskambi** [comment]
Argh, I have an idea what did I break. I tried to make an additional optimization along the way, but it's not so easy. On it.
