### ISSUE TITLE
iOS publishing issues

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#230]
Trivial / Hover now works as expected on local devices - iPhone 6 + iPad Pro

Tried a build of Trivial for iOS to check out AppStore deployment - some warnings / errors, one a show-stopper - messages below (added numbers for reference)

1) IPHONEOS_DEPLOYMENT_TARGET - trivial, just needs changing in the master template - work-around, change in XCode

2+3) Yeah, we know Apple are the devil incarnate (ignore)

4) Eeek - missing armv7 version - can't publish (more accurately test publishing)

=================================
Showing Recent Messages
1) The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99.

2) /Users/simon/src/Trivial/castle-engine-output/ios/xcode_project/HoverApp.xcodeproj OpenGLES is deprecated. Consider migrating to Metal instead.

3) /Users/simon/src/Trivial/castle-engine-output/ios/xcode_project/HoverApp.xcodeproj GLKit is deprecated. Consider migrating to MetalKit instead.

4) /Users/simon/src/Trivial/castle-engine-output/ios/xcode_project/HoverApp.xcodeproj The linked library 'libPods-Hover Mobile App.a' is missing one or more architectures required by this target: armv7.

**Comment by peardox** [comment]
Oopsie - just realized, Mac's screwing up over the library filename, it's got spaces in it c/o caption

CastleEngineManifest.xml had...

`caption="Hover Mobile App"
`

Changing this to one word fixed the issue...

`caption="Hover"
`

**Comment by michaliskambi** [comment]
As for Apple deprecating OpenGLES -- Khronos is working on OpenGLES implementation, for both desktops and mobiles, on top of Metal. So when Apple will do their crazy move (remove OpenGL(ES)), expect many applications (including CGE, and all web browsers using WebGL, even Safari) to go through this compatibility layer.

Thanks for investigating the issue. The caption should not even be used for this (only project internal name, that cannot contain spaces) so it should be easy to fix.

**Comment by peardox** [comment]
Yeah, thought so

I hit another issue after renaming to get it uploadable that is annoying

I had transparency on the icon file, Apple won't accept this

I'm running through a complete fake publish to check things out, I'm worried about icons as some are missing (see grabs below)

<img width="1440" alt="Screenshot 2020-11-25 at 22 37 03" src="https://user-images.githubusercontent.com/1549219/100561606-426d6d80-32b1-11eb-8c1f-a71fd5fe18b9.png">

<img width="1440" alt="Screenshot 2020-11-25 at 22 37 17" src="https://user-images.githubusercontent.com/1549219/100561620-49947b80-32b1-11eb-8b5a-08a6a1ba85bc.png">

**Comment by peardox** [comment]
And - it just uploaded to Apple OK with a modified AppIcon + Caption (wow, light at the end of the tunnel). I've not published anything to apple for about 2 years and never a CGE app so it's worth going thru this dry-run

**Comment by michaliskambi** [comment]
I'm testing the build process on iOS now,

- with latest CGE,
- with FPC 3.2.0
- on macOS Catalina
- with Xcode Version 12.1 (12A7403)

Note that I'm testing using FPC 3.2.0 official installers for macOS (for native FPC on macOS, and for cross-compiler to iOS, as linked on https://github.com/castle-engine/castle-engine/wiki/iOS ). I couldn't get fpcupdeluxe to produce for me all needed combinations, for 3.2.0 or trunk.

Things work OK for me.

Note that IPHONEOS_DEPLOYMENT_TARGET and various other Xcode warnings can be ignored for now.

I'm building just by

```
castle-engine --target=ios --fast package
```

following our wiki docs. Afterwards I can use Xcode to build in Ad-Hoc mode and upload IPA file to TestFairy ( https://www.testfairy.com/ ), this is a handy way to test iOS applications without going through the creation of application on the Apple website. (But you need to first add your iOS device id to your developer profile, to be able to install applications distributed this way.)

I was testing with CGE examples/2d_dragon_spine_game, that has space in caption (`caption="Dragon:Castle Game Engine Demo"` in `CastleEngineManifest.xml`).

Tested also your https://github.com/peardox/TrivialApp .

I got both 2d_dragon_spine_game and your TrivialApp running on my iPhone this way, without the need to edit Xcode project in any way except to set "development team" to sign the app.

I then retested both applications to do a more automatic build:

- Added `<ios team="..." />` to the `CastleEngineManifest.xml`

- Run `castle-engine package --target=iOS --package-format=ios-archive-app-store`

This allows to avoid the need to open the project in Xcode at all, it makes the resulting IPA file 100% automatically.

Hm, although I encountered an error -- IPA made by `castle-engine package --target=iOS --package-format=ios-archive-app-store` doesn't contain any device ids. Added to my TODO... but it seems unrelated to this issue, it is unrelated to the troubles you were experiencing.

As for images missing, this will be fixed once we migrate to "storyboards". But it seems Apple does not (yet) reject projects that didn't migrate to storyboards, so it's not a blocker (I plan to migrate to storyboards anyway, for "The Unholy Society" on iOS in January 2021).
