### ISSUE TITLE
Tiny doc error

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#234]
https://castle-engine.io/macosx_requirements.php#section_lcl

`On macOS, the default LCL widgetset is Carbon right now.`

How old is the documentation :)

**Comment by michaliskambi** [comment]
Actually I checked this recently (in November, when changing Android API level and rebuilding Docker image). I still had to switch to "cocoa" explicitly, default was "carbon".

I saw in Lazarus list they changed it in Lazarus trunk on 2020-07. There was a long time when the default in Lazarus was Carbon, despite Cocoa being necessary on modern macs.

I'll test with Lazarus 2.0.10. Possibly my recent test was using Lazarus 2.0.8.

**Comment by michaliskambi** [comment]
The documentation indeed is correct, with respect to the latest Lazarus stable version, 2.0.10. They still have default = carbon ( https://svn.freepascal.org/cgi-bin/viewvc.cgi/tags/lazarus_2_0_10/packager/packagesystem.pas?view=markup&root=lazarus ).

The change to default = cocoa is for now only in trunk, https://svn.freepascal.org/cgi-bin/viewvc.cgi/trunk/packager/packagesystem.pas?root=lazarus&r1=63551&r2=63550&pathrev=63551 .

I'll update the page to say so.

**Comment by peardox** [comment]
I always build from https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases

It's notable that Carbon comes before Cocoa in his release list owing to being alphabetic (he's also got an aarch64-cocoa)

It would be worthwhile advising the use of the cocoa build if using 10,15+ (99.9% likely to be true) as this is not obvious (I didn't know the first time I used it - had to look it up)

On a similar subject advise GTK2 for Linux as the preferred choice - I discovered I had one machine with a QT Linux build by accident - this resulted in some Discord discussion...

**Comment by michaliskambi** [comment]
> It would be worthwhile advising the use of the cocoa build if using 10,15+ (99.9% likely to be true) as this is not obvious (I didn't know the first time I used it - had to look it up)

The https://castle-engine.io/macosx_requirements.php#section_lcl clearly says """Only Cocoa supports 64-bit applications and latest macOS Catalina requires all applications to be 64-bit. So you just have to use Cocoa on new macOS. """

> On a similar subject advise GTK2 for Linux as the preferred choice - I discovered I had one machine with a QT Linux build by accident - this resulted in some Discord discussion...

GTK2 is already Lazarus default.
