### ISSUE TITLE
Weird iOS missing file error message in log

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#235]
https://github.com/peardox/TrivialApp (New and Improved - TForm moved). It's now got a huge model - 71Mb - which is (supposed to be) a test of TProgress. Note that gameinitialize.pas -> AppInitialization.pas...

Anyway - it all sort of works (apart from the TProgress) so I thought I'd test it out on iOS as it's run on all desktops.

I got the attached error log 
[ios.log](https://github.com/castle-engine/castle-engine/files/5648485/ios.log)
The odd but is at the bottom after...

`Sound: Consider using streaming when....`

The error message is not overly helpful...

```
2020-12-06 07:16:42.617209+0000 Basic Mobile App[3398:3455095] fopen failed for data file: errno = 2 (No such file or directory)
2020-12-06 07:16:42.617320+0000 Basic Mobile App[3398:3455095] Errors found! Invalidating cache...

```
That is supposed to be opening castle-data:/exebition_hall/scene.gltf which has a very large bin attached to it

I tried renaming the textures (in case jpeg ext was an issue) - nope, renamed caption in Manifest in case a space in filename issue again - nope.

At a loss as to what to try next as the error is rather uninformative.

Gonna try a Droid build...

[5 mins later] Droid worked perfectly - walk nav is cool when it eventually loads...

**Comment by peardox** [comment]
Altered the manifest owing to issues with no bundle being specified and magically iOS fails in an acceptable manner (Terminated due to memory issue)

I wondered about memory being a problem on mobile and it looks like that's the case here (stupidly large model) - it appears my iPadPro (1st gen - 2Gb RAM) don't like such a big test model.

**Comment by michaliskambi** [comment]
I don't see the large model anymore in https://github.com/peardox/TrivialApp . I just tested your TrivialApp and iOS and it opened fine, with a simple cube.

If you still have a testcase (large model that breaks on iOS) to reproduce, please reopen and submit a link here. While I cannot promise that any model will work on mobile (mobile devices just have limits), but maybe I can give some pointers in some cases, or at least tell you whether it may be improved in the future. And I could see whether memory usage of a particular model can be lowered. Depending on the model, maybe disabling collisions (do not include `ssDynamicCollisions` in `Scene.Spatial`) may help for memory usage. Or using smaller textures, or GPU-compressed textures ( https://castle-engine.io/creating_data_auto_generated_textures.php ).
