### ISSUE TITLE
Bad castle-data on MacOS using alternative_castle_window_based_on_lcl

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#236]
I just created a test version of https://github.com/peardox/TrivialApp - the BasicMac.lpi project that uses alternative_castle_window_based_on_lcl.lpk

This version is faster to the BasicLaz.lpi version which uses the full Lazarus component package (well, it loads the test scene faster).

However, it doesn't pick up castle-data correctly. If started from Finder it looks like it's looking in $HOME for data. There was an issue with the Mac .app version looking in the .app directory which you resolved by also looking in $CWD or something but it appear that fix was only applied to the castle_components version of things.

**Comment by michaliskambi** [comment]
That fix should be for both LCL (castle_components) and not. If we cannot find data within application bundle (`BundlePath + 'Contents/Resources/data/'`) then we will look at `data` that is sibling to application bundle (`BundlePath + '../data/'`).

Of course the latter is only for debugging (to actually distribute the app to users, you should copy datat inisde the bundle). As per https://castle-engine.io/macosx_requirements.php (see the bottom section).

Please show how your bundle (`xxx.app`) and show how your directory structure looks like. (Is `data` sibling to `xxx.app`?)

**Comment by peardox** [comment]
Ahh - that pointed me in the right direction...

This is an experimental hack to get things working without a form so I just copied the normal lpi and changed the package requirements. Examining the lpi I now notice this one had <UseAppBundle Value="False"/> so I changed it to True and everything worked again.

It's calling the form events - annoying, I'll just ifdef those out which should fix things

Trying to compile with castle-engine results in a linker error for X11 (which I'm not using)

**Comment by michaliskambi** [comment]
> Trying to compile with castle-engine results in a linker error for X11 (which I'm not using)

Compilation using build tool (when you didn't use `build_using_lazbuild` there) cannot use LCL units, so it cannot use "CastleWindow backend on top of LCL" (which is necessary to make CastleWindow with Cocoa). There's no solution here, for macOS (if you want to use CastleWindow + Cocoa) you must compile through Lazarus/lazbuild (or build tool with `build_using_lazbuild=true`).

The only fix from it will come once we have our own (non-LCL) CastleWindow backend using directly Cocoa. https://castle-engine.io/macosx_requirements.php#section_castle_window_cocoa
