### ISSUE TITLE
MacOS - alternative_castle_window_based_on_lcl - Debug stops without reason

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#237]
On closing an application as per screenshot below

To replicate issue ...

1) Create an 'empty' cge-editor project and transfer it to a Mac then use the Mac to...
2) Switch project to using alternative_castle_window_based_on_lcl instead of castle_window (as outlined in docs)
3) Clean + Run project
4) Close the application window
5) Weird Exception triggers

<img width="1440" alt="Screenshot 2020-12-07 at 21 46 26" src="https://user-images.githubusercontent.com/1549219/101410054-b1148180-38d6-11eb-9087-6aa1a9217eae.png">

**Comment by michaliskambi** [comment]
It's an access violation in LCL Cocoa unit.

Can you try reproducing it with a non-CGE application? Just drop TOpenGLControl on a form in a new Lazarus application. If we can make this is reproducible, then we can report it to Lazarus devs.

**Comment by peardox** [comment]
Hope - that worked fine

**Comment by michaliskambi** [comment]
Fixed :) There was already a related fix for similar crash at Carbon.

**Comment by peardox** [comment]
Cool - I'll go check it out on the Mac
