### ISSUE TITLE
Little documentation error

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#238]
https://github.com/castle-engine/castle-engine/wiki/2D-Games#full-featured-render-using-tcastlescene

> To have fixed resolution (regardless of the actual window size in pixels), set TCastleViewport.Camera.Orthoraphic.Width and/or TCastleViewport.Camera.Orthoraphic.Height. By default they are both zero (which means they follow window size), but if you set them then you explicitly specify the size. Set exactly one of them to non-zero to make the other one automatically adjusted to follow aspect ratio.

Orthoraphic -> Orthographic

**Comment by michaliskambi** [comment]
Fixed, thanks!
