### ISSUE TITLE
TGLImage documentation for "create"

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#24]
http://castle-engine.sourceforge.net/apidoc/html/CastleGLImages.TGLImage.html
TGLImage contains 4 variants of "create" however, their description seems to mismatch... Maybe I should try to fix the issue?

**Comment by michaliskambi** [comment]
In latest (from GitHub) version of the engine, it was even worse, as we have TGLImageCore and TGLImage, and their docs were a bit messed up...

My first answer was "go ahead", but I could not stand my own mess. So I did improve them a little myself:) The latest version is on http://michalis.ii.uni.wroc.pl/castle-engine-snapshots/docs/reference/html/CastleGLImages.TGLImageCore.html . Feel free to improve them more!
