### ISSUE TITLE
Display Source of Exception

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#240]
Another fairly trivial quality of life issue...

I just installed a clean Lazarus setup via FPCUpDeluxe on Windows to overcome some screwed up Lazarus components. Anyway, project is compiling fine under Lazarus so I decide to quickly check how it fares with build-tool

```
PS C:\dev\DAEVideo> castle-engine compile
Compiling project "DAEVideoApp" for OS / CPU "win64 / x86_64" in mode "release".
Exception "Exception":
Cannot find "windres" executable on $PATH. On Windows, it should be installed along with FPC (Free Pascal Compiler), so just make sure FPC is installed and available on $PATH. On Linux, "windres" is usually available as part of MinGW, so install the package named like "mingw*-binutils".

```

The message comes from castle-engine.exe but at no point is this obvious, in fact after fixing this (add an extra dir to path) there was an issue with the project via fpc (also fixed now)

My point here is that the Exception is un-informative. There is no way to tell from the text that this issue is coming from the build-tool.

It would be preferable is build-tool said that it had identified this problem, something along the lines of...

'While preparing \<project\> for compilation build-tool found the following issue with your FPC installation...'

**Comment by michaliskambi** [comment]
As you run the build tool, it is natural that all messages come from the build tool. So we don't repeat at each line that it is from build tool, and the project name (which is printed at the beginning of build tool output). With `castle-engine xxx --verbose` you can see the subcommands being run.

Also it should not really be relevant to you what is reporting this. For a newcomer to the engine, just running "compile" from the editor, it doesn't matter whether the `windres` is needed by the build tool, FPC, or some other tool used under the hood. What matters is that `windres` is missing, which the message already tries to explain how to fix.
