### ISSUE TITLE
Deprecation warnings in Android about Google Play Games services

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#250]
I just compiled

https://github.com/castle-engine/castle-engine/tree/master/examples/2d_dragon_spine_game

There are a load of deprecation warnings (Game Center esp) which is pretty bad for something pointed to as a getting started example

**Comment by michaliskambi** [comment]
Actually the deprecation warnings are *only* about Google Play services, not about anything else, last I checked.

We know about them, and they are exactly that: deprecation warnings. We'll work on them when time allows. In the meantime, the deprecated API continues to work just fine (and it will not disappear, as you declare the API version explicitly in Gradle).

**Comment by michaliskambi** [comment]
Work on this is started in https://github.com/castle-engine/castle-engine/tree/google-play-games-upgrade .

The code on that branch works 
- uses new Google Play Games API, not deprecated, 
- - successfully sign-ins to Google Play Games, 
- and can manage achievements.

It is not yet finished. The Java code misses some Google Play Games functionality: 
- leaderboards, 
- savegames.
(they will be ignored if requested from Pascal API `GameServices`.)

For now, finishing this seems not critical -- after some testing, the old Google Play Games API, while deprecated, still works perfectly. And Google doesn't have any hard deadlines on requiring the upgrade *right now*.

**Comment by michaliskambi** [comment]
Along with a few other Android upgrades, I want to finish the Google Play Games upgrade this week (~August 6th).

Various Android upgrades are made in master now, and the branch https://github.com/castle-engine/castle-engine/tree/google-play-games-upgrade has now working (and non-deprecated) code to handle achievements and leaderboards, and improved example in examples/mobile/game_services/ . Savegames and more testing will follow soon.

**Comment by michaliskambi** [comment]
Google Play Games usage, through our `google_play_games` Android service, was upgraded and it no longer uses any deprecated Java APIs.

New example: https://github.com/castle-engine/castle-engine/tree/master/examples/mobile/game_services . This is in the process of being published on Google Play so people can also actually play it on their phones.

Docs: https://github.com/castle-engine/castle-engine/blob/master/tools/build-tool/data/android/integrated-services/google_play_games/README.adoc . Many other Android docs have been updated.

More in the news this weekend :)
