### ISSUE TITLE
Origin not centered using an IsoMetric viewport

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#261]
It's the lastest version of sample project : https://github.com/peardox/IsometricTest - needs graphic assets adding (instructions in the README.md)

![origin](https://user-images.githubusercontent.com/1549219/109960791-1d89fb80-7ce1-11eb-8064-5f7f721049aa.png)

pngcrunch should fix the CRC issues in the originals

Basically I wanted to have an extra viewport that renders 3D content over a 2D viewport so the project now has 3 viewports, all except the rear-most being transarent...

Backport (background - just a JPG for now)
Viewport (2D for Isometric tiles)
Birdport (3D - was gonna put a parrot here, changed to a cross as it's very simple to debug the object - it's 0,0,0 origin and -23 to + 23 in X, Y and Z)

You advised setting the camera to look in -1,-1,-1 in an orthogonal viewport so I set that up very simply in lines 163-188 of MainGameUnit.pas - I've hooked Resize as well but commented it out (tried all sorts of things)

Using the advised setting of 0.5, 0.5 for the origin to screen center it places the origin in the top RH side for Birdport. Experimentation shows that 0.25, 0.25 is close to center on startup

When you run it make sure you resize the window - that is really odd, Viewport (2d) remains entered while Birdport does odd things depending on the origin setting used.

You know, we could really do with some more boiler-plate SetupXXX methods - e,g, SetupIsometric (and there are many others of course). Manually working out the interaction is a time-consuming process for the uninitiated (me)

Oh - why is the camera set to (0, 0, 500) in Setup2D? It's the Z I'm wondering about, There's still a FOV in orthohonol ain't there. To my thinking the center needs to be based on the width + height of the viewport for the Z in use. I did some experimentation a few months back in this respect to allow me to chose the FOV so rotating in the Y axis minimised the total X/Y area used (3D looking straight on from 0,0)

**Comment by Kagamma** [comment]
The camera was set to (0,0,500) due to an old bug, see https://sourceforge.net/p/castle-engine/discussion/general/thread/b66c948e/
This setup (Z = 500) is not important if you don't rely on TouchSensor in 2D mode.

**Comment by michaliskambi** [comment]
The camera at (0,0,500) is not a result of a bug -- we need camera to be at some Z, as orthogonal projection has projection near/far clipping planes, and we cast rays to determine "picked" things (not only by X3D touch sensor, also e.g. `Viewport.MouseRayHit` or `Viewport.TransformUnderMouse`) from this Z. The way it works is documented on https://castle-engine.io/apidoc-unstable/html/CastleViewport.TCastleViewport.html#Setup2D .

In case of orthographic projection, the "field of view" is determined by `Viewport.Camera.Orthographic.Width` / `Height` ( https://castle-engine.io/apidoc-unstable/html/CastleCameras.TCastleOrthographic.html#Width ).

This is just FYI, I didn't yet test the testcase. I only say that I do not suspect (yet) the camera Z to be a problem here. It is more likely that `Camera.Origin` was not implemented with this case in mind, and it does something weird, and maybe I can fix it :)

**Comment by peardox** [comment]
In the testcase if you use the mousewheel it zooms the 3D object in the 2D world (using current Navigation)

As mouse wheel alters the camera's Z if what you say is true the 3D model should not zoom???

**Comment by michaliskambi** [comment]
> As mouse wheel alters the camera's Z if what you say is true the 3D model should not zoom???

Altering the camera Z in orthographic projection would make no zoom effect, indeed. That is why mouse wheel (zoom) in orthographic projection **does not** change camera Z, it is handled specially:

```pascal
function TCastleExamineNavigation.Zoom(const Factor: Single): boolean;

  function OrthographicProjection: Boolean;
  begin
    { See how perspective (and more flexible frustum) projection matrices
      look like in CastleProjection, they have always -1 in this field. }
    Result := Camera.ProjectionMatrix.Data[2, 3] = 0;
  end;

var
  Size: Single;
  OldTranslation, OldPosition: TVector3;
  B: TBox3D;
begin
  ...
    if OrthographicProjection then
    begin
      { In case of OrthographicProjection, changing Translation
        would have no effect. So instead scale the projection size. }
      Camera.Orthographic.Scale := Camera.Orthographic.Scale * Exp(-Factor);
    end else
    begin
      ...
      Translation := Translation + Vector3(0, 0, ...);
    end;
  ...
end;

**Comment by peardox** [comment]
Fixed it

Turns out the ordering of the viewport setup methods is somewhat critical

**Comment by michaliskambi** [comment]
@peardox Cool.

Can you elaborate on what was the problem / what was the exact fix? I'm curious for the future (whether we may improve something in the engine or in docs at least). I see your commits https://github.com/peardox/IsometricTest/commit/6f7366938383fe609212670fd08a12d39b0e66f5 https://github.com/peardox/IsometricTest/commit/4a2bd2d0dd58f98ba453a0f4e6557c4c8aee274e , in particular the former one changes `TCastleApp.LoadViewport` order. But it is curious why it helped. 

The `TCastleViewport.Setup2D` indeed changes some other properties of viewport / camera. It is one reason why I don't like such "shortcut methods that change a bunch of other properties", you need to be aware what properties are changed. In this case,

```pascal
procedure TCastleViewport.Setup2D;
begin
  Camera.Init(
    { pos } Vector3(0, 0, Default2DCameraZ),
    { dir } Vector3(0, 0, -1),
    { up } Vector3(0, 1, 0),
    { gravity up } Vector3(0, 1, 0)
  ); // sets both initial and current vectors
  Camera.ProjectionNear := -Default2DProjectionFar;
  Camera.ProjectionFar := Default2DProjectionFar;
  Camera.ProjectionType := ptOrthographic;
  AutoCamera := false;
end;
```

So yes, the moment you call `Setup2D` matters. It overrides the camera position/direction etc.

**Comment by peardox** [comment]
I was just playing with the test case (I've changed it + simplified it) to demo the 'fix'

Now it's broken worse than ever :(

All graphical dependencies have been removed - it's all self-contained now at https://github.com/peardox/IsometricTest

The issue is setting Camera.Direction

You said that isometric was simply a case of setting the camera direction to -1, -1, -1 (which is how all this started)

The test case has buttons that allow you to set the camera in 7 configurations - press the buttons, a random order makes it go wrong fairly quick - then click 0, 0, -1 to set it back to default 2D (will you actually get default 2D? Its a case of Russian roulette...)

**Comment by peardox** [comment]
Worked out why irs not working as I thought it would

Changing any of Direction, Position + Up changes the others (they're normalized)

**Comment by michaliskambi** [comment]
> Changing any of Direction, Position + Up changes the others (they're normalized)

Changing Position is not related.

Changing Direction and Up: yes, they are normalized upon setting. They are also forced to be orthogonal. This is deliberate and documented at `TCastleTransform.SetView` and `TCastleTransform.UpPrefer` , https://castle-engine.io/apidoc-unstable/html/CastleTransform.TCastleTransform.html#SetView .
