### ISSUE TITLE
Bad docs link

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#263]
On https://github.com/castle-engine/castle-engine/wiki/Sprite-sheets

It says ...

See CGE manual about loading and playing scenes and animations: loading, displaying a scene, transform, animate etc. a scene.

The 'loading, displaying a scene' link goes to - https://castle-engine.io/manual_load_3d.php (note it's 3D)

Shouldn't it link to a 2D setup page (I know there's one somewhere - never can find anything in the Manual...)

**Comment by michaliskambi** [comment]
It's a valid link. It says "3D" but it is really about "loading to TCastleScene" and all there applies to 3D as well.

**Comment by michaliskambi** [comment]
I mean, that manual page can be improved -- and talk about editor too. But it should apply to both 3D and 2D.
