### ISSUE TITLE
StopAnimation not stopping animation

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#273]
As per Discord StopAnimation isn't, also as per Discord - bare bones testcase

Testcase repo : https://github.com/peardox/TestCase

Line 72 - maingameunit.pas - SwitchAnimation

Compiles with build tool for max Michalis friendliness :)

**Comment by peardox** [comment]
Found that this works

```
  frame := Scene.AnimationDuration(Scene.AnimationsList[AIndex]) / 2;
  Scene.ForceAnimationPose(Scene.AnimationsList[AIndex], frame, false, true);
```

And it also appears more suited to the task at hand (3D model -> 2D Sprite)

**Comment by michaliskambi** [comment]
Fixed!

Sorry for delay. I'm finally getting back to my feet after COVID.

**Comment by peardox** [comment]
Thanks

Nice to have you back
