### ISSUE TITLE
Allows light sources in scenes other than MainScene affect other scenes

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#280]
As discuss in discord, this feature will allow us to manipulate light sources directly in editor. It is also friendlier IMO, because we work with scenes most of time.

**Comment by michaliskambi** [comment]
This is in-progress this week. 

- New 4 components to define light nodes: TCastlePointLight, TCastleSpotLight, TCastleDirectionalLight, TCastleEnvironmentLight. All "wrapping" X3D light nodes underneath, and exposing lights as something you can easily manipulate from editor and from code too.

- New properties to control lights: RenderOptions.ReceiveSceneLights, RenderOptions.ReceiveGlobalLights, Scene.CastGlobalLights . Any scene can set `Scene.CastGlobalLights`, this ability is no longer special to `MainScene`.

![Zrzut ekranu z 2022-02-09 13-03-15](https://user-images.githubusercontent.com/1076978/153199039-525cbc4c-c16d-440b-a057-f3b844820fdb.png)
![Zrzut ekranu z 2022-02-09 13-02-42](https://user-images.githubusercontent.com/1076978/153199045-0a8c726e-1ea4-4195-aad0-53747a4e62c6.png)

**Comment by michaliskambi** [comment]
Merged to CGE master. Every scene has now `CastGlobalLights` boolean property. I will write more about the new things in a news post this weekend.
