### ISSUE TITLE
CGE does not optimize scenes outside of MainScene light's radius

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#281]
Nvidia Nsight shows me the engine still pass light uniforms to shader even though the light itself is far away from the scene. So I assume the engine doesn't optimize lights based on distance?

**Comment by michaliskambi** [comment]
We do optimize that. We spend some time to gather at each shape the "lights potentially affecting it", and if the light radius doesn't reach the shape's bounding box that the light should not be considered "affecting the shape". Later (in `TGLRenderer.RenderShapeLights`) we only take care of the relevant lights (for both shader and ancient fixed-function pipeline).

Can you submit a testcase? Then I can investigate and/or explain why the detection failed and maybe improve it :)

**Comment by michaliskambi** [comment]
Reading carefully your title I actually know what is wrong :) In `TGLRenderer.RenderShapeLights` we always pass all `BaseLights` to the shape. In case of non-MainScene rendering, the `BaseLights` will contain all the global lights from MainScene, disregarding the fact that some lights may be too distant.

Will be fixed, thank you!

**Comment by michaliskambi** [comment]
This is properly optimized now in `light-components` branch. I'll close this report when it's merged to `master`.

**Comment by michaliskambi** [comment]
The fix, along with a bunch of other improvements to lights, is now merged to CGE master.

**Comment by Kagamma** [comment]
Thanks will try it soon :)
