### ISSUE TITLE
FileNameAutoInc

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#289]
Not sure how to title this one as this could actually be a FPC problem, it's probably little used anyway (but still a concern)

https://castle-engine.io/apidoc-unstable/html/CastleFilesUtils.html#FileNameAutoInc states that passing a parameter of  'screenshot_%04d.png' will create a padded filename with four digits, this is not true (and confusing as you use the without zero variant just before)

In C etc this format does produce a LFZ pad, in FPC it doesn't. Both width and precision specifiers appear to be required.

For example FileNameAutoInc('castle-data:/grab_%4.4d.png') produces the expected result.

Note that this seems to be FPC being non-standard / bugged (docs say it will work in the expected manner)

The CGE documentation could do with a correct example - using a CGE-specific path also seems beneficial

[Addendum]

This function would be improved with an optional variant with a base number to start a sequence from so you could have a one-based numbering system (more end-user friendly)

**Comment by michaliskambi** [comment]
Thanks -- I fixed the documentation, should be `screenshot_%.04d.png` (add dot right after the percent sign).

FPC and FPC docs are correct here, it was just my mistake. The existing behavior is documented on https://www.freepascal.org/docs-html/rtl/sysutils/format.html precisely.

Note that you shall never save anything to `castle-data:/`, this may be a read-only directory on various platforms (it is for 100% read-only on Android). So do not use `FileNameAutoInc('castle-data:/.....')` to store anything, if you want to work cross-platform. Save to `ApplicationConfig` or `SaveScreenPath` or even better save using `Window.Container.SaveScreenToDefaultFile` to have the best chance that it will work cross-platform. While `Window.Container.SaveScreenToDefaultFile` doesn't work 100% cross-platform *yet*, but it could in the future, e.g. on iOS it could save images to your camera roll. 

I mentioned this in doc too.
