### ISSUE TITLE
AllowStretch for Orthographic

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#290]
From Discord...

> TCastleOrthographic.AllowStretch = true (new possibility): TCastleOrthographic.Width and TCastleOrthographic.Height are taken literally. So e.g. using
> 
> Viewport.Camera.ProjectionType := prOrthographic;
> Viewport.Camera.Orthographic.AllowStretch := true;
> Viewport.Camera.Orthographic.Width := 200;
> Viewport.Camera.Orthographic.Height := 100;
> Viewport.Width := 1000;
> Viewport.Height := 1000;
> 
> 
> ... would mean that your effective rendering squeezes Y 2x (because Viewport.Camera.Orthographic.Width / Viewport.Camera.Orthographic.Height = 2, but Viewport.Width / Viewport.Height = 1).
> 

This will theoretically allow faking Oblique projection (Military as in Ultima 7, possibly original SimCity)

**Comment by peardox** [comment]
I've now proved that scaling by 0.81625 in X using a (1, -2, 1) viewpoint gives a Military projection

Could you either add this as specific mode or tell me where I can hook to implement it myself.

**Comment by michaliskambi** [comment]
I implemented `TCastleOrthographic.Stretch` :) It can be tested in CGE editor too, `Stretch` is published.

So the way for you is to 

- Set Camera.Orthographic.Stretch = true.

- From code, set both `Camera.Orthographic.Width` and `Camera.Orthographic.Height` to apply your desired multiplier (but otherwise reflect the current control width and height).

To be safe (if you have resizeable window) you should override state `ContainerResize` to set viewport size each time container size possibly changed:

```pascal
procedure TMyState.ContainerResize(const AContainerWidth, AContainerHeight: Cardinal);
const
  Multiplier = 0.8;
begin
  inherited;
  { Update orthographic projection size, to reflect MyViewport size with some multiplier. }
  MyViewport.Camera.Orthographic.Width := MyViewport.EffectiveWidth * Multiplier;
  MyViewport.Camera.Orthographic.Height := MyViewport.EffectiveHeight;
end;
```

**Comment by peardox** [comment]
Thanks a million for this @michaliskambi 

My 3D to 2D converter project (I'm getting nagged about the release date) will now support conversion to all the commonly used 2D views of a Sprite...

Flat, Side-On, Top Down (typical scrollers etc)
2:1 Pixel Aspect Ratio (Nicer lookign scrollers)
Isometric (Diablo-esqe)
Military (Ultima 7 Style)
Other (choose your own VP)

Cabinet is also used - I'll have to look into that one but the all important Military view should now work (I'm about to test it)
Military is important 'cos one of the most prolific artists I'm aware of uses it exclusively (PV Games)
