### ISSUE TITLE
TViewport.PositionToSomething(...) can return nonsense results

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#295]
From Discord...

Calling PositionToSomething(...) is supposed to return a boolean False if the result is bad but calling it shortly after setting the viewport has been created results in nonsensical results (e,g, TVector3(0, 0, Depth - 10) while also saying the function suceeded.

**Comment by michaliskambi** [comment]
Confirmed, fixed, tested.

Interactive reproduction on https://gist.github.com/michaliskambi/2b8faee73df9f3a12351736cabcad1ee . Run and press "s". Output before fix (so result from early calls is different than result from `Press`):

```
Testing on : 100.00 100.00
  PositionToRay test: 0.00 0.00 0.00 0.00 0.00 -1.00
  PositionToCameraPlane test: 0.00 0.00 -2.00
  PositionToWorldPlane test: 0.00 0.00 -10.00
  PositionTo2DWorld test: : 0.00 0.00
Testing on : 150.00 150.00
  PositionToRay test: 0.00 0.00 0.00 0.00 0.00 -1.00
  PositionToCameraPlane test: 0.00 0.00 -2.00
  PositionToWorldPlane test: 0.00 0.00 -10.00
  PositionTo2DWorld test: : 0.00 0.00
Testing on : 100.00 100.00
  PositionToRay test: 0.00 0.00 0.00 -0.13 -0.13 -0.98
  PositionToCameraPlane test: -0.27 -0.27 -2.00
  PositionToWorldPlane test: -1.37 -1.37 -10.00
  PositionTo2DWorld test: : 100.00 100.00
Testing on : 150.00 150.00
  PositionToRay test: 0.00 0.00 0.00 0.00 0.00 -1.00
  PositionToCameraPlane test: 0.00 0.00 -2.00
  PositionToWorldPlane test: 0.01 0.01 -10.00
  PositionTo2DWorld test: : 150.00 150.00
```

Output after fix (result from early calls is equal to the result from `Press`):

```
Testing on : 100.00 100.00
  PositionToRay test: 0.00 0.00 0.00 -0.13 -0.13 -0.98
  PositionToCameraPlane test: -0.27 -0.27 -2.00
  PositionToWorldPlane test: -1.37 -1.37 -10.00
  PositionTo2DWorld test: : 100.00 100.00
Testing on : 150.00 150.00
  PositionToRay test: 0.00 0.00 0.00 0.00 0.00 -1.00
  PositionToCameraPlane test: 0.00 0.00 -2.00
  PositionToWorldPlane test: 0.01 0.01 -10.00
  PositionTo2DWorld test: : 150.00 150.00
Testing on : 100.00 100.00
  PositionToRay test: 0.00 0.00 0.00 -0.13 -0.13 -0.98
  PositionToCameraPlane test: -0.27 -0.27 -2.00
  PositionToWorldPlane test: -1.37 -1.37 -10.00
  PositionTo2DWorld test: : 100.00 100.00
Testing on : 150.00 150.00
  PositionToRay test: 0.00 0.00 0.00 0.00 0.00 -1.00
  PositionToCameraPlane test: 0.00 0.00 -2.00
  PositionToWorldPlane test: 0.01 0.01 -10.00
  PositionTo2DWorld test: : 150.00 150.00
```

Fixed.

Non-interactive reproduction added to test suite, `TTestWindow.TestViewportPositionTo`.

**Comment by michaliskambi** [comment]
Note:

The TCastleViewport.PositionToXxx family was fixed, to return correct values even when used early (before a rendering happens)

Note that it doesn't mean that they'll return `false` (in case of `PositionToCameraPlane`, `PositionToWorldPlane`). They return `false` only if the ray doesn't hit the indicated plane (which may easily happen with `PositionToWorldPlane`, if the camera looks in another direction; it is almost impossible to get with `PositionToCameraPlane`, as you'd need a field of view > 180deg, which is for now not allowed anyway at it would cause other troubles).
