### ISSUE TITLE
Bad path for shared file in 3d_rendering_processing/show_bounding_rect_in_2d.lpr

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#296]
PLaying with TLineSetNode and finding one in 3d_rendering_processing/show_bounding_rect_in_2d.lpr...

Line 107...
`  Scene.Load('../2d_dragon_spine_game/data/dragon/dragon.json');
`

File no longer exists owing to repo re-ordering

Suitable alternative...

  Scene.Load('../component_gallery/data/dragon/dragon.json');

I've grepped out examples and find no other references to 2d_dragon_spine_game

**Comment by michaliskambi** [comment]
Thanks for checking, I applied the suggested fix.

Note that I'm in the middle of rearranging the `examples/` subdirectory (and the old `examples/3d_rendering_processing/` is definitely a subject to some rearrangements). So more breakage will happen soon :) In new demos, I usually place their own data in `data/`, without referencing any parent, even when it means duplicating some files in CGE examples.
