### ISSUE TITLE
Joystick problem in Windows

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#30]
Eventually I've bought a cheap gamepad for myself :)
After a few minor fixes (see https://github.com/eugeneloza/castle-engine/commit/adb4ec3832ae8c1845f513279fe41e3f6a7c490d ) I've managed to make my gamepad work on Linux smoothly.
But It works not as expected on Windows.
I couldn't solve the puzzle of Up/Down/Pressed state, the implementation is much more complex in Windows and therefore I don't really understand where it fails...
I've managed fix onAxisMove event spamming, but POV axes don't trigger onAxisMove events, moreover they provide incorrect data for my gamepad (UP=UP, LEFT=UP, RIGHT=RIGHT, DOWN=DOWNLEFT) while everything is correct in Linux and in native gamepad test software.
@tsr8  I believe you are much more experienced in gamepads than me... if you could give me a hand here I'd be very grateful.

@michaliskambi  Is it possible to implement "TCastleWindow.gamepadlook" similar to "TCastleWindow.mouselook"? Where should I start digging? It's a theoretical question for now as I'm buisy with my game interface at the moment, so don't take it too seriously, just a hint or reference to the procedure will be absolutely enough for me to understand whether I am capable of doing that... :)
Maybe it's a good idea to make gamepad events linked to TCastleWindow.OnMotion? E.g. integrate it in `TInputPressReleaseType = (itKey, itMouseButton, itMouseWheel, itJoystickAxis, itJoystickButton);` I see that TCameraInputListener and TUIContainer already have some joystick support.

P.S. When I make changes to castlejoysticks.pas it doesn't compile together with my program and I have to compile castle_base manually. Strange, because castleimages works like a charm here even while editing "inc" files. Maybe, there's something wrong with package settings for castlejoysticks.pas unit so its change doesn't call to re-compile the castle_base automatically?
It's not listed in castle_base.lpk but is used in CastleUIControls.

**Comment by michaliskambi** [comment]
> Is it possible to implement "TCastleWindow.gamepadlook" similar to "TCastleWindow.mouselook"? Where should I start digging?

As for MouseLook: it is mostly passed to the TWalkCamera. It is probably not the best "role model" of implementation, as it spans a couple of features:

1. cursor must be hidden
2. cursor must be "confined" to window, by keeping it at center
3. and, finally, camera reacts correctly to mouse look.

I would prefer to "localize" the MouseLook handling more, but it's just not possible, as 2. and 3. must work together (3. depends on 2. being done OK).

> Make gamepad events linked to TCastleWindow.OnMotion?

I'm not sure about the OnMotion. It contains positions, which are specific to something like mouse / touch.

But I would like to unify pressed and releases with current OnPress / OnRelease events (and Press / Release virtual methods), in a structure TInputPressRelease . The TInputPressReleaseType may be extended with joystick enum. This would be a little better than current separate method JoyButtonPress, as you could process all these inputs at once. This allows to do things like TInputShortcut, that represent a user-configurable shortcut, which can be now set any mouse button, key, or mouse wheel move. "The Castle" https://github.com/castle-engine/castle-game uses this to present a nice menu "configure game controls" to user.

It would be cool to have joystick presses assignable there too. So user could configure any game action to any joystick press.

> It's not listed in castle_base.lpk but is used in CastleUIControls.

Exactly, it should be added to castle_base.lpk then:)

**Comment by michaliskambi** [comment]
> Exactly, it should be added to castle_base.lpk then:)

Done:)

**Comment by michaliskambi** [comment]
And some documentation about our input system is here: http://michalis.ii.uni.wroc.pl/cge-www-preview/tutorial_key_mouse.php . This tutorial (soon to be renamed "manual":) chapter is not best, there are no examples. The code of https://github.com/castle-engine/castle-game hopefully provides a good (and complicated...) example for now.

**Comment by tsr8** [comment]
> @tsr8 I believe you are much more experienced in gamepads than me... if you could give me a hand here I'd be very grateful.
On Windows system implementation have been used old multimedia library _winmm.dll_. It is compatible but very basic.
As described in _castlejoysticks.pas_ file:
`//todo: only partially works on Windows (no support of new features); need to be ported to xinput library`
I don't use Windows at all so it will be to hard for me to implement this in short future.

**Comment by eugeneloza** [comment]
I'll also try to handle this one myself. Moving to my repository branch.
