### ISSUE TITLE
Upside down TileMaps

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#300]
I just noticed that the TextureAtlas images the Sprite Editor produces are non-standard in that sprite 0 is at the lower left of the compsite image whereas the images produced by everything else has tile 0 at the upper left.

While this is not a real concern if consistent it does limit the facilities offfered by the Sprite Editor especially when using external artwork and external starling xml files

The most noticable issue is that if an animation result in a partial row of frames this row will be at the top of the TextureAltas image (this is why I spotted it - creating 64 209x256 frames for an animation left the top line with only one frame...)

If the resultant TextureAtlas is used by any non-CGE engine the ordering of the frames will result in unexpected frame order from 'other engine' (Which will make peple say we're wrong ...)

It seems sensible to follow convention and have the Texture Atlas use the expected upper-right origin especially as translation to this ordering is trivial.

This may also affect TileMaps?

**Comment by michaliskambi** [comment]
The coordinates of the frames are written in `.castle-sprite-sheet` file explicitly, and the way they are written follows Starling XML conventions. So I don't see the problem. We can open this file, and if you change it into Starling XML by changing extension (which you can do now, as `.castle-sprite-sheet` is for now almost the same as Starling XML, we only made 1 small addition) then other applications will be able to open it too.

So all software should work.

The humans that looks at atlas file may be surprised, but this is easy to explain. We follow a different convention, but it is consistent with CGE convention that "Y = 0 is bottom, Y grows up" (which follows mathematical convention, which indeed is reverse from what various GUI libraries do; but it is a good thing in a 3D / 2D game engine, as such definition of Y makes sense for both 3D and 2D).

There's no relation to TileMaps (I assume you mean "Tiled" maps) here, as far as I see. We open atlases, in any format, correctly -- always accounting for the way Y goes.
