### ISSUE TITLE
Confusing documentation for BoundingSphere

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#301]
https://castle-engine.io/apidoc-unstable/html/CastleBoxes.TBox3D.html#BoundingSphere

It is not made clear theat the returned radius is the radius squared

After a lot of unexpected results I just twigged that to be of any use to me I need to take the sqrt of the returned value

I realise that the square is valid for other uses (comparisons etc) but with a method named BoundingSphere it is natural to (wrongly) presume that you get the radius.

**Comment by michaliskambi** [comment]
Improved the docs, thanks!

BTW If I would create this method today, I would likely not make this complication. I was avoiding like crazy the usage of `Sqrt` in the engine long long time ago.. and it caused some additional work (you need to square the other side of the equation) for little-to-no-gain. At the very least, I would call this `BoundingSphereSqr`.

Anyway, for now I decided to not break compatibiilty and just document it clearly.
