### ISSUE TITLE
Changing texture co-ordinates dynamically not updating model

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#303]
I've got this...

```
procedure TCastleStage.ChangeTextureCoordinates(const Model3D: TX3DRootNode; const AScale: Single = 1.0);
var
  TextureCoordinateNode: TTextureCoordinateNode;
  NewCoords: array[0..3] of TVector2;
begin
  // Find the texture
  TextureCoordinateNode := Model3D.TryFindNodeByName(TTextureCoordinateNode, 'ObjFrontTextureCoordinates', false) as TTextureCoordinateNode;
  if not (TextureCoordinateNode = nil) then
    begin
      // Set new texture coordinates
      NewCoords[0] := Vector2(AScale, 0);
      NewCoords[1] := Vector2(AScale, AScale);
      NewCoords[2] := Vector2(0, AScale);
      NewCoords[3] := Vector2(0, 0);

      TextureCoordinateNode.SetPoint(NewCoords);
    end
  else
    WriteLnLog('Failed to change ground texture scale to ' + FloatToStr(AScale));
end;
```

The procedure is intended to allow the user to dynamically scale a texture, the ground in my case, which is a useful technique for my converter application.

The code does actually work but not in real time. I've got another procedure that changes the texture url of the model (it's a very simple plane) without changing the model geometry. This works  as intended.

To get the texture co-ordinates to visibly update I have to call the above procedure then call the change texture url procedure (using its current value works) in order for the desired texture co-ordinates to be applied - obviously I don't want to pointlessly change anything I don't have to like the Uri in this case.

Fairly obviously my use is an edge-case, game devs are hardly going to want to change texture cordinates (maybe as an effect - but that's stretching things)

Nevertheless I would class this as a bug as the implied outcome of changing texture co-ordinates is that the model visibly change. While some invalidation or whatever prob fixes the situation this is not what SetPoint should do IMHO in this situation (it's an undocumented procedure from the results shown when searching API)

Addendum...

I just noticed that changing the texture co-ordinates to all zeros doesn't raise any exceptions etc - UV mapping (0, 0) - (0, 0) is defintitely not a correct value

**Comment by michaliskambi** [comment]
Thanks -- indeed it is a bug, I mean calling `TextureCoordinateNode.SetPoint` *should* automatically make the change visible, without doing anything extra to provoke internal "invalidate" to make it visible. I'm sure we had it working at some point, so it's possible I just broke it with some optimization :)

> I just noticed that changing the texture co-ordinates to all zeros doesn't raise any exceptions etc - UV mapping (0, 0) - (0, 0) is defintitely not a correct value

Any UV value is correct, including this. You can specify any texture area, even such weird one. GPU allows it, X3D allows it, glTF allows it. And we try to *not* analyze the contents of per-vertex data (like texture coordinates) at all in CGE, when possible, for speed.

**Comment by peardox** [comment]
Think I'll still throw out empty coords mysef tho :)

**Comment by michaliskambi** [comment]
I investigated it but so far I failed to reproduce the problem. 

Here's my attempt at reproduction: https://gist.github.com/michaliskambi/0b2d035a7b7a47739c016ed5152e23f7 . It's just example code from https://castle-engine.io/x3d_implementation_geometry3d.php#section_example_pascal_rect , calling `TTextureCoordinateNode.SetPoint` just like you show in the bugreport description. Each time you press "s" it changes texture coords. (If testing it yourself, be sure to adjust texture URL/filename at ` Scene.Load(BuildRootNode('/home/michalis/....` call.)

And it works -- `TTextureCoordinateNode.SetPoint` changes texture coordinates, without the need to do anything else.

Please provide a reproducible testcase, how does this fail for you. Feel welcome to start from my testcase. Maybe you start from some specific x3d/glTF model with some specific setup that causes this? Maybe you initialize the TCastleScene in some special way?

**Comment by peardox** [comment]
I'm doing something similar, the most notable differences are that I load from an extremely simple X3DV and I've got  a TTransformNode in between so I can move the thing around (it's a simple ground plane and I wanna be able to change it's height on demand)

I'll see if I can break yur gist / find out is I've done anything bad...

**Comment by peardox** [comment]
Well, that was extremely annoying. I just spent well over an hour trying to break the example. Perhaps it's LCL I thought so messed theere as well trying the call in a Press event (which worked). Finally I removed the bodge I had to make LCL work and ... it worked OK there too - it didn't when I posted this issue!

Something you've changed elsewhere since I reported this has actually fixed this one.
