### ISSUE TITLE
Improper usage of FBO on mac OpenGL

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#305]
// As per discord https://discord.com/channels/389676745957310465/389676745957310467/854297290695901214

Investigating crash scenarios with my Spritely project on the Mac I narrowed things down to the issue being with the use of Directional Lights / Shadow Maps (project works without lights). Further investigating I decided to open a sample demo scene from the shadow_map folder, namely simple_shadow_map_teapots.x3dv, to further eliminate potential causes.

This was the result...

<img width="1680" alt="Screenshot 2021-06-15 at 09 46 15" src="https://user-images.githubusercontent.com/1549219/122035657-9877ad80-cdca-11eb-9bb3-f48e5fcb3599.png">

You observed that the info display panel is badly sized considering this to also be a potential problem - this appears not the case though as dismissing the error message in the above screenshot resulted in a frame update that resolved the sizing.

You requested I obtain the machine's GL Information from the Help menu. This caused yet another error dialog as shown below.

<img width="1680" alt="Screenshot 2021-06-15 at 11 16 45" src="https://user-images.githubusercontent.com/1549219/122036272-4aaf7500-cdcb-11eb-85a4-65e9eb545967.png">

After dismissing that error message I re-tried the Help -> OpenGL Information and sucessfully got it (although repeating the process results in the same error - success loop)

Here's the GLInfo

[glinfo.txt](https://github.com/castle-engine/castle-engine/files/6654815/glinfo.txt)

**Comment by peardox** [comment]
I just added a TSpotLightNode to my project and it worked as expected

I then modified my directional light to not use shadows and it worked as expected

I finally just enabled the undocumented TDirectionalList.Shadows and it crashed as before.

This indicates that the Mac issue may be with ShadowMaps

**Comment by peardox** [comment]
Oops - bad bug-diagnosis and assumptions on my part

I then kicked myself in the ass for not checking shadow maps, and so re-enabled them without the TDirectionalList.Shadows unset and it worked

I created a shadow map but didn't use it so it appears that the use of shadows is the problem

**Comment by michaliskambi** [comment]
Thanks for testing. Your conclusions are mostly as expected, as shadow maps require using the FBO that error message is speaking about. 

> I just added a TSpotLightNode to my project and it worked as expected

As a one final test, I'd suggest to try TSpotLightNode with shadow maps (using simple `Shadows` field) enabled. I bet it will fail just the same when you activate shadow maps.

> the undocumented TDirectionalList.Shadows 

It's the `shadows` field on light X3D node, https://castle-engine.io/x3d_extensions_shadow_maps.php#section_light_shadows_on_everything . Better docs for X3D nodes and fields are coming (I have some pieces in tools/internal/x3d-nodes-to-pascal/nodes-specification), but also soon we'll have new way to design lights (and shadows) in editor so it will have new docs:)

**Comment by peardox** [comment]
> As a one final test, I'd suggest to try TSpotLightNode with shadow maps (using simple Shadows field) enabled. I bet it will fail just the same when you activate shadow maps.

The one light I don't want to cast a shadow (it highlights the subject model) - yep, that also kills it

> soon we'll have new way to design lights (and shadows) in editor

The editor that don't work with TCastleWindowBase :)

I'll get around to converting my project to use no LCL later on but for now LCL is the only way to get a UI for it...

**Comment by michaliskambi** [comment]
> The editor that don't work with TCastleWindowBase :)
> I'll get around to converting my project to use no LCL later on but for now LCL is the only way to get a UI for it...

Not sure what do you mean. The editor creates designs -- that you can load in `TCastleWindowBase` (as all templates and many examples show) or to `TCastleControlBase` (as e.g. `examples/lazarus/model_3d_with_2d_controls/` does). Anyway, this is getting off-topic from this bugreport.

**Comment by michaliskambi** [comment]
Sorry for such delay in dealing with this!

1. Recently, I retested with latest `master` branch (before the merge of `shadow-volumes-new` that did a lot of upgrades to our OpenGL code), and I could no longer reproduce the issue. That is, `simple_shadow_map_teapots.x3dv` rendering, with shadow maps, works without any errors reported. This is using latest view3dscene from master, with latest CGE from master.

   Tested on macOS 12.4, on Intel-based mac, with a probably non-standard GPU inside a machine provided by MacStadium hosting ("Intel UHD Graphics 630 1536 MB").

2. Later, I finished a big refactor of our rendering code (in `shadow-volumes-new`, with lots more work on `master`). This changes quite a lot in our support, for the better:

    - We now access "core" OpenGL context on macOS (which allows to get latest OpenGL, not stuck with 2.1). See https://github.com/castle-engine/castle-engine/issues/409 .

    - We now use FBO from OpenGL "core" 3.0 (previously, macOS was using it through GL_ARB_framebuffer_object extension).

    Even simple_shadow_map_teapots.x3dv changed (we no longer support compareMode="NONE" in X3D, which was a debugging hack that was hard to maintain; in exchange, shadow maps work now smoothly on OpenGLES).

Soo... a lot of things changes on CGE `master` in regards to macOS and OpenGL, and I tested -- `simple_shadow_map_teapots.x3dv` rendering goes without errors (both before and after these changes).

If you still can reproduce the issue with latest CGE / view3dscene (get them from https://castle-engine.io/download , or just view3dscene "snapshot" version from https://castle-engine.io/view3dscene.php ) please reopen.

![Zrzut ekranu z 2023-02-21 02-59-43](https://user-images.githubusercontent.com/1076978/220228668-2624aa3d-2416-4951-8686-0d987064a8f4.png)
