### ISSUE TITLE
Shadows removing ground

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#308]
I guess this one is different from the other lighting ones somehow (as you asked me to ticket it)

Note that the model in the center is lit by six spots (up, down, left, right, back + front) in it's own scene so it is always highly visible. The model is then placed in another scene called 'Stage' with the ground and a global light intended to cast shadows on the ground - getting this working reliably is a nightmare!

Anyway - Here's a lit without shadows image as a control...

![grab_0001](https://user-images.githubusercontent.com/1549219/122936364-0131cd80-d369-11eb-9571-636e570f0ffe.jpg)

That one's a Point - add Shadows := True to it and we get...

![grab_0002](https://user-images.githubusercontent.com/1549219/122936548-24f51380-d369-11eb-98e2-f55d6e2178d6.jpg)

Change to spot and we get...

![grab_0003](https://user-images.githubusercontent.com/1549219/122936624-35a58980-d369-11eb-9eb6-7f0ee495c5bf.jpg)

The last case is Directional - I've got that working using one specific set of settings it took me ages to work out so here's one where the direction is altered (I've got it on a rotary button - this is 225% rotation see below)

![grab_0004](https://user-images.githubusercontent.com/1549219/122937037-8e752200-d369-11eb-82e6-177c0e669fb1.jpg)

Of note with directional lighting is that there is no lighting on the 'ground' in three of the four quadrants

The rotation knob explained - it's a little debugging thing so I could interact with the lights...

>   ARadius := 1;
>   ATheta := DegToRad(BGRAKnob1.Value);
>   AElevation := -12;
>   ADir := Vector3(sqrt(ARadius) * Cos(ATheta),
>                   AElevation,
>                   sqrt(ARadius) * Sin(ATheta));
> 
>   CastleApp.Stage.LightNode.Direction := ADir;

**Comment by michaliskambi** [comment]
Fixed. As testcases I used https://github.com/castle-engine/demo-models , subdirectory `shadow_maps/explicit_projection_parameters/`. After this fix, they look nice, and we don't show black when shadow map doesn't reach.
![directional_params_explicit_0](https://user-images.githubusercontent.com/1076978/220814162-e8b99c0d-9ada-43e4-94cf-03cf7748880d.png)
![spot_params_explicit_0](https://user-images.githubusercontent.com/1076978/220814163-0d1a614b-4ba5-4121-8ddc-a98d2205687b.png)
