### ISSUE TITLE
Joystick test program

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#31]
As usually I've invented a bycicle and made up a joystick example :) Afterwards I saw that there is already an example available in "examples". I haven't tried it yet. I'll check it and maybe it'd be a good idea to merge them?
[JoyTest.tar.gz](https://github.com/castle-engine/castle-engine/files/574857/JoyTest.tar.gz)

**Comment by michaliskambi** [comment]
It's probably best to merge it, as both examples seem to cover the same ground. I would welcome a pull request:)

As I cannot yet test the joystick functionality myself, I very much depend on contributions here:)

**Comment by eugeneloza** [comment]
Moving the issue to my fork. Closed this one for now. I'll report here as soon as I've finished.
