### ISSUE TITLE
castle-editor (with custom component) cannot rebuild itself

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#329]
This screenshot should fully explain this issue

![image](https://user-images.githubusercontent.com/7451778/127773895-f5af6333-ff87-4e32-9c4f-7c330f6daf4b.png)
(the editor cannot rebuild itself and this action have to be performed by another copy of the editor)

**Comment by michaliskambi** [comment]
Confirmed and fully agreed, I'll handle this and https://github.com/castle-engine/castle-engine/issues/328 this evening :)

**Comment by michaliskambi** [comment]
In progress. Right now the old editor instance really waits for the new editor to start (it can even run longer, if you were in the middle of design changes, and to the question "do you want to save the design" you answer "cancel").

So this prevents, on Windows, from writing the new editor exe right at the place of the old exe. Simple solutions (compile to a different name + rename, or use separate launcher that renames + runs) will not work, until we have a clear way of knowing "previous editor really finished the execution".

I will think, and also look at Lazarus, how to do it easily + 100% reliably.

Note that you can also run custom editor from command-line by `castle-engine editor`. I.e. the build tool actually compiles the custom editor and runs it. This is another workaround (from doing it from another copy of the editor).

**Comment by michaliskambi** [comment]
Fixed by https://github.com/castle-engine/castle-engine/commit/9ac74a6e8066829dcc914a1e52706f1bced9a550 + https://github.com/castle-engine/castle-engine/commit/03aeaf8811f2b5ae6cb5169897a3e92d1d29d9a7 .
