### ISSUE TITLE
castle-editor should be built with unique directive symbol

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#330]
I've been maintained a version of build-tool's custom_editor_template with `CASTLE_EDITOR` directive symbol in it's .LPI file, so I can use it in custom components to tell which part of code should belong to the editor.

I think this should be added to the official version of the build-tool. I know there's `CastleDesignMode`, but it won't work on unit section for example.

**Comment by michaliskambi** [comment]
Done.

With a trivial demo that it can be used to register URL property editor in `examples/advanced_editor/code/gamecontrols.pas`.

Note that I decided to call the symbol `CASTLE_DESIGN_MODE` to be consistent with `CastleDesignMode`.

**Comment by michaliskambi** [comment]
P.S. Note that the package with custom components depends on LCL, and Lazarus automatically defines `LCL` symbol in this case.

So for most CGE applications (the ones not using LCL and `TCastleControlBase` at runtime, but relying on `TCastleWindowBase`) using `{$ifdef CASTLE_DESIGN_MODE}` will be actually equivalent to `{$ifdef LCL}`. The difference really only occurs for applications using `TCastleControlBase`.
