### ISSUE TITLE
Align buttons with images

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#331]
Mentioned in discord recenty so reminder time...

ATM we get this if using an image inside a button

![oldbtn](https://user-images.githubusercontent.com/1549219/128096372-e260d2f7-d3e2-4e8f-9afc-ab2eacf085ca.png)

While this is fine for horizontally aligned buttons it looks bad with vertical alignment where something like this looks better

![newbtn](https://user-images.githubusercontent.com/1549219/128096467-f2bf7596-30f9-43b5-9ddb-3b4b883be8a4.png)

**Comment by michaliskambi** [comment]
Partially fixed. We have `TCastleButton.Alignment`, `TCastleButton.VerticalAlignment` that align within the button, still honoring the button.

Leaving this open, and some combinations of alignment + ImageLayout (when TCastleButton.Image is not assigned) are not yet supported, and will raise exceptions when drawing.

**Comment by michaliskambi** [comment]
Closing this -- `TCastleButton.Alignment`, `TCastleButton.VerticalAlignment` fulfill the feature request outlined in this issue. Set `MyButton.Alignment := hpLeft` to have the effect shown in the image.

Note: Some combinations of alignment + `ImageLayout` remain unsupported (and will show a clear exception) but these are so corner-cases that it doesn't seem anyone needs them. Nobody seemed to be even noticed them unsupported for ~2 years now :) And users can place any content, including TCastleLabel and TCastleImageControl, as children inside a button -- which allow to practically get anything in a button if necessary. So these unsupported combination can just remain unsupported for now. They are marked as TODO in code, and that's good enough, until there will occur real-life need for them.
