### ISSUE TITLE
Allows to edit TCollectionItem properties in castle-editor

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#335]
![image](https://user-images.githubusercontent.com/7451778/131313983-d4ab5c7a-3e32-4680-abb8-da48a6958444.png)
Right now if we select/double click a TCollectionItem instance the editor does nothing.

**Comment by michaliskambi** [comment]
Ah, I recall I saw this problem too, trying to add database components to CGE editor in https://github.com/castle-engine/castle-db-aware-controls :)

Do you know what is the reason / have a fix?

**Comment by Kagamma** [comment]
According to this topic https://forum.lazarus.freepascal.org/index.php?topic=28544.0 looks like we have to catch the click event ourselves and then point TTIPropertyGrid to the selected item instead. Then we restore TTIPropertyGrid to previous selected item once we're done editing.

**Comment by Kagamma** [comment]
This feature is added in https://github.com/castle-engine/castle-engine/pull/337
