### ISSUE TITLE
Inverted normals but displays fine on gltf viewer - sample model

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#336]
> Hm, confirmed. It has inverted normals in view3dscene. Works fine in https://gltf-viewer.donmccurdy.com/  and https://github.khronos.org/glTF-Sample-Viewer-Release/ so it's CGE bug. Please submt a GitHub issue with this model, I'll look into it ASAP.

[battlement_half.zip](https://github.com/castle-engine/castle-engine/files/7077249/battlement_half.zip)

For comparison...
[battlement_half.obj.zip](https://github.com/castle-engine/castle-engine/files/7077254/battlement_half.obj.zip)

**Comment by michaliskambi** [comment]
The model has a negative scale on one component (scale = -1, 1, 1) which confuses our workings.

Hm, while we generally don't promise that lighting will work OK with some negative scales, but this one could be handled. The initial idea is to do this mod:

```
modified   src/x3d/opengl/castleinternalrenderer_meshrenderer.inc
@@ -527,7 +527,21 @@ end;
 procedure TBaseCoordinateRenderer.RenderCoordinateBegin;
 begin
   RenderContext.CullFace := Arrays.CullFace;
-  RenderContext.FrontFaceCcw := Arrays.FrontFaceCcw;
+  { Following glTF on what to do with negative scale transformations:
+
+    """
+    If the determinant of the transform is a negative value,
+    the winding order of the mesh triangle faces should be reversed.
+    This supports negative scales for mirroring geometry.
+    """
+
+    This makes backface culling remove proper faces when negative
+    scale is used.
+    See https://github.com/castle-engine/castle-engine/issues/336 . }
+  if Shape.ModelView.Determinant < 0 then
+    RenderContext.FrontFaceCcw := not Arrays.FrontFaceCcw
+  else
+    RenderContext.FrontFaceCcw := Arrays.FrontFaceCcw;
   if Renderer.RenderOptions.Mode = rmFull then
     Renderer.SmoothShading := not Arrays.ForceFlatShading;
 end;
```

I'll have to test how does it behave with various scales (all or none components negative) and see can I implement it more efficiently. But the patch above already fixes behavior of the testcase.

**Comment by michaliskambi** [comment]
You can now enable `RenderOptions.RobustNegativeScale` to have backface culling and lighting work reliably on scenes using (potentially) negative scale.

I hope to one day just make it a default -- but for now, it is disabled by default, as it has a small performance cost and is not necessary on most models.

view3dscene has a menu item "View -> Robust Negative Scale" to easily test it.
