### ISSUE TITLE
Invalid GLTFs (created by assimp)

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#339]
The attached CC0 model incorrectly converts from a fbx to a gltf using assimp which can have repercussions in CGE (spotted when writing custom url handler)

If the model is extracted then the fbx version is converted to a gltf using the following command...

`assimp export tree.fbx tree.gltf`

Examining the resultant tree.gltf you will find th following incorrect images section

`    "images": [
        {
            "uri": "..\\Textures\\Bark_Texture.jpg"
        },
        {
            "uri": "..\\Textures\\Leaf_Texture.png"
        }
    ],
`

[Tree.zip](https://github.com/castle-engine/castle-engine/files/7115720/Tree.zip)

Ref - https://github.com/assimp/assimp/issues/4065

**Comment by michaliskambi** [comment]
Fixed.

Note that at this testcase, there's an unrelated issue -- alpha mode should probably be set to "blend" or "alpha test" on leaves texture. Right now texture is treated as opaque, which follows the glTF information.

I didn't investigate now what is the cause. The issue may be at various places in the toolchain (I understand you exported FBX from Blender):

- problem in Blender file (material should be marked as "alpha mode" = "blend" or "alpha test". This works OK when exporting Blender->glTF directly)

- problem in Blender->FBX exporter 

- problem in Assimp FBX->glTF

I do not know whether the "alpha mode" can be recorded in FBX. I know that gTF does require it. CGE allows to use "alpha mode" = "AUTO" in X3D, so we can guess blending by the fact that your texture has alpha channel, but in case of glTF the default says to use "alpha mode" opaque, without any auto-detection.

**Comment by peardox** [comment]
Yes, I had to recreate the test model from the FBX Quaternius supplied as the original FBX version was missing textures and as the whole purpose of the test mode was to check texture exports from FBX to GLTF.

The submitted model is still the CC0 Quaternius supplied, just probably incorrectly 'fixed' by myself...

If you wanna alter it then NP, it'll still be CCO :)
