### ISSUE TITLE
Why my PlayingSound.OnStop is happenning only when I close the application?

### ISSUE THREAD

**Issue by cpicanco** [castle-engine/castle-engine#343]
Hi castle engineers, rsrs

I am just trying to understand why the OnStop is not happening when it should. I have this very simple class and the OnStop is happening only when I close the application:

```
unit Consequences.Custom;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, CastleSoundEngine, Stimuli.Image;

type

  { TConsequence }

  TConsequence = class(TComponent)
  private
    FAuditive: TCastlePlayingSound;
    FVisual: TStimulusFigure;
    procedure SoundStopped(Sender : TObject);
  public
    constructor Create(AOwner: TComponent); override;
    destructor Destroy; override;
    procedure Load(AImage, ASound : string);
    procedure Play;
    property Visual : TStimulusFigure read FVisual write FVisual;
    property Auditive : TCastlePlayingSound read FAuditive write FAuditive;
  end;

var
  CustomConsequence : TConsequence;

implementation

uses
  Session.Configuration.GlobalContainer;

{ TConsequence }

procedure TConsequence.SoundStopped(Sender: TObject);
begin
  FVisual.Stop;
end;

constructor TConsequence.Create(AOwner: TComponent);
begin
  inherited Create(AOwner);
  FVisual := TStimulusFigure.Create(Self);
  FAuditive := TCastlePlayingSound.Create(Self);
  FAuditive.Sound := TCastleSound.Create(Self);
  FAuditive.FreeOnStop := False;
  FAuditive.Loop := False;
  FAuditive.InitialOffset := 0;
  FAuditive.Offset := 0;
  FAuditive.OnStop := @SoundStopped;
end;

destructor TConsequence.Destroy;
begin
  { do stuff here }
  inherited Destroy;
end;

procedure TConsequence.Load(AImage, ASound: string);
begin
  FVisual.LoadFromFile(GlobalContainer.RootMedia+AImage);
  FAuditive.Sound.URL := GlobalContainer.RootMedia+ASound;
end;

procedure TConsequence.Play;
begin
  FVisual.Start;
  FAuditive.Stop;
  SoundEngine.Play(FAuditive);
end;

initialization
  CustomConsequence := TConsequence.Create(nil);
  CustomConsequence.Load('imagem-jocosa.png', 'risada-jocosa.wav');

finalization
  CustomConsequence.Free;

end.
```

**Comment by cpicanco** [comment]
What I am trying to do is to hide an image with `FVisual.Stop` using the `PlayingSound.OnStop` event. Everything is working just fine, except the OnStop. I can hide the image manually and I can play the sound just fine.

**Comment by michaliskambi** [comment]
It seems you're using CGE, but without any `TCastleWindowBase` or `TCasleControlBase` (i.e. engine doesn't do any rendering or processing).

In this case you have to do one additional thing: call `ApplicationProperties._Update` regularly (`ApplicationProperties` is a singleton in `CastleApplicationProperties`. See how e.g. `examples/audio/audio_player/` does it -- it just

- uses regular LCL `TTimer` component
- with timer interval = 1
- and inside does
- 
```
procedure TMainForm.Timer1Timer(Sender: TObject);
begin
  { When application doesn't use any TCastleWindowBase or TCastleControlBase,
    this must be called manually to update some CGE state,
    e.g. detect unused sounds. }
  ApplicationProperties._Update;

  // the rest of implementation in examples/audio/audio_player/ is specific to that example
end;
```

**Comment by cpicanco** [comment]
Hi Michael, there is no need to reopen the issue. Just want to thank you for the fast response. If you let ask you a noob question, please, why you choose to use a timer instead of callbacks (in a event driven fashion)?


PS.: Just found this stackoverflow about OpenAL and "OnFinishedPlaying" events: https://stackoverflow.com/questions/1046315/getting-notified-when-a-sound-is-done-playing-in-openal

**Comment by michaliskambi** [comment]
> Hi Michael, there is no need to reopen the issue. Just want to thank you for the fast response. If you let me ask you a noob question, please, why you choose to use a timer instead of callbacks (in a event driven fashion)?

Well, the `ApplicationProperties._Update` must be called regularly, using whatever means are the simplest :) In case you use any `TCastleWindowBase` or `TCasleControlBase` this is done automatically and hidden from you. If not -> you need to do this regularly yourself.

Using LCL `TTimer` seems just like a simplest solution for this case. Other approaches, like using LCL `TApplicationProperties.OnIdle`, would be fine too.

Note that using `TTimer` does use callbacks. You just have to call it regularly. There's nothing to react to.

> PS.: Just found this stackoverflow about OpenAL and "OnFinishedPlaying" events: https://stackoverflow.com/questions/1046315/getting-notified-when-a-sound-is-done-playing-in-openal

This is indeed what is done under the hood, CGE regularly checks `AL_SOURCE_STATE` and compares whether it is `AL_PLAYING`. One has to do it like this in OpenAL -- OpenAL doesn't expose by itself any callback to notify when sound stopped, you have to "observe" OpenAL sounds to detect it. This is what `ApplicationProperties._Update` essentially does.

**Comment by michaliskambi** [comment]
While I understand it works, but I would much rather advise my solution for this, from my previous answer here.

In your solution: 
- you have hardcoded some things (25 times, 5 seconds) and nothing here is guaranteed -- the values actually needed may depend on OpenAL, OpenAL backend (OS), how much the OS is overworked. 
- You also do `Sleep(...)` which is generally a bad idea in an interactive apps -- you hang the process (even if for a short time).

I would definitely advise instead to go with what I proposed, i.e. use `TTimer` and call `ApplicationProperties._Update` there. Then
- there's no need to hang the process
- there's no need to hardcode values like 25 and 5
- it is guaranteed to always work, we test it in CGE e.g. by `examples/audio/audio_player/`, and in general it is closely equivalent to what happens when you use `TCastleWindowBase` or `TCastleControlBase`
- there's no need to call LCL `Application.ProcessMessages`.

**Comment by cpicanco** [comment]
I will did @michaliskambi !

Now you can choose to run the update method forever or for some time:

```
unit Session.CastleUtils;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, ExtCtrls;

type

  { TSessionUpdater }

  TSessionUpdater = class(TObject)
  private
    FTimer : TTimer;
    FStarted : Extended;
    FSeconds : Extended;
    procedure UpdateForever(Sender : TObject);
    procedure UpdateForSomeTime(Sender : TObject);
  public
    constructor Create(AUpdateForever : Boolean); reintroduce;
    destructor Destroy; override;
    procedure Start;
    property Seconds : Extended read FSeconds write FSeconds;
  end;

var
  SessionUpdater : TSessionUpdater;

implementation

uses CastleApplicationProperties, Forms, Timestamps.Helpers;

{ TSessionUpdater }

procedure TSessionUpdater.UpdateForever(Sender: TObject);
begin
  ApplicationProperties._Update;
end;

procedure TSessionUpdater.UpdateForSomeTime(Sender: TObject);
begin
  ApplicationProperties._Update;
  if (GetCustomTick - FStarted) > Seconds then begin
    FTimer.Enabled := False;
  end;
end;

constructor TSessionUpdater.Create(AUpdateForever : Boolean);
begin
  FTimer := TTimer.Create(nil);
  FSeconds := 1;
  FTimer.Enabled := False;
  FTimer.Interval := 1;
  if AUpdateForever then begin
    FTimer.OnTimer := @UpdateForever;
  end else begin
    FTimer.OnTimer := @UpdateForSomeTime;
  end;
end;

destructor TSessionUpdater.Destroy;
begin
  FTimer.Free;
  inherited Destroy;
end;

procedure TSessionUpdater.Start;
begin
  FTimer.Enabled := True;
  FStarted := GetCustomTick;
end;

initialization
  SessionUpdater := TSessionUpdater.Create(False);

finalization
  SessionUpdater.Free;

end.
```
