### ISSUE TITLE
How to call a sound when another sound stops?

### ISSUE THREAD

**Issue by cpicanco** [castle-engine/castle-engine#344]
Right now I am trying to use the OnStop method and the SoundEngine.Play. But when I have two sounds, lets say:

```pascal
//CallSound2
SoundEngine.Play(Sound2);

// setup
Sound1.OnStop := @CallSound2;
Sound2.OnStop := @DoSomething;
SoundEngine.Play(Sound1);
```

the second sound will not call the OnStop (i.e., DoSomething) because the first `OnStop` didn't finnish!! Damn. (Does it make any sense??) So I am guessing I need some sort of Independence from `SoundEngine.Play` central calls...

**Comment by michaliskambi** [comment]
I'm afraid I don't follow the description of the problem precisely.

What you describe in general -- should be possible, you can start 1 sound in the `OnStop` of another sound. And `OnStop` should be reliably executed for all sounds that, well, stop.

Please submit a testcase (simplest possible application to reproduce the problem).

**Comment by cpicanco** [comment]
In the present example the CastleSoundEngine functionallity is wrapped inside `Audio.CastleSound.TSound`.

Compile, execute, then wait 2 seconds:

1. the first sound will play then;
2. the second sound will play and a square will be draw at the form top left;
3. then the square was supposed to hide, but it is not hiding. So here is the bug on the second call to OnStop.


[serial_timer.zip](https://github.com/castle-engine/castle-engine/files/7264461/serial_timer.zip)
