### ISSUE TITLE
Editor: Access violation when try drag a Button to HorizontalGroup

### ISSUE THREAD

**Issue by and3md** [castle-engine/castle-engine#353]
Just a reminder to investigate after I finish my current task.

Steps to reproduce: 
1. Create new project with empty template
2. Open design
3. Add button
4. Add horizontal group
5. Try drag button to horizontal group -> Access violation

System: Windows 10
Current master.

**Comment by michaliskambi** [comment]
Tested now quickly on Linux/x86_64, works OK, dragged button lands inside a horizontal group without any error.

With latest master, FPC 3.2.2.

![Zrzut ekranu z 2021-12-15 17-21-58](https://user-images.githubusercontent.com/1076978/146224527-044825ac-430e-450f-b9f8-4365d02f4c64.png)

**Comment by eugeneloza** [comment]
Unfortunately I cannot reproduce it either. Neither on binaries downloaded from the official site just a few seconds ago, nor on my local build (with some quite obsolete CGE version). Windows 10x64.

However, from time to time I run into this bug. I couldn't find a way to reproduce it. For me it's usually after using Castle Editor for some long time and then trying to drag something around (either the last component or into the last component of some hierarchy level). It feels to have something to do with the Undo System, but I could never get neither the proper debug line nor (even unreliable) reproduction steps.

**Comment by eugeneloza** [comment]
This bug jumps up from time to time, very rarely, but still does:

https://trello.com/c/YizbsBMD/110-bug-access-violation-in-castle-editor-when-drag-n-dropping-items-in-hierarchy

https://trello.com/c/hwVKI010/114-bug-access-violation-in-castle-editor-when-changing-the-name-of-the-component-in-hierarchy-and-trying-to-drag-it-by-mouse-in-edi

Also this one may be somehow related: https://trello.com/c/V6v2rBwv/75-bug-access-violation-in-castle-editor

**Comment by and3md** [comment]
@michaliskambi I didn't have any editor crashes when I made platformer on Linux so I think that can be only Windows related issue. 
@eugeneloza I don't remember if I used Undo before AV. But the designs was a lot simpler than level in platformer demo. And I had two AV in one day (on Windows). I will check that more carefully and maybe I'll find a case that can be reproduced every time.

**Comment by eugeneloza** [comment]
> I don't remember if I used Undo before AV

Yes, it doesn't happen when you perform Undo. But when an Undo record is created. That is on every meaningful action. And if some memory gets corrupted / freed before it's accessed by Undo subsystem to create an Undo snapshot, it'll result in an Access Violation.

**Comment by and3md** [comment]
@eugeneloza @michaliskambi  I'm not sure if this crash is the same as before, but I managed to reproduce it and fix the bug. I was dealing with it now because I came across him once again. Maybe I'm the (un)lucky one to found bugs :D

The bug is on Windows only and steps to reproduce are:

1. Create new project with empty template
2. Open design
3. Add button
4. Add horizontal group
5. Try drag button BELLOW horizontal group -> Access violation 

The cause of the error was using TTreeNode after being deleted. Probably worked on linux because in GTK the nodes are removed after some time. The solution is available [here](https://github.com/castle-engine/castle-engine/tree/editor_crash). But I still have to do tests on Linux.

I also fixed selection bug after drug and removed hierarchy reload after drag'n'drop.

**Comment by eugeneloza** [comment]
> Try drag button BELLOW horizontal group -> Access violation

I still can't reproduce this bug this way. But your fixes do make sense.

**Comment by and3md** [comment]
Unfortunately, there the hierarchy is still reloaded after drag'n'drop transforms. One reload is removed but there is another one.

**Comment by and3md** [comment]
Ahh maybe you are in debug? Because I saw that the bug is hard to reproduce in debug (maybe some object has longer life then) and always in Release.

**Comment by michaliskambi** [comment]
> Ahh maybe you are in debug? Because I saw that the bug is hard to reproduce in debug (maybe some object has longer life then) and always in Release.

We don't use debug/release modes in CGE editor. (Because they would only complicate testing, and the debug/release would not apply to CGE packages doing actual "heavy work", so it would be that beneficial.)

**Comment by and3md** [comment]
I tested on Lazarus 2.0.13 (fixes branch) and 2.2RC3 (fixes branch) and I can reproduce it always.

**Comment by and3md** [comment]
> > Ahh maybe you are in debug? Because I saw that the bug is hard to reproduce in debug (maybe some object has longer life then) and always in Release.
> 
> We don't use debug/release modes in CGE editor. (Because they would only complicate testing, and the debug/release would not apply to CGE packages doing actual "heavy work", so it would not be that beneficial.)

I also can reproduce bug in default mode.

**Comment by and3md** [comment]
![obraz](https://user-images.githubusercontent.com/18555708/146933475-68f7b1fc-b18c-40dc-9da0-6779b13c15db.png)

**Comment by eugeneloza** [comment]
> Ahh maybe you are in debug? Because I saw that the bug is hard to reproduce in debug (maybe some object has longer life then) and always in Release.

No, running binaries from castle-engine.io

**Comment by and3md** [comment]
> Just additionally tried and cannot reproduce it neither in Default/Debug/Release mode when build from sources in Lazarus

So I'm the unlucky one ;) With those steps (Create new project with empty template, open design, add button, add horizontal group) I get AV always. When I take other components I need make more drag'n'drop operations but finally I get AV. I don't know why it behaves differently on your computer (my PC: Windows 10 x64 Pro, Ryzen 3700X 32 GB RAM, GTX 1060).

**Comment by eugeneloza** [comment]
No, you actually the lucky one, because hopefully it helps to fix the bug!

> I don't know why it behaves differently on your computer

I don't think it's the hardware configuration, most likely some OS features, but Windows 10x64, Ryzen 5 1600, 40 Gb RAM, Radeon RX 560. So the only significant difference is the videocard.

**Comment by and3md** [comment]
Editor from our website also gets AV on my computer.

**Comment by michaliskambi** [comment]
I can reproduce the bug too! Thanks for the precise description @and3md 

> The bug is on Windows only and steps to reproduce are:
>
>    Create new project with empty template
>    Open design
>    Add button
>    Add horizontal group
>    Try drag button BELLOW horizontal group -> Access violation

I'm on 
- Windows 10, 
- 64-bit, 
- 8 GB RAM, 
- CPU: Intel(R) Core(TM) i5-8300H CPU,
- GPU: 

    ```
    Vendor: NVIDIA Corporation
    Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
    ```
- I'm on laptop using touchpad now, in case it matters. I used touchpad for dragging during reproduction.

I did this using our binary build from https://castle-engine.io/ .

We talked today with @and3md , 

- https://github.com/castle-engine/castle-engine/compare/editor_crash is the right solution,

-  *and* it brings a much-needed improvement to the engine also (no reload of the hierarchy each time you drag something, will also fix https://trello.com/c/qP2DIKwP/192-when-adding-dragging-a-component-the-collapsed-states-of-ttreeview-components-resets-and-view-selection-jumps-to-top )

- one additional thing I require for the PR: since we remove `UpdateDesign`, let's add `ValidateHierarchy` that iterates over the tree in LCL, and in tree in CGE, and makes sure they match: that captions and data of LCL tree nodes is as we expect. If not -> we can make `WriteLnWarning('Hierarchy view desynchronized with CGE internal hierarchy. 1. Please submit a bug, this should never happen.  2. To workaround it for now, save and reopen the design file.');`

**Comment by eugeneloza** [comment]
> GeForce 

I wonder, can it be NVIDIA-only issue (as in something updates at the wrong moment)? I mean I get AVs from time to time, but extremely rarely (though the anticipated reproduction steps seem to be consistent with the steps above) and I could not reproduce the bug following those exact steps no matter how many times I've tried.
