### ISSUE TITLE
Error trying to create new project

### ISSUE THREAD

**Issue by the-Arioch** [castle-engine/castle-engine#357]
Tried to repro #348 but could not, perhaps did not have anyhow realistically complex projects.

So i just clicked New Project, 3D FPS Game, and without chaning a single property clicked Create.

The folder was created, some text application window was run (perhaps it is not nice it was a separate windows, not a log panel inside GCE).

And then this error:

```
[Window Title]
Error

[Content]
Exception "Exception":
Project name contains invalid characters: "${XmlQuote(PROJECT_NAME)}", this character is not allowed: "$"

[OK]
```

And it seems the manifest files was not touched at all!!!

```
<?xml version="1.0" encoding="utf-8"?>
<project name="${XmlQuote(PROJECT_NAME)}"
  standalone_source="${XmlQuote(PROJECT_PASCAL_NAME)}_standalone.dpr"
  game_units="GameInitialize"
  qualified_name="${XmlQuote(PROJECT_QUALIFIED_NAME)}"
  caption="${XmlQuote(PROJECT_CAPTION)}"
>
  <compiler_options>
    <search_paths>
      <path value="code/" />
    </search_paths>
  </compiler_options>
</project>
```

I guess you forgot to enforce some `TemplateUpdate()` in the `CreateButton.OnClick` :-)

Mmm... no, if i change project title strings - the manifest file still remains the same...

**Comment by the-Arioch** [comment]
Dunno if any hints there

```
Found data in "D:\Castle Game Engine Projects\my-new-project\data\"
Automatically adding "Png" to dependencies because data contains file: file:///D:/Castle%20Game%20Engine%20Projects/my-new-project/data/menu-background.png
Automatically adding "Sound" to dependencies because data contains file: file:///D:/Castle%20Game%20Engine%20Projects/my-new-project/data/audio/flaunch.wav
Automatically adding "OggVorbis" to dependencies because data contains file: file:///D:/Castle%20Game%20Engine%20Projects/my-new-project/data/audio/dark_fallout.ogg
Automatically adding "Zlib" to dependencies because it is a prerequisite of existing dependency "Png"
Calling D:\DelphiProjects\Libs\Games\castle-engine\bin\castle-engine.exe
generate-program

Found data in "D:\Castle Game Engine Projects\my-new-project-1\data\"
Automatically adding "Png" to dependencies because data contains file: file:///D:/Castle%20Game%20Engine%20Projects/my-new-project-1/data/menu-background.png
Automatically adding "Sound" to dependencies because data contains file: file:///D:/Castle%20Game%20Engine%20Projects/my-new-project-1/data/audio/flaunch.wav
Automatically adding "OggVorbis" to dependencies because data contains file: file:///D:/Castle%20Game%20Engine%20Projects/my-new-project-1/data/audio/dark_fallout.ogg
Automatically adding "Zlib" to dependencies because it is a prerequisite of existing dependency "Png"
```

**Comment by eugeneloza** [comment]
I believe it might be the consequence of https://github.com/castle-engine/castle-engine/commit/9fca9ae2204ea4a171af70c9d8f2fd5d3ed2dea6

**Comment by michaliskambi** [comment]
@the-Arioch It works on my side. And the error seems like you have updated CGE, but didn't recompile the editor afterwards. 

New CGE source code has new templates which require new macros, which in turn require new editor.

See https://castle-engine.io/compiling_from_source.php#section_Updating -- if you update the source code, you always have to at least update the 
- build tool (command-line)
- and the editor

Please reopen if the problem persists after you recompile them.

**Comment by the-Arioch** [comment]
i believe i compiled them all and even Lazarus itself. Maybe i had to clean-build instead...

**Comment by the-Arioch** [comment]
PErhaps i copyied the exe file in wrong direction, dunno.

I rebuild again and carefully copied INTO \bin not out of it. 

And it works now... Rather stupid on my part...
