### ISSUE TITLE
Wish: make the Project Group to facilitate manual installation from sources

### ISSUE THREAD

**Issue by the-Arioch** [castle-engine/castle-engine#362]
Probably should be done after `castle-view-image` and `castle-view3dscene` got merged into main repo.

Chrome i heavy program, really. And when having more than single tab, noticeably heavy.

Compiling from sources after git pull needs looking into https://castle-engine.io/compiling_from_source.php every know and then.

In modern Delphi this would be mostly subsided by using Project Group (it is always used in Delphi today, even for a single project) and placing projects in proper order. Copying `.exe`s to `bin` then can be done as post-build event, or left to user to do manually. Installation of components into IDEs would had to be done manualy anyway. But at least the projects themselves woul be listed completely and in proper order.

Now it seems Lazarus has a similar functionality, albeit it is not compiled and installed by default, one has to add the "module" for it in `fpcupdeluxe` - https://wiki.freepascal.org/Project_Groups

Dunno if Lazarus can have post-build copying in OS-neutral way, probably not.

**Comment by michaliskambi** [comment]
> Dunno if Lazarus can have post-build copying in OS-neutral way, probably not.

It does, we use it in other cases.

> https://wiki.freepascal.org/Project_Groups

Until this is available in Lazarus out-of-the-box, I don't want to use it. I would be additional maintenance burden to support yet another way of compilation (we already support a few ways to compile everything), not many people would use it (until it's part of Lazarus) and I don't consider this a priority.

- It's really just 2 commands to compile editor and build tool, it is not that big issue. If you want to do this often, you don't even need to move then to `bin` subdirectory, you can instead add them to `$PATH` as mentioned on https://castle-engine.io/compiling_from_source.php  .

- It's rather trivial to read https://castle-engine.io/compiling_from_source.php . 

    As for your argument that opening webpages in a web browser is "heavy"... We all use WWW browsers for a lot of things now, including whole CGE website, including GitHub and this bugtracker -- so whatever you think of your web browser, you will have to use it anyway. You may switch to a different web browser if you want. 

- If you want to automate it -- you can use a shell script (these work on Windows too, with Cygwin/MinGW, you could probably use old BAT too). 
 
- If this sounds like too much work, just use a binary release.

**Comment by michaliskambi** [comment]
> However your answer suggests you already made such scripts for your Win system, just keeping them out of git.

No, I would commit them then :) I do try to publish stuff even remotely useful (though obscure things go to separate repo, like https://github.com/castle-engine/cge-scripts/ ).

I have set up my system such that I have built tool and editor on $PATH (I would want them on $PATH anyway to use on command-line) and I set $CASTLE_ENGINE_PATH so it doesn't matter from where I run them. When I update and see that something changed that could affect the build tool, I just go and recompile it. And I usually run editor, just like all other CGE applications, by `cd tools/castle-editor && castle-engine compile && castle-engine run` (that's part of my Emacs setup, https://github.com/michaliskambi/elisp ) so it gets recompiled automatically.

You can find in CGE  various scripts that do this, though. `pack_release.sh` rebuilds everything (essentially doing https://castle-engine.io/compiling_from_source.php ) though you probably don't want to use it (it requires various tools from Cygwin on Windows; for most people it would be easier to just download the binary CGE release).

**Comment by the-Arioch** [comment]
Funny that i already saw some Lazarus internal error, trying to utilize the
Package Group.

Not sure if it was related to using the Froup while having another
non-grouped project, dependent upon Castl, open in IDE.
Or just to the fact i rolled back my changes and pulled from you. In theory
make should understand it and recompile all PPUs

It also seem Lazarus just can not run without project at all. You close
project- you get that annoying little window, that can not be closed
without Lazarus itself.
Sadly PG is not a first class Lazarus citizen...

Anyway, on clean Laz restart it seemed to compile via the group, but it was
a bumpy ride.
