### ISSUE TITLE
Wiki example is using an absent file

### ISSUE THREAD

**Issue by the-Arioch** [castle-engine/castle-engine#368]
https://castle-engine.io/x3d_implementation_geometry2d.php

The source is a single .LPR file, but the source mentions some `face.png`.

Perhaps it better be changed into a normal demo project in `castle-engine\examples\` ?
Alternatively, a whole project as a .zip to be put into wiki.

Alternatively, yet worse would be using data:// URI  (Delphi literals, and need for newbs to add dependencies on castle_XXX packages)

**Comment by michaliskambi** [comment]
I explained on the page that you can really use any image file, just put it in `data`, and provided a link to the `face.png` as an example image.

> Perhaps it better be changed into a normal demo project in castle-engine\examples\ ?

Maybe. In general I'm not satisfied with the single-file-examples on our www, and will probably get rid of most of them sooner or later.
