### ISSUE TITLE
Wish, tutorials, 2D - more and earlier about coordinates transformations.

### ISSUE THREAD

**Issue by the-Arioch** [castle-engine/castle-engine#370]
2D games are split into two large classes: side scrollers and look-from-above. 
Those latter are again split into orthogonal view, and some "slanted", usually isometric views.

This all naturally raises a question, how to map "virtual world" coordinates to windows 2D coordinates.
Frankly, those are the questions immediately coming to mind when starting thinking about modelling 2D world.

I think they similarly better be addressed at very beginning of 2D tutorials. Now they seem to be randomly dispersed around articles and sources, by small disconnected pieces.

https://castle-engine.io/how_to_render_2d

> You should call TCastleViewport.Setup2D on the viewport to easily make it suitable for 2D games, and call TCastleScene.Setup2D to easily make it suitable for 2D games

Sound like a magic pill, just call and it is all done. "Easily". And no details are given, what it actually sets up, which only reinforces this idea, magic do-all call.

...until it dawns at you that a single parameter-less procedure can not guess if you wanted a side-scroller or "god view" 2D game.

This fundamental, i think, question better discussed immediately as the top bullet point or even before the list.

_Side note: is it really needed to call .Setup2D on both objects? can it set some flag that another object (and they would be connected to work together) would detect and setup itself accordingly?_

Much later there is an indirect mentioning.

> You can mix 2D and 3D freely. The TCastleViewport.Camera defines projection settings and controls camera...

Well, it is not only late in the list, it also hase a rather specific pre-condition, wanting to mix 3D and 2D, what if one does not want to? he would probably skip that bullet altogether, there already is a lot.

And, there could be a ready example about setting typical for 2D game projections.

> 1.2. Simple: Render using TDrawableImage

It is better here. "Use TDrawableImage as your main way to draw." is the immediate next line, and `TDrawableImage.Draw` has that information.

```
Note that the image position (ImageX, ImageY) is specified like a texture coordinate. So (0, 0) is actually the left-bottom corner of the left-bottom pixel, and (Width,Height) is the right-top corner of the right-top pixel. That is why image position and sizes are floats, it makes sense to render partial pixels this way (make sure you have SmoothScaling = True to get nice scaling of image contents).
```

However the working link `API reference: TDrawableImage.` is only the 4th of the links. A "linear" reader would only later come to it. Also, hy this fundamental information is a "note" ? i think it at least should be uplifted to the `Class TDrawableImage` / `Description` section - it is fundamental! And it is not only about .Draw, it is also about .Rect, about .Create ( ... ResizeX ... )

------------------

https://castle-engine.io/x3d_implementation_geometry2d.php

> `just place everything at a Z = zero plane`

okay, this is some indirect info about projection, but it is hidden really deep.

----

there is also "Miscellaneous knowledge: Which way is up?" - miscellanous? for 2D it is fundamental!

maybe it should be mentioned early on in every 2D-related article.

**Comment by michaliskambi** [comment]
The https://castle-engine.io/how_to_render_2d is indeed a poor introduction to "how to make 2D games". 

There is, since this weekend, a much better https://castle-engine.io/viewport_2d . And I plan to make it even better in the future (by adding more screenshots and step-by-step instructions, like https://castle-engine.io/viewport_3d has).

**Comment by the-Arioch** [comment]
Indeed, much better. Thanks. 
For example, personally, to me such use of term "Scene" as "any virtual object to be rendered" was counter-intuitive :-)

Still, being picky :-)

Viewport intro advertises "easy 3D "primitives"

1. Immediate question, if there is some way to connect number of figures into a single object. Like, a cylinder and two cones to make a like of android bat. This is perhaps implementation-specific. As one thing is those primitives are pre-set riangle mesh inside, and another is they are custom made of curves, etc. Adjacent question would be if such a "combined shape" can share the same skin/materiel.


Then, https://castle-engine.io/apidoc-unstable/html/CastleScene.TCastleCylinder.html (same with the Cone, etc)

2. `property Height ... default 2;` - frankly, what that 2 mean, what units? Of course, as 3D world is purely virtual. It is not like CSS which try to address physical world, thus provides "units of measurement". Using zooming factor (whatever the name, camera, projection) i can make 1.0 however large or however small. However, it is not described in the "viewport and scenes" tutorial either.

It was said those shapes provide for fast prototyping, but it would be nice then to have an immediate grasp how to set default coordinates to something meaningful for modern FullHD+ screens, perhaps there can be some consequent explanation of those properties and factors, starting with end leaf (those primitives, or distance between points in x3d mesh) and through all the tree up to the Viewscene and then up to the LCL/GCE form.  Some reasonable suggested defaults, for newb onboarding, with advices which of those factors later to tweak for which purposes.

3. `TCastleCylinder` API does not seem to provide for positioning/rotation, nor for skin/materiel. Some of those are exposed up the tree, in `tCastleAbstractPrimitive`. I wonder, if PasDoc can be set to (ideally - conditionally and to selected depth) publish inherited members too.

Otherwise each of specific primitives is begging a sidenote like "For rendering options, such as texture and color, read `tCastleAbstractPrimitive` documentation" - would be tedious...

Alternatively, there maybe can be a cheat-sheet for all those primitives, that would group their properties by purpose and then direct reader to proper API classes and then enlisting all the out-of-the-box primitives? Frankly, this seem ot me most suitable option, because...

4. To reach angle/rotation one has to go yet one more up the tree to the `TCastleTransform`. So, the above considerations hold here too. However, more than that.

Sphere and cube are axis-symmetric. Cylinder and cone are not. With those objects the immediate question comes `property Height ... default 2;` - what axis is Height? Yeah, later i can change it using Transform members, but... starting point?

I think a simple semi-transparent drawing with axes would be useful for those shapes, along with textual description. And those drawing then can be all published together in a simple table in the cheat-sheet proposed above.

Equally, such a cheat-sheet then can be linked from the 1.2 chapter of the Viewports intro, instead of specific classes.

**Comment by michaliskambi** [comment]
> Immediate question, if there is some way to connect number of figures into a single object.

You can, and the exact details "how to connect" depend on "why do you want to connect them".

If you just to transform them together, treat as one `TCastleTransform` -- then just place multiple `TCastleTransform` instances as children of one single `TCastleTransform` instance.

If you want to make a single mesh from them, this is also possible using X3D nodes. You can rebuild a mesh, you can combine nodes from multiple `TCastleScene` into one -- see "Building a mesh using code" on https://castle-engine.io/viewport_and_scenes_from_code#_building_a_mesh_using_code , see "should you combine multiple loaded models into one TCastleScene" on https://castle-engine.io/manual_transformation_hierarchy.php . In practice, you should not need to do this in simple applications.

If you want them to share the same material, assign the same `TPhysicalMaterialNode` to them. There will be a nicer management of materials (this is what "Ability to modify materials in CGE editor" in https://castle-engine.io/wp/2022/01/01/summary-of-2021-plans-for-2022/ refers to), so it should be simpler in the future.

> frankly, what that 2 mean, what units?

1 unit is 1 meter, but it is just a convention. 

You can in practice use other measurements (esp. 2D games commonly ignore this convention), just be sure to adjust sound speed, in units per second, if you want e.g. Doppler effect work naturally. I'll look into documenting it somewhere. It is specified already in X3D specification though, and it is normal in 3D authoring applications like Blender.

> It was said those shapes provide for fast prototyping, but it would be nice then to have an immediate grasp how to set default coordinates to something meaningful for modern FullHD+ screens, perhaps there can be some consequent explanation of those properties and factors, starting with end leaf (those primitives, or distance between points in x3d mesh) and through all the tree up to the Viewscene and then up to the LCL/GCE form. Some reasonable suggested defaults, for newb onboarding, with advices which of those factors later to tweak for which purposes.

If you mean to include primitives (TCastleCylinder etc.) in the docs more -- perhaps. They are quite obvious, and most/all the questions you can answer yourself by just adding them in CGE editor.

> TCastleCylinder API does not seem to provide for positioning/rotation, nor for skin/materiel.

As you noted, it is possible, as it descends from tCastleAbstractPrimitive that allows to set "material".

( I would advise to not use the term "skin", in 3D graphics it can be easily misiterpreted as refering to the "skinned animation", and it seems you just mean "material". )

> I wonder, if PasDoc can be set to (ideally - conditionally and to selected depth) publish inherited members too.

Right now, PasDoc doesn't have such functionality. But indeed it should. We already have an issue about it, https://github.com/castle-engine/castle-engine/issues/177 .

> To think of it, such an all-of-them drawing perhaps can be made a simple demo-project linked to the cheat-sheet page, and its screenshot substitute mostly for the table?..

You can look at drawings in X3D specification of Geometry3D component, https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD/Part01/components/geometry3D.html . Our primitives correspond to them. See

- Box: https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD/Part01/components/geometry3D.html#Box
- Cone: https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD/Part01/components/geometry3D.html#Cone
- Cylinder: https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD/Part01/components/geometry3D.html#Cylinder

Indeed, adding such drawings to the API docs would be helpful. I'll see into it later.

**Comment by the-Arioch** [comment]
> If you just to transform them together, treat as one TCastleTransform

Exactly. And also maybe an easier way to do things like "assign the same TPhysicalMaterialNode to them", but that is only made once, so is not that crucial.

> then just place multiple TCastleTransform instances as children of one single TCastleTransform instance.

I see, i thought there would be some special "aggregation" object, not jsut base class :-)
Well, this seems to be a good hint to newbs in tutorials :-)

I think i saw somewhere in low-level manuals (x3d? glTF? irrelevant) that to merge several objects a special collection-like tag exists, so that did nor help either. Not that it should had helped...

> just be sure to adjust sound speed, in units per second, if you want e.g. Doppler effect work naturally. 

See, that is hen and egg. To get even remote idea how to "adjust" - to compensate for my deviations - i have to have idea what my deviations were, and that requires idea what are "normal" expectations of the engine :-D

> you can answer yourself by just adding them in CGE editor.

Oh, i could just generate them in demo app and see.

But it is a "road report" of a newb, highlighting where tutorials can stiull be made easier to consume.

Also... no, "just do and see" is not a 100% replacement, for "documentation is contract" and implementation behavior may be a contract or just a volatile implementation detail.

> I'll see into it later.

Good. That was my intention :-)

**Comment by the-Arioch** [comment]
Docs: Rotation in 3D, around a specified axis. Rotation is expressed as a 4D vector, in which the first 3 components specify the rotation axis (does not need to be normalized, but must be non-zero), and the last component is the rotation angle in radians.

Does not seem true...

Also - _Note: the Rotation axis (first 3 components) must be non-zero_ - the wording is unlucky, it suggests that allthree of X, Y AND Z should be non-zero.

```
procedure TfmSea.FormCreate(Sender: TObject);
var H: single;
begin
  Viewport := TCastleViewport.Create(Self);
  Viewport.FullSize := true;
  Viewport.Setup2D;

  Viewport.Camera.Orthographic.Width := 2000 * pxInMeter;
  Viewport.Camera.Orthographic.Origin := Vector2(0.5, 0.5);
  Viewport.BackgroundColor := Navy;

  CastleSea.Controls.InsertFront(Viewport);
  
  MyCone := TCastleCone.Create(Self);
  MyCone.Material := pmUnlit;
  MyCone.Color := Yellow;
  H := 150 * pxInMeter;
  MyCone.Height := H;

  MyCone.Center := Vector3(0, h/2, 0);
  MyCone.BottomRadius := H/4;
  MyCone.TranslationXY := Vector2(0, h/2);
  MyCone.Rotation.Init(0,0, 1 {2, 3, 4} , pi {*0.5} {*1.5} );

  Viewport.Items.Add(MyCone);
end;
```

The quoted doc suggests i should be rotating the cone by changing it's 4th W component while keeping Z axis (3rd paramneter to .Init) any non-zero value.

The test shows, however, i actually have specify the rotation angle in Radians as Z parameter, and W does not matter.

**Comment by Kagamma** [comment]
@michaliskambi TGenericVector4.Init assigns the wrong value to itself.
![image](https://user-images.githubusercontent.com/7451778/151727695-522692c7-3eb9-45c7-9639-b22f55b0e3be.png)

**Comment by the-Arioch** [comment]
Well, wrong or not, but it is haaaandy :-)

**Comment by the-Arioch** [comment]
One more thing lacking from tutorialsm lowlevel ones, is how to make the picture update.

It seems the correct call (at least it does the tirck) is `Viewport.Update` but its parameters are not documented.

It seems that in a typical game the time flow and events processing are done automatically in TCastleScene, so the quotes like _The state has an Update method that is continuously called by the engine._

It feels like there is a need to overview "time transformaitons" like they flows through the CGE internals, and like it is somewhat described about coordinates/tranformations/rotations.

**Comment by the-Arioch** [comment]
It's a crazy, crazy world...

So, we can assemble few primitives together...

```
function CreateShip(const Owner: TComponent; const color: TCastleColor
  ): TCastleTransform;
var
  cf, cr: TCastleCone; b: TCastleCylinder;

  L, W: integer;

  procedure Setup1(const O: TCastleAbstractPrimitive);
  begin
    O.Material := pmUnlit;
    O.Color := color;

    O.RenderOptions.Blending := True;
    O.RenderOptions.BlendingSort := bs2D;
  end;
begin
  Result := TCastleTransform.Create(Owner);

  L := 40 * pxInMeter;
  W := 15 * pxInMeter;

  b := TCastleCylinder.Create(Owner);
  cf := TCastleCone.Create(Owner);
  cr := TCastleCone.Create(Owner);

  Setup1(b);
  Setup1(cf);
  Setup1(cr);

  b.Height := L;
  b.Radius := W;

  cf.BottomRadius := W;
  cf.Height := W;
  cr.BottomRadius := W;
  cr.Height := W;

  cf.TranslationXY := Vector2(0, -(L+W)/2);
  cr.TranslationXY := Vector2(0, +(L+W)/2);

  Result.Add(cf);
  Result.Add(cr);
  Result.Add(b);
end;
```

Then

```
  ......
  Viewport.Items.Add(MyCone);

  Ship1 := CreateShip(Self, Teal);
  Ship2 := CreateShip(Self, Silver);

  Ship1.TranslationXY := Vector2(-5000, -400);
  Ship2.TranslationXY := Vector2(2000, 1000);

  Ship2.Rotation.Init(0, 0, 1, pi);

  Viewport.Items.Add(Ship1);
  Viewport.Items.Add(Ship2);
```

Oooops!

`Ship2.Direction := Vector3( xxx, yyy, 0);` works - but in a counter-intuitive way totally unsuited to 2D

`Ship2.Rotation.Init` does not wotk at all! it just does not rotate its inner child nodes, whatever options i tried

**Comment by michaliskambi** [comment]
> The test shows, however, i actually have specify the rotation angle in Radians as Z parameter, and W does not matter.

As for the 3rd/4th component of 4D vector: Indeed, we just had an ordinary bug in `TGenericVector4.Init`, fixed now (and testcase added) in https://github.com/castle-engine/castle-engine/commit/c1dd9a943d9146b38514ca7d49e245e3eb6b676a

Moreover:

It likely went so long unnoticed because `TGenericVectorXxx.Init` is seldom used. 

In the case of your code, what you should use is `MyTransform.Rotation := Vector4(...)`, not `MyTransform.Rotation.Init(...)`.

The reasons for doing so are explained on https://castle-engine.io/coding_traps , and I have now extended the `Translation`, `Rotation`, `Scale` API docs to mention this explicitly too, with link to https://castle-engine.io/coding_traps . It's indeed a trap when dealing with record properties, one that you just have to be aware of.

This also likely resolves your later note _"Ship2.Rotation.Init does not wotk at all! it just does not rotate its inner child nodes, whatever options i tried"_.

> Note: the Rotation axis (first 3 components) must be non-zero - the wording is unlucky, it suggests that allthree of X, Y AND Z should be non-zero.

Changed to "the Rotation axis (first 3 components) must not be a zero vector"

> It seems the correct call (at least it does the tirck) is Viewport.Update but its parameters are not documented. Neither is documented .Render

These methods are part of TCastleUserInterface, they are documented there. See https://castle-engine.io/apidoc-unstable/html/CastleUIControls.TCastleUserInterface.html . Indeed, as we talked in another thread, eventually we'd like to show API docs better at descendants, this is in https://github.com/castle-engine/castle-engine/issues/177 .

Do not call them yourself, they are called automatically.

**Comment by the-Arioch** [comment]
>
> The reasons for doing so are explained on
> https://castle-engine.io/coding_traps ,
>

well, i found and used .Init exactly to avoid the trap of obj.record.field
:= ...

however, assigning the WHOLE record seems questionable performance-wise.
perhaps the record can exhibit .X/.Y/.Z properties WITH setters ?

yes, it may potentially lead to the same trap as .Init or any other method,
if "getter function" be introduced. But would you have to do so, you can
change the data type to be either a record pointer or an object/interface.

since Delphi (and i hope FPC too) now implicitly change recordptr.field
into recordptr^.field it should be source-compatible.

really, changing ALL the 4 properties, and those that would subject to a
rather costly normalization, when you only need to change an angle without
changing the axis, it seems a waist.

Also, just like you have .TranslationXY maybe there can be a special
reduced 2D version of rotation API

**Comment by the-Arioch** [comment]
> Do not call them yourself, they are called automatically.

They were not, so i had to call it manually. I'll check it again, but
i think there were not.

I'll check later if `Rotation := Vector4(...)` would act differently,
from `Rotation.Init`. Maybe indeed it was the difference that avoided
triggering invalidating/updating loop.
Though i also suspect there is some more function, GCE's analogue of
Applciation.Run that should had started rendering-updating loop, and
that i missed doing.
Maybe not, maybe LCL main message loop should be enough, will check.

That said, i still feel it some over engineering and loss to assign 4
components and additionally do some complex math on them, when you
actually just need to change an angle on the same pre-calculated
axis... It should be just one property, skipping axis re-calculation.

And 2D-friendly :-D

I also was changing .TranslateXY on those compound objects, and there
was no object move until .Render forced.
Do not have this code now, but AFAIR i used exactly that technic with
local Vector2 var read, modified and assigned back.
So i expected the rendered object to be moved automagically, but it did not.

will have to try again, and maybe did a minimized project. You never
know where a newb can find an opportunity to jump off the railroad :-)

**Comment by eugeneloza** [comment]
Quick note:

> I'll check later if `Rotation := Vector4(...)` would act differently, from `Rotation.Init`.

Yes, they will act differently. `Rotation.Init` shouldn't do anything. The issue is that when you ask for a `property` you receive either a pointer (for pointer-type objects) or copy of the variable (if it's not a pointer). The latter is the case for `TSomething.Rotation` - when you ask `TSomething.Rotation.Init` you get a copy of `Rotation` call `Init` on it and discard the result. `Rotation := Vector4(...)` is the correct way to operate non-pointer variables such as `TVector4`.

**Comment by the-Arioch** [comment]
Think about it from another andle too:  would my `.Init` actually work
on a temporary volatile copy, rather than the object's member var,
then no amount of ".Render" or ".Update" forced calls would not change
the visible picture.

If my changes had fallen into a temporary var - they'd be just lost.

But it was not so, the forced re-render DID change the picture,
implying i WAS changing the actual record not a copy.

**Comment by eugeneloza** [comment]
Interesting, indeed

```Pascal
program Project1;

{$modeswitch advancedrecords}

type
  Rec = record
    Value: Integer;
    procedure Init;
  end;

procedure Rec.Init;
begin
  Value := 10;
end;


type
  TA = class
  strict private
    FI: Rec;
  public
    property R: Rec read FI write FI;
  end;

var
  A: TA;
begin
  A := TA.Create;
  WriteLn(A.R.Value);
  A.R.Init;
  WriteLn(A.R.Value);
  A.Free;
  ReadLn;
end.
```

worked for me. Something I'd never expect :D And also happy that new Lazarus/FPC version doesn't allow `A.R.Value := 1` which was the source of so many of errors before.

**Comment by the-Arioch** [comment]
>  new Lazarus/FPC version doesn't allow A.R.Value := 1 which was the
> source of so many of errors before.
>

I think i heard newer Delphi banned it too, so FPC mode-delphi finally had
green light with it.

All in all, for high-level API complex properties better be TComponent or
Interface, while for low-level speed-bound they better be record pointers
rather than records. Having the best of both worlds so to say.

Win32 Delphi also has TP-like objects, that were sometimes used before
advanced records introduced, for example in mORMot lib. But i am not sure
win64 and LLVM Delphi have them still. Even mORMot eventually abandoned
them, despite being performance addicts.

>

**Comment by michaliskambi** [comment]
>  well, i found and used .Init exactly to avoid the trap of obj.record.field := ...

You are landing in the same trap using `Init`, I'm afraid. Using `Scene.Translation.Init` is not a reliable solution. 

It may work now (when `Scene.Translation` is directly backed by a field) but 

- there is no guarantee from CGE side (that we will not change some vector property to use a getter method). Some of our vector properties may use a getter method, some may use direct field access -- you should code to be prepared for any version.
 
- from what I know, there is no guarantee from Pascal/FPC/Delphi side that it will work, even if it stays a direct field access. At least I didn't ever see such guarantee in any docs.

> however, assigning the WHOLE record seems questionable performance-wise.
> perhaps the record can exhibit .X/.Y/.Z properties WITH setters ?

The record *has* X, Y, Z properties with setters. But you (may) modify a temporary result of a getter method.

Talking here about performance yields a usual question ( https://castle-engine.io/coding_conventions#_optimize_smartly_profile_optimize_where_it_matters_and_not_where_it_doesnt_think_about_smarter_algorithms_and_moving_cpu_work_to_gpu_to_get_big_benefits ) -- do you have a real-world application when this is causing a measureable loss of performance?

We use vectors internally throughout the engine and such property assignments are actually not that often, so it's not a problem. Neither is this in any practical application I saw. We do 100 things more expensive than all these vector assignments throughout a normal code :)

>  But would you have to do so, you can change the data type to be either a record pointer or an object/interface.

This advise is not applicable.

We use records, and properties of records, for good reasons -- passing around records is both most comfortable and efficient than passing classes, as I wrote in https://castle-engine.io/coding_traps .

We will not expose pointers to them, as it would prevent doing anything automatic in the setter.

Alternative classes to access them are already available (`TranslationPersistent`, `RotationPersistent`) where doing `TranslationPersistent.X := xxx` works OK. So this is done. We don't advise using this way to access vectors though -- as it's more consistent to just use vectors as records throughout your code, than thinking about 2 approaches to deal with them.

> They were not, so i had to call it manually. I'll check it again, but i think there were not.

`Update` and `Render` methods of TCastleViewport are absolutely 100% called automatically. Submit a testcase if they are not.

**Comment by the-Arioch** [comment]
`.Render` gets called if to use property setter instead of `.Init`

> We will not expose pointers to them, as it would prevent doing anything automatic in the setter

why??? setter is a setter! it is a function you call "by assignment"! Within that funciton you do whatever you want.

Changing a record property of read-field write-function kind from a record to a typed pointer to that record would not change that much source-wise for the object consumer. Even producing a local copy of record by assigning would probably only require adding one `^` char. 

Of course, if your record does not have an added "owner" or "OnUpdate" field it would not help much, as the record won't know whom to inform about changes.

---

Okay, aside from performance PoV, this also raises a question of boilerplate vs laconic code. And chances of stupid typos in boilerplate ( as the whole .Init funciton was victim of );

```
+++ var V: TVector4;
begin
+++ V := obj.Rotation;
  V.W := newRotationValue; // and why W? why not Z or Y?
+++ obj.Rotation := V;
end;
```

is just several lines (and error chances) more than

```
begin
  obj.RotationAngle := newRotationValue; 
end;
```

Can you do it for simplicity of use in 2D apps if nothing else?

[0001-Direct-access-to-rotation-angle.patch.gz](https://github.com/castle-engine/castle-engine/files/7982257/0001-Direct-access-to-rotation-angle.patch.gz)


P.S. I wish Delphi/FPC has more support for type inference and overloaded properties so this could would "just work" given a proper overloaded setter and getter functions...

```
var V: single;
begin
  V := obj.Rotation;
  V = V + pi * 0.2;
  obj.Rotation := V;
end;
```

**Comment by michaliskambi** [comment]
> >  We will not expose pointers to them, as it would prevent doing anything automatic in the setter

> why??? setter is a setter! it is a function you call "by assignment"! Within that funciton you do whatever you want.

That is right, let me correct my statement:

If we make `Scene.Translation` etc. as pointers, we could indeed make setters for fields (like X and Y within) that notify parent `Scene`. But that means that `Scene.Translation` is actually becoming equivalent to what we already expose: `Scene.TranslationPersistent`, which is instance of class `TCastleVector3Persistent`.

So we already have this... 

But using `Scene.XxxPersistent` and `TCastleVectorXxxPersistent` is not in general comfortable (although it indeed avoids the trap with records in properties). For the exact same reasons why we introduced vectors as records in the first place: You can copy around records, and it behaves naturally (you copy contents, not reference, when doing simple assignment), and you don't need to manage memory (create/free). Which is why we generally use records (like `TVector3`, `TVector4`) throughout CGE, and keep `TCastleVectorXxxPersistent` mostly to be able to easily expose it in inspector.

> Can you do it for simplicity of use in 2D apps if nothing else?

Maybe yes, though I'd expose it differently. For simplicity of 2D, I would rather expose Rotation2D that sets angle, and also sets axis to (0,0,1). Otherwise the `RotationAngle` is your patch would still be confusing for 2D people, as setting it would not do anything, as the axis remains as it was (and it is zero by default).

Il'l keep that mind. I didn't see much use for this in all 2D games we did with CGE, but if I'll see it could be useful more often I'll add it.

**Comment by the-Arioch** [comment]
> Maybe yes, though I'd expose it differently. For simplicity of 2D

1) It is not only for 2D, it is for every case where rotation axis is
stable, only angle is changing but not the axis. Half Life's "activate me
to see a movie" marks are an example, they always rotate (if rotate) around
vertical axis.

2) while "sets axis to (0,0,1)" would suit most 2D games, there
hypothetically can be 2D games with different axes positions. Pre-setting
axis is rather responsibility of some "comfort method" like .Setup2D

3) And even with default axes setup - the same question, why only that axis
of them all?

Here is the 2D classic - https://www.youtube.com/watch?v=JJR7ER4_jmk
See how the coin is rotating at 0:36 - it is not +Y axis! _Granted, that
more seems like changing sprites than real rotation, but that is
technicality_
At 2:04 you would see a turtle turning belly-up, again, due to hardware
restrictions it is just one time turn, made by sprite, but i think i played
platformer games, where enemies were falling from hights rotating over
left-to-right axis.

**Comment by the-Arioch** [comment]
All in all, it is about minimizing boilerplate (and associated risk of
typos) and about the code being documenting intention rather than
implementation details. If i do not want to change the rotation axis -
i should not be.

**Comment by michaliskambi** [comment]
The trap with `Scene.Translation.X := Scene.Translation.X + xxx` is now solved, in the sense: this and all other such constructs will no longer compile. 

And the `Init` method, just as all other methods that change current vector (instead of returning new value), is now deprecated. So `Scene.Translation.Init(...)`, while it will still compile, will make a clear warning.
