### ISSUE TITLE
Documentation: no mix for GCE and LCL forms

### ISSUE THREAD

**Issue by the-Arioch** [castle-engine/castle-engine#371]
https://castle-engine.io/manual_lazarus_control.php
https://castle-engine.io/apidoc-unstable/html/CastleControl.TCastleControlBase.html
https://castle-engine.io/apidoc-unstable/html/CastleWindow.TCastleWindowBase.html

As of now those pages suggest those forms/controls to be self-dependent and thus freely mixable in one project, depending on the specifc window needs.

However, actually each of those forms *require* a specific, closely bound `TApplication` implementation (on frm LCL or one from GCE).

It was said, those controls would not work properly with  "wrong" application class.

Which suggests - and it was confirmed - there is no way to mix both "bases" in one project. It has to be decided early on it either would be all LCL forms + control base, or it would be all CGE forms.

I think it has to be explicitly spelled in the three articles above.

**Comment by michaliskambi** [comment]
Indeed, I had an update of TCastleControlBase docs already planned. Done, https://castle-engine.io/control_on_form now describes everything.
