### ISSUE TITLE
Wish: make way for objects to have limited zooming factor

### ISSUE THREAD

**Issue by the-Arioch** [castle-engine/castle-engine#372]
The visible ('perseived') size of `TCastleScene` object is dependent upon

* distance from Camera, if perspective projection used
* ViewPort's settings, like setting `Viewport.Camera.Orthographic.Width` as compared to the actual "pixel" size of `TCasteControlBase` or `TCastleWindowBase`
* maybe some more factors

The resizing of actual window with fixed ViewPort dimensions could hypothetically be implemented as moving camera.

An object's visible size would then be decreased until it gets projected into a single pixel, or even made invisible dure to `TProjection.ProjectionFar`
In other direction, the visible size would infinitely grow, untill it becomes larger than the form (unless it gets clipped by `TProjection.ProjectionNear`)

----

I wish there would be a way for an object to set minimum and/or maximum visible size along X and/or Y coords (in pixels or, if possible, in mm of the physical display).

Such an object would not be clipped invisible when going out of "visible range of Z projection".
Such an object would never be renedered with visible size less than provided minimum.
Such an object would never be renedered with visible size more than provided maximum.
It's visible ('perceived') size would only be changing within that range, a la "arythmetic with saturation".
Default ranges to be -INF to +INF (or perhaps it would easier to have boolean properties, `.Check{Max|Min}Visible{X|Y}Size` );

Maybe such a "zoom limiter" has to be implemented as a custom `TCastleTransform` proxy, that can be applied on top of any `TCastleScene` and would somehow measure their X-span or Y-span and calculate scale modifier to override "normal" viewform-distance-to-scale logic.

The purpose would be to make objects, that do not represent in-the-game objects, but rather kind of GUI elements, are visual clues. Not some fixed specific class, but any of existing objects, like `TCastleCone`, etc.

Example: earhtquake markers, discs at https://forum.castle-engine.io/t/some-newb-questions/472/2?u=arioch
There is no point to make them represent some "real world" area, they only should mark the place for the user, so the goal is to have visible size easy to spot but not overlapping too much of background information.

Example: aircraft tokens at FlightRadar-like sites: https://www.flightradar24.com/54.99,34.37/8
They do not repesent actual colors or dimensions of the real vehicles, just the anchor easy to spot.

Example: Half Life Lost Coast demo had a special "backstage video" mode, in which many scenes have educational/documentary movies built-in. Those places were indicated by specific "not of this worls" objects, for example: https://www.abcgames.sk/udaje/screenshoty/1133/113369.jpg

It would make sense for such an element to be zoomed in some range, as player walks to or away. But only in some range. This token should be rendered large enough to be easily spot from a far no matter how far away player is. This token should not fill the whole viewport when player comes very close to activate it.

It would be good to have a way to denote such an object to the GCE like "render it always no matter the distance, render it no smaller that 50 px width, render it no larger than 250 px height"

**Comment by Kagamma** [comment]
What prevents you from finding screen coordinate of the 2D/3D position, then draw the "not of this world" object using the newly found 2D coordinate like every game engines out there?
Something like: `Position2D := (Viewport.Camera.ProjectionMatrix * Viewport.Camera.Matrix).MultPoint(Position3D).XY;`
And then render your object at Position2D, either via TCastleUserInterface descendants, or TCastleScene in a new Viewport (configure for 2D) on top of the current Viewport.

What we need is a function that conveniently returns screen position from a given 2D/3D position @michaliskambi I couldn't find any functions like that, maybe we should add it, something like like Unity's **WorldToScreenPoint** https://docs.unity3d.com/ScriptReference/Camera.WorldToScreenPoint.html

**Comment by the-Arioch** [comment]
> And then render your object

Not always good for the reasons `TDrawableImage` is generally discouraged in https://castle-engine.io/how_to_render_2d

`Something like:` already shows it is not immediately obvious even to seasoned devs.
Then we would have to account for "Screen coordinate" of the base viewport can be changing.

Also, it is not about "draw at coordinate", it is about "draw with some scale", automatically adjusting to the scale of the scene, but in a limited way.

You suggest me to create a separate Viewport, then move it relatively to base Viewport, then arrangge Z-Order so new ViewPort would be on top of old one, not the other way, and then...
...to manually calculate camera position in the new Viewport to mimic camera position in the base ViewPort.

It really does not sound so reliable...

Do you think the Half-life's cut scene activator was rendered outside of the main objects tree?
I really don't remember now how it behaved when some other object appeared in front of it, was it seen through or was it obscured normally.

This is interesting though per se, but seems independent on the idea to keep a object visual size in a given range (scaling manipulation).

**Comment by Kagamma** [comment]
>Also, it is not about "draw at coordinate", it is about "draw with some scale", automatically adjusting to the scale of the scene, but in a limited way.

That should be user's responsibility to add such logic (how object scale to the scene).

I personally don't see how the half-life cut-scene activator related to your 1st and 2nd examples, they behave exactly like normal (unlit) objects to me https://www.youtube.com/watch?v=hpq_22ZH3IU

**Comment by Kagamma** [comment]
Replica of 2nd example.
[map.zip](https://github.com/castle-engine/castle-engine/files/7921077/map.zip)

**Comment by the-Arioch** [comment]
i brought HL for example of the kind of objects and how they relate to user experience.

unlimited zooming in HL makes UX worse IMHO.

At your link, 5:56 - and the activator obscures a significant part of the scene. I think i remember there were activators that made me quickly run backword to see the cut-scene properly...

And at 5:17 one of right activators could easily obscure another (which is not easily visible already), if not for epcific manual tunning of their plane direction.

I'll look into your sample next weekend, thanks.

**Comment by michaliskambi** [comment]
I see here 2 (somewhat connected) desired features. I added `PositionFromWorld` to CGE, and made a demo in CGE  `examples/3d_rendering_processing/position_from_world/` that shows how to use this to achieve both features:

1. You may want to have an object within the existing 3D space (so that it can be rotated in 3D, is obscured by other 3D elements etc.) but keep "some control" over its size on the screen. That is what e.g. gizmos in CGE editor do (they also use `RenderContext.DepthRange` to be rendered on top, but this is unrelated).

    The solution to this is just to adjust the object scale, at runtime, depending on the projection.

    Using  new `PositionFromWorld`, you can easily calculate "how long is 1 unit in 3D on the screen" and thus adjust the scale of some TCastleTransform. The demo I mentioned above shows how. It comes down to these lines:

    ```
    { calculate SphereViewportPosition, position of the sphere middle in 2D viewport coordinates. }
    SphereWorldPosition := MainSphere.LocalToWorld(Vector3(0, 0, 0));
    SphereViewportPosition := MainViewport.PositionFromWorld(SphereWorldPosition);

    // ...

    { calculate Sphere1UnitSizeOnScreen, how large is 1 unit in 3D space around sphere, on the screen. }
    SphereWorldPosition1 := SphereWorldPosition + Vector3(0, 1, 0);
    SphereViewportPosition1 := MainViewport.PositionFromWorld(SphereWorldPosition1);
    Sphere1UnitSizeOnScreen := PointsDistance(SphereViewportPosition, SphereViewportPosition1);

    { use Sphere1UnitSizeOnScreen to keep the TextAttached size similar on screen,
      regardless of how far is the scene. }
    TextAttachedScale := 100 / Sphere1UnitSizeOnScreen;
    TextAttached.Scale := Vector3(TextAttachedScale, TextAttachedScale, TextAttachedScale);
    ```

    Note:: I do not want to add more specific things around this (like TCastleTransform.MinZoom, TCastleTransform.MaxZoom) to the engine core. Because I don't think we can implement such mechanism at engine level in a way that would be universally useful. Other engines also don't do this. New demo and `PositionFromWorld` allows you to easily implement it yourself.

2. As @Kagamma mentioned, if you want to make your object a UI element, you can just take the 2D coordinates of the 3D position and use it for TCastleUserInterface position.

    Using new `PositionFromWorld` makes is straightforward, and I also show this in the demo. It comes down to these lines:

    ```
    { calculate SphereViewportPosition, position of the sphere middle in 2D viewport coordinates. }
    SphereWorldPosition := MainSphere.LocalToWorld(Vector3(0, 0, 0));
    SphereViewportPosition := MainViewport.PositionFromWorld(SphereWorldPosition);

    { SphereViewportPosition is immediately useful to determine LabelAttached position }
    LabelAttached.AnchorDelta := SphereViewportPosition;
    ```

    (so `PositionFromWorld` and `SphereViewportPosition` are actually useful twice in this demo :) ).

Indeed, `PositionFromWorld` is similar to Unity `WorldToScreenPoint`. I chose the `PositionFromWorld` name, as it matches existing `PositionFrom2DWorld` and it inverts the `PositionToXxx` family of viewport methods.

![Zrzut ekranu z 2022-01-24 01-05-20](https://user-images.githubusercontent.com/1076978/150703973-c963631e-f082-44a7-9bb4-9dc1f7919a46.png)
![Zrzut ekranu z 2022-01-24 01-05-11](https://user-images.githubusercontent.com/1076978/150703977-f17385e4-b2f3-4d93-8727-ded71d4b0fb5.png)
![Zrzut ekranu z 2022-01-24 01-04-57](https://user-images.githubusercontent.com/1076978/150703978-eca13af6-1e1e-4db4-84e7-5b893376086a.png)

**Comment by michaliskambi** [comment]
Looking at @Kagamma demo code, I see we think similarly :)

The `TCastleViewport.PositionFromWorld` is basically a fancy way of doing `(Viewport.Camera.ProjectionMatrix * Viewport.Camera.Matrix).MultPoint(...)`.
