### ISSUE TITLE
Allows build-tool to generate map file for resources in data directory

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#375]
This will be helpful for future web target, as we may need to pre-download some resources before CGE app start.
The map file should be in JSON format, so it can be easily read by JS.

**Comment by eugeneloza** [comment]
I see `data\auto_generated\CastleDataInformation.xml` is already generated by `build-tool`. Is this is what is needed (just convert it to JSON) or something else?

**Comment by Kagamma** [comment]
I can't find any documentation related to it so I assume the tool doesn't support. If it is already supported then this issue can be closed :)

**Comment by michaliskambi** [comment]
Cool, so I understand existing `CastleDataInformation.xml` fullfills this need. Some information about it:

It is easiest to test it by doing

```
castle-engine package --package-format=directory --fast
```

inside any CGE project. This will create a directory like `<project-name>-<version>-<os>-<cpu>`, and inside you can find `data/auto_generated/CastleDataInformation.xml`. The relevant CGE unit to read it is `src/files/castleinternaldirectoryinformation.pas` . 

(pass `--package-name-no-version` also to have even more reliable directory name for scripts, without version number.)

This information is e.g. used by `CastleFindFiles` on platforms that don't expose a reliable way to enumerate/search data files, e.g. in Android assets. 

It's an internal thing, so indeed we don't document it in CGE manual or public API. Normal CGE users should not even need to know this file exists. But it will stay -- it works reliably, solves an existing problem. If the web target will use it too, then all the more reason to keep using it.

I would moreover suggest to read it, without converting to JSON. Both Pas2JS and WebAssembly hopefully have an XML-reading unit, so maybe we don't need to convert it to JSON, and can read it using CGE CastleInternalDirectoryInformation in all situations?
