### ISSUE TITLE
Type mismatch in castleimages_vampyre_imaging.inc

### ISSUE THREAD

**Issue by Free-Pascal-meets-SDL-Website** [castle-engine/castle-engine#378]
On compiling castle_base I get this error:

castleimages_vampyre_imaging.inc(180,42) Error: Type mismatch

The line of code is
`if not Img.SaveToStream(Ext, Stream) then`

Regards
Matthias

**Comment by michaliskambi** [comment]
This would indicate you have registered an old version of Vampyre packages, where the `TSingleImage.SaveToStream` is a procedure not a function.

The Vampyre in latest upstream, https://github.com/galfar/imaginglib , as well as version bundled in CGE, have `TSingleImage.SaveToStream` as a function that returns Boolean.

Did you install Vampyre library through some other means than by using version bundled in CGE? Can you upgrade that easily (to latest upstream) or just use our CGE version (by compiling it by Lazarus, following https://castle-engine.io/wp/2022/01/28/more-integration-with-vampyre-imaging-library-used-by-default-with-both-fpc-and-delphi/ )? I decided to just use in CGE Vampyre through regular LPK, `VampyreImagingPackage.lpk`, `VampyreImagingPackageExt.lpk`. But please describe your situation in more detail, CGE approach is not set in stone :)

**Comment by Free-Pascal-meets-SDL-Website** [comment]
I was wondering about the "conditional procedure". 

I installed vampyre via Lazarus' in-built Online-Package-Manager tool (Ctrl+Alt+O). I expected to get a quite recent version of vampyre and didn't check against other sources, it is version 0.80. - The versioning situation seems strange though for vampyre anyway: [https://github.com/galfar/imaginglib/tags](https://github.com/galfar/imaginglib/tags). Seems 0.80 is kind of a special Lazarus version, while it doesn't seem to be the most recent, although the version number suggests it.

Never mind, going to go for the shipped package with CGE anyway, just overlooked the fact it is there. :-) 

Thanks for the quick answer.

**Comment by michaliskambi** [comment]
OK! 

I will ping to update Vampyre in Online Package Manager then, to include the version with `TSingleImage.SaveToStream`. Otherwise, I understand this may be an easy trap for people who get Vampyre from OPM.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Great!
