### ISSUE TITLE
Only high(LongWord) variants of random64 /not high(QWord)

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#38]
While having "truly 64 bits" accuracy, our random64 function can return only high(LongWord) variants of 64-bit integer. This is caused by initializing the 64-bit seed by two sequential 32-bit seeds. However, knowing the first 32-bit seed we can always calculate the next one, they are not independent.
E.g. compare this to SysUtils.random(int64). As they have variable-cycling algorithm which is slower, they still are free from the problem of xorshift algorithm that two sequential seeds are not independent. Yes, they also do not have truly independence, but a higher degree of.
We're using a single-variable pseudorandom generation algorithm, which is while easier and faster, cannot provide for 64 bit diversity based on two non-independent 32 bit randoms.

There are few ways we can fix this:
1. Leave it "as is". There is actually no serious problem at all. The random is truly 64 bits, it just doesn't use all the possible variants of a 64-bit integer. And I can hardly imagine user ever experiencing two identical 64-bit random sequence probability of which is still determined by 32-bit random seed: 1/high(LongWord).
2. Modify the algorithm to use two independent seeds in case of 64 bit integer request. We shall fake 2-variable cycling algorithm for 64 bit randoms then, and also we shall avoid cycling the 32-bit seed twice (which is also no problem, actually).
3. Make a separate implementation of xorshift64 bit, the one I'm using to randomize and turn two 32bit randoms into a 64 bit one.

The easiest way to fix the issue (except not fixing it at all :)) is "3". We can easily get a 64-bit seed from randomize and turn random64 into a separate and semi-independent (but the initial random seed is the same) random algorithm. It will still reproduce the random sequence fine, however calls to random64 won't affect next values of random and vice versa.

**Comment by michaliskambi** [comment]
Ah, OK. I understand the problem, we actually only have 2^32 possible values for our 2^64 result.

I vote for the variant that is simplest to implement, and has the shortest resulting code:) This probably indicates the solution 1, to ignore the problem:) 

Unless we do have a real need for a better RandomInt64, in a real usecase. Without this "real usecase", I fear that the RandomInt64 implementation is turning into a complicated solution for a non-existing problem.

In other words, having a simple and maintainable code is also an important factor here. We want to have a simple code, and I think that we can sacrifice the perfect randomness of RandomInt64 in favor of a simple implementation. TCastleRandom should not be used for cryptographic purposes, so deviations from perfect randomness are OK.

Looking back, I would be even fine with the original TCastleRandom.RandomInt64 implementation "qword(Random32bit) or (qword(Random32bit) shl 32)". Although the result was always > High(LongWord). But in a perfect 64-bit random function, the chance of having a result <= High(LongWord) is incredibly small anyway (it is "1 / High(LongWord)"), so it was acceptable that our RandomInt64 never returned it.

**Comment by eugeneloza** [comment]
So... Then we're closing this issue untill requested :)
