### ISSUE TITLE
Zoom with center on current mouseposition

### ISSUE THREAD

**Issue by fliegermichl** [castle-engine/castle-engine#381]
I try to make an TCADNavigation which is at start an nearly exact copy of TCastleExamineNavigation (cadnavigation.pas)
castletest.lpr is an simple testprogram with ctmainform.*
I tried to change the function Zoom in a way that the zoom has its center on current MousPosition not Scenecenter.

[castletest.zip](https://github.com/castle-engine/castle-engine/files/8068618/castletest.zip)

**Comment by michaliskambi** [comment]
Fixed, thank you -- `TCastleViewport.PositionToCameraPlane` now changes value right after changing `Camera.Orthographic.Scale`, and your "zoom to mouse position" works nicely :)

More comments at related forum thread https://forum.castle-engine.io/t/zoom-with-center-on-mouseposition/521/4 .
