### ISSUE TITLE
documentation: specific coordinates of Plane ?

### ISSUE THREAD

**Issue by the-Arioch** [castle-engine/castle-engine#382]
https://castle-engine.io/apidoc-unstable/html/CastleScene.TCastlePlane.html

This object has .Size (which is a bit unexpected, in school we learnt planes were infinite :-) )

Seems the plane here is a small 2D (zero-thickness) box.  However, what should be the actual coordinates of the plane's "box" ?

Frankly, just like with default setting Orthographic Camera, i expected the plane to be [ 0; 0; Size.X; Size.Y] however my short (and maybe wrong) experiment suhhests it be rather [ -Size.X/2; -Size.Y/2; Size.X/2; Size.Y/2] wit (0;0) being the object's center rather than corner.

Anyway, it has to be documented

**Comment by michaliskambi** [comment]
Added docs. For better or worse, "plane" traditionally means a "rectangle, that by default can act as a floor in 3D" in 3D applications like Blender or Unity. So we're consistent with their naming.

**Comment by the-Arioch** [comment]
Frankly, i'd still - for redundancy and ease of consumption - added description in ` [ -Size.X/2; -Size.Y/2; Size.X/2; Size.Y/2 ] ` terms :-)
