### ISSUE TITLE
Dynamic Batching causes UI rendering issue in view3dscene

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#389]
I think this issue is caused by the engine and not view3dscene so I report it here.

Tested on 2 systems, with latest CGE & view3dscene source code:
- Windows 10, dual-monitor setup, with NVIDIA GeForce GTX 1650.
- Windows 10, 3-monitor setup, with NVIDIA GeForce RTX 2060.

Steps to reproduce:
- Open `dragon.json` from `demo-models`.
- Enable `Dynamic Batching`.
- Play one of it's animations.

![image](https://user-images.githubusercontent.com/7451778/162118355-476aed5a-bc0c-48a7-8285-d4ffd5a2dd17.png)

**Comment by michaliskambi** [comment]
Confirmed, I can reproduce with latest CGE on Windows 10, FPC 3.2.2, with `Renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2`.

Weirdly I could not reproduce it on 3 Linux machines (including one running on the same hardware as Windows above). So it seems Windows-specific, though it's almost for sure some issue with OpenGL rendering. Looks like Linux implementations do something different than Windows and it matters for this.

**Comment by michaliskambi** [comment]
Found the issue and fixed, thank you!
