### ISSUE TITLE
[Castle Editor on FreeBSD 13.1 with UHD Graphics 620] Previewing any asset breaks main design viewport (multiple TCastleControl sharing resources are problematic)

### ISSUE THREAD

**Issue by bbrtj** [castle-engine/castle-engine#391]
When I click on anything that the editor will preview (like a model or a image) the main viewport where all the scene UI and transforms are viewed is no longer functional. Moreover, it won't properly load png images after the first time, sometimes mistaking model textures for the actual png image.

Example:

When I first open the editor, I see this (which I call "main design viewport"):

![image](https://user-images.githubusercontent.com/44323413/168885209-b2eb1479-3e6b-4501-8435-76a066120cbe.png)

Then, I click on the background png image, and it is already broken:

![image](https://user-images.githubusercontent.com/44323413/168885402-f3214a9f-6072-4a41-b82a-3350f4cdcb61.png)

The main viewport stays the same, but when I close and open it again, I see this:

![image](https://user-images.githubusercontent.com/44323413/168885601-fb021bf0-ae4d-479a-b64f-09db2a838c73.png)

It sometimes starts to blink rapidly. I also have this little model that I can preview:

![image](https://user-images.githubusercontent.com/44323413/168885724-b0dd8ad7-fd50-42a0-ace9-74bd16245534.png)

And after previewing it, I *sometimes* can catch this very brief thing where a png image views the texture for my model for ~2 sec before going black:

![image](https://user-images.githubusercontent.com/44323413/168886205-53e466a2-4f58-48e1-ab20-141c336bbaf5.png)

When it breaks, the only way to fix it seems to be re-launching the editor.

This bug occurs pretty deterministically. I have compiled manually, commit `9b9077caeb7805fed8b45cefd91199faebe1b0b1`, FreeBSD 13.1

**Comment by michaliskambi** [comment]
The preview indeed uses a second OpenGL context (another instance of `TCastleControl`). They should not interfere though in any way (although we have a mechanism to cache the same textures between >1 OpenGL contexts, but it should not reuse resource when the texture URL is different).

Using the preview works OK for me, on Linux and on FreeBSD 13.0 (albeit in a virtual machine).

![VirtualBox_freebsd_17_05_2022_22_11_54](https://user-images.githubusercontent.com/1076978/168904061-08d7d38e-2392-43ec-bea7-35d7a34935b0.png)


It's tempting to blame here OpenGL driver. 

1. Please attach here the report of your system using "Help -> System Information", click on "Save To File" to save everything to a text file. 
2. If you have a choice between various GPU drivers, please test whether switching to a different one helps.

**Comment by bbrtj** [comment]
I tried recompiling GPU driver from source (which is drm-fbsd13-kmod), but it didn't help. I had the same driver before, but precompiled from repositories.

I can attach my system info but need more directions. I don't use any desktop environment, so you just have to point me to a command line tool that extracts the info you need. For the time being, I'll attach some of the info from `sysinfo` utility:
[info.txt](https://github.com/castle-engine/castle-engine/files/8711632/info.txt)

One more observation: after this problem occurs, I have this weird artifact that seems to happen every time. Basically one fourth of a screen has this overlay when I hover over it:
![image](https://user-images.githubusercontent.com/44323413/168913065-2d84f886-cca4-4166-978b-46e10557b8bb.png)

The game compiles and runs just fine, its just the editor that is having some difficulty. Could that be a problem with drivers nonetheless?

**Comment by michaliskambi** [comment]
> I can attach my system info but need more directions. I don't use any desktop environment, so you just have to point me to a command line tool that extracts the info you need. For the time being, I'll attach some of the info from sysinfo utility:

The "Help -> System Information" is a menu item in the Castle Game Engine editor that you're using :) See the https://castle-engine.io/wp/2022/04/16/2-big-features-in-progress-and-small-editor-improvements-available-already/ for announcement and screenshot how it should look.

Thank you for the `sysinfo` report, though this is not enough for us. The "Help -> System Information" reports exactly how does the editor "see" your OpenGL, it reports OpenGL version, features, and what they imply for CGE.

The other artifacts (white frame, black stripes) do suggest a problem with OpenGL drivers even more.

**Comment by bbrtj** [comment]
Ah sorry, I didn't know the editor has that option. Here's the result of saving to file:
[info.txt](https://github.com/castle-engine/castle-engine/files/8712076/info.txt)

**Comment by michaliskambi** [comment]
> Ah sorry, I didn't know the editor has that option. Here's the result of saving to file:

Thank you!

Hm, everything in the report looks mighty fine. 

- Good OpenGL version (4.6), no "buggy xxx" detected by CGE, everything is rendered using the shader pipeline that is fully tested and advised.

- Renderer is `Mesa Intel(R) UHD Graphics 620 (KBL GT2)` which matches the `sysinfo` report that said `device='UHD Graphics 620'`.

- You use advised latest stable FPC 3.2.2 and it is a regular FreeBSD on x86_64.

I'm stuck, admittedly. The report doesn't show anything unusual. And I do not reproduce this problem on my FreeBSD (13.0 FreeBSD, on x86_64, in a virtual machine) nor any other system. 

Hm. Sorry, I do not have a solution or way forward *yet*. It's tempting to just say "bad OpenGL drivers" but this isn't very helpful for you, I'd like to have some idea what to try / workaround anyway.

**Comment by bbrtj** [comment]
Thanks for verifing that nothing obvious is broken. I have some ideas on my own of what to try next. Keep in mind 13.1 is very fresh (2 days), so the problem may be either with the system or the way I upgraded major version (12.3 -> 13.1). I can't recall if I had this problem before the upgrade, so chances are it only started happening after the upgrade.

Could this kind of bug be an effect of outdated castle_components.lpk or castle_base.lpk? I'm not exactly sure when / how should I update them in lazarus and my installation is surely older than the last time they changed in the repository.

I also have an older computer laying around with FreeBSD / OpenSUSE dualboot so I will check if I can reproduce this problem there.

**Comment by michaliskambi** [comment]
> Could this kind of bug be an effect of outdated castle_components.lpk or castle_base.lpk? I'm not exactly sure when / how should I update them in lazarus and my installation is surely older than the last time they changed in the repository.

I doubt you actually have them outdated.

If you just updated the CGE repo, e.g. following https://castle-engine.io/compiling_from_source.php , then the LPK are updated too. They will be automatically recompiled when you recompile with CGE editor. (It doesn't really matter if you reinstalled them in Lazarus IDE.) And if you would have them too outdated, CGE editor would not even compile :)

Basically just doing

```
git pull --rebase
make
```

in CGE dir on Unix will rebuild everything correctly, including the Lazarus packages in CGE editor.

**Comment by bbrtj** [comment]
Just tried to narrow down when it goes wrong. Creating `TViewFileFrame` is fine, but assigning to its `Parent` property creates the problem. I think this is the moment when `TCastleControl` serialized inside `TViewFileFrame` enters the screen. Seems it is never deinitialized, just its `Enabled` and `Visible` flags get swapped.

So I added `FreeAndNil(ViewFileFrame);` to that code part where ViewFileFrame is hidden in formproject.pas, and it partially fixes the problem. I mean, when two of those TCastleControls are on the same screen, the artifacts are still there. But as soon as I click away from the file being previewed and the second control is destroyed, everything seems to be back to normal and I have no artifacts in the main design viewport.

**Comment by bbrtj** [comment]
I don't think that workaround should end up in main CGE repository, it helps me for now to have CGE editor usable on my system but it does not solve the problem. I guess if I wanted to create a lazarus app with two CGE controls I would end up with same artifact / broken view problem.

Lets just sit back and have this issue open. Sadly I don't know where should I report this, but chances are good people of FreeBSD will notice and fix anyway. Or maybe in the meantime I'll come up with a better workaround.

**Comment by michaliskambi** [comment]
> I guess if I wanted to create a lazarus app with two CGE controls I would end up with same artifact / broken view problem.

You can also write an application showing multiple `TCastleWindow` instances at once, and I guess the problem would also occur there. Interesting, you can test `examples/window/multi_window/multi_window.dpr` , it shows 5 windows, all within one application, managed by CGE (though the example doesn't display anything fancy, but one could extend it to load any design/3D model).

If the problem is reproducible there too, then at least we know it's not related to anything in LCL.

> Lets just sit back and have this issue open. Sadly I don't know where should I report this, but chances are good people of FreeBSD will notice and fix anyway. Or maybe in the meantime I'll come up with a better workaround.

Absolutely, and thanks for testing. Maybe a solution will come, in the meantime the ticket will stay open.

**Comment by bbrtj** [comment]
> If the problem is reproducible there too, then at least we know it's not related to anything in LCL.

Actually no, I compiled that example and loaded a castle-user-interface in each window - no artifacts at all:

![image](https://user-images.githubusercontent.com/44323413/169396963-8f920cc8-227b-4b2a-916c-ca085950e4d7.png)

**Comment by michaliskambi** [comment]
I updated to FreeBSD 13.1 on my (virtual) system, and it works OK. With FPC 3.2.2, Lazarus 2.2.2, x86_64. 

![VirtualBox_freebsd_22_05_2022_03_58_18](https://user-images.githubusercontent.com/1076978/169675094-c19f6e41-ea8a-4891-a7b6-d557d79570c7.png)

![VirtualBox_freebsd_22_05_2022_03_58_54](https://user-images.githubusercontent.com/1076978/169675095-3b259ae3-484f-46eb-9236-2a11598e1204.png)

**Comment by michaliskambi** [comment]
One idea: Since you build editor yourself, what widgetset are you using? 

Lazarus by default uses GTK2 widsetget on Linux and FreeBSD. Did you change it (e.g.to Qt?). Some widgetsets (in particular Qt)

**Comment by bbrtj** [comment]
I decided to rollback my update due to suspend/resume problems on 13, so I'm back on 12.3 (freebsd can rollback major version upgrades).

Just recompiled CGE and the problem is still here. So it indeed must be caused by another part of my setup.

> Since you build editor yourself, what LCL widgetset are you using?

I have this little script that I use to build instead of original `lazbuild`:

```
/usr/local/bin/lazbuild --ws=qt5 $@
```

I've made it a while ago because recompiling CGE with custom components used GTK instead of Qt. So I always compile with qt5 now.

**Comment by bbrtj** [comment]
Good call @michaliskambi, I tried compiling again but with vanilla lazbuild. And looks like it works:
![image](https://user-images.githubusercontent.com/44323413/169695962-07cc71bf-3f7e-4e9d-8747-7095d152975f.png)
I think the widgetset is gtk2 now, so it would mean qt5 control got this part wrong? Should I try compile with some other widgetsets?

**Comment by michaliskambi** [comment]
> /usr/local/bin/lazbuild --ws=qt5 $@

Aha! Then solved. LCL Qt widgetset doesn't support OpenGL context sharing (in `lazarus/components/opengl/glqtcontext.pas`, `SharedControl` is passed around but not used for anything). This exactly explains your issues.

It also explains why everything worked with `TCastleWindow` -- then we use our own OpenGL context initialization code, and we handle context sharing in all cases (although we don't implement Qt at all -- for FreeBSD we support GTK2 and Xlib).

Please build CGE editor with the standard widgetset, i.e. GTK 2.

I'm looking into how to solve this (it seems Qt, GTK3 and Cocoa LCL widgetsets all have this problem) -- and will most likely just submit a patch to LCL, it's easier to fix it on LCL side than to workaround in CGE (we rely on context sharing through our cache). For now:

- I extended our "System Information" to report the widgetset, so that we will notice in logs when someone uses non-standard widgetset :)

- In https://github.com/castle-engine/castle-engine/commit/3a7fc1b26551b7088eabcec8cca44e1f5e61e94f : I made the CGE compilation fail if you use widgetset that doesn't support sharing, you will get a message like this:

    `...frameviewfile.pas(20,4) Error: (2023) User defined: Do not use LCL Qt or GTK3 widgetsets to build CGE editor, as LCL TOpenGLControl doesn't support OpenGL context sharing in this case. Use LCL default widgetset instead, like GTK2.`

**Comment by michaliskambi** [comment]
> I think the widgetset is gtk2 now, so it would mean qt5 control got this part wrong? Should I try compiling with some other widgetsets?

Ah, I see you got the same conclusion while I was writing my post :) Yes -- Qt widgetset in LCL is at fault here. GTK2 widgetset will be fine.

**Comment by bbrtj** [comment]
I'm a bit confused though - when I open castle_editor.lpi in lazarus, the widgetset for the project is Qt5 as well. And when I compile with lazarus and not lazbuild, the issue still occurs. So following the manual (by opening lazarus and compiling there) still yields the same results.

So it's not like I changed how it compiles, I just made a script that helps me keep the same widgetset after recompiling the editor with custom components (because it uses lazbuild, and it uses gtk2 no matter what).

How come I'm the only one experiencing this? Does castle-editor compile with gtk2 by default, but somehow it chooses qt5 on my machine?

**Comment by michaliskambi** [comment]
> Does castle-editor compile with gtk2 by default, but somehow it chooses qt5 on my machine?

Hm, Lazarus (both when compiling from Lazarus IDE, and when compiling using `lazbuild`) should default to GTK2 (on FreeBSD and Linux). And it does for me -- I tested Lazarus from FreeBSD packages, then I switched to Lazarus just compiled from source (got Lazarus sources from GitLab, run `gmake`).

Did you maybe change the default widgetset in Lazarus IDE some time ago, and It was just saved in your user preferences?

How did you install Lazarus?

**Comment by bbrtj** [comment]
I've got stock lazarus from `pkg install`. It was installed last year, recently reinstalled due to problems after major version upgrade. I guess some configs could've stayed in my home directory, but I can't recall manually configuring widgetset.

![image](https://user-images.githubusercontent.com/44323413/169699088-4efddae7-087a-44f9-9f5f-90e2c6811ebb.png)

![image](https://user-images.githubusercontent.com/44323413/169699105-1f574729-2569-41fd-a639-c118119fb231.png)

I looked in lazarus configs but can't see widgetset configured anywhere. My `~/.lazarus/environmentoptions.xml` doesn't have widgetset in it either. Where else could it be configured?

**Comment by michaliskambi** [comment]
Hm. Weird.  I also installed Lazarus from `pkg` on FreeBSD. Using

```
pkg install editors/lazarus
```

and it tells me that `lazarus-gtk2` is actually installed. In all the windows you show, I have `gtk2` where you have `qt5` :)

What FreeBSD package did you use? Because https://wiki.lazarus.freepascal.org/Installing_Lazarus_on_FreeBSD says there's alternative `pkg install editors/lazarus-qt5` , which is naturally based on qt5.

**Comment by michaliskambi** [comment]
I have just now created a PR to Lazarus that fixes the underlying issue, allowing LCL `TOpenGLContext` (from which our `TCastleControl` descends) to share data. The PR is on https://gitlab.com/freepascal.org/lazarus/lazarus/-/merge_requests/95 .

Once this is applied to Lazarus, CGE editor will work just fine with Qt5 widgetset too :)

**Comment by bbrtj** [comment]
> What FreeBSD package did you use? Because https://wiki.lazarus.freepascal.org/Installing_Lazarus_on_FreeBSD says there's alternative `pkg install editors/lazarus-qt5` , which is naturally based on qt5.

Ah yes, totally forgot there's either lazarus-qt5 and lazarus-gtk2, not just lazarus :D okay mystery solved then, I simply installed lazarus-qt5

Editor looks much better with qt5, so I would prefer to use that, but gtk2 is good enough for the time being. Thanks helping me solve this!
