### ISSUE TITLE
GLInformationString

### ISSUE THREAD

**Issue by tomwiel** [castle-engine/castle-engine#395]
castleglutils_information.inc:
    {$ifdef OpenGLES} + NL +
    '  Max line width: ' + GetInteger(GL_ALIASED_LINE_WIDTH_RANGE)
corrupts the memory (2nd integer), because a pair (float, float) is delivered.

**Comment by michaliskambi** [comment]
Thank you! Fixed, I also made it queried on (desktop) OpenGL, and also query as 2 floats.
