### ISSUE TITLE
Can not setup required fpcupdeluxe on Windows 64 needed for Castle Android development

### ISSUE THREAD

**Issue by AndreMikulec** [castle-engine/castle-engine#396]
May somwone provide alternate instructions that do not require fpcupdeluxe to do Android development?

3.5. Install FPC for Android (using fpcupdeluxe)
https://castle-engine.io/android

I am not getting fpcupdeluxe to install in Windows 64bit.
This is my issue. Progress is very very slow.

fpcupdeluxe-x86_64-win64 stable/stable install error: revision.inc(1,1) Error: Identifier not found "release_3_2_2" #519
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/519

**Comment by eugeneloza** [comment]
Hello!

I skimmed your bugreport at FPCUpDeluxe - I think I've had the same issue. Running FPCUpDeluxe executable from shell helped me. I was using the one that comes with WinGit.

Alternative way is to setup cross-compilers manually. At some point Lazarus provided prebuilt Android cross-compiler, but I can't see it in the latest version. You can still go through by building your own cross-compiler https://wiki.freepascal.org/Android#Building_cross_compiler (it's complicated).

Third way (the easiest one, and the one I'm always using) is by using CGE docker images - where everything is already preinstalled and precompiled. See https://castle-engine.io/docker for details. Note that CGE image is large - around 20-25 Gb. You need to have that much to download and use the corresponding Docker image. It'll still take some time to learn to use Docker, but eventually it goes down to `docker container start cge` - `docker container exec cge sh /yourproject/buildscript.sh` - `docker container stop cge`.

**Comment by AndreMikulec** [comment]
@eugeneloza

Thanks for the excellent advice.  I am sorry about wasting your time.

The case ended up being that my  AVG Antivirus was blocking MAKE.EXE.
I created an exception in AVG to allow MAKE.EXE and everything worked fine.

(Closed)
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/519

Yes, these are excellent. I agree.

https://castle-engine.io/docker

Or
https://castle-engine.io/github_actions

I use Appveyor and Github Actions on other non-Pascal projects.

I am "new" to docker.

I am closing this ticket.

**Comment by michaliskambi** [comment]
Confiming what @eugeneloza said:

1. Docker is one option (it's also linked from https://castle-engine.io/android ). https://castle-engine.io/docker

2. Another option is to compile FPC cross-compiler yourself. You need

- The normal compiler (Win64->Win64) in your case.
- FPC sources. You can get them from GitLab ( https://gitlab.com/freepascal.org/fpc/source ) with appropriate tag, like 

```
git clone --depth 1 --single-branch --branch release_3_2_2  https://gitlab.com/freepascal.org/fpc/source.git
```

(I use `--depth 1 --single-branch --branch release_3_2_2` in above command to limit download to the subset of Git repo you really need. Look at https://gitlab.com/freepascal.org/fpc/source/-/tags to know what tags are available. )

- Build and install the compiler using

```
make clean crossall crossinstall OS_TARGET=android CPU_TARGET=arm CROSSOPT="-CfVFPV3" INSTALL_PREFIX=$HOME/installed/fpc/android
make clean crossall crossinstall OS_TARGET=android CPU_TARGET=aarch64 INSTALL_PREFIX=$HOME/installed/fpc/android
```

(from our old docs, https://github.com/castle-engine/cge-www/blob/master/htdocs/doc/obsolete/android_old_notes.adoc ).

**Comment by michaliskambi** [comment]
Ah, my answer was a few minutes too late :) Happy to see this is resolved.
