### ISSUE TITLE
[minor] Castle-Editor question "Rebuild with custom components" doesn't have a taskbar button

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#397]
Sometimes it's a bit inconvenient, e.g. if other window is on top - there is no way to bring this one back up except for minimizing/closing all other windows.

![2022-07-14-184116_1366x768_scrot](https://user-images.githubusercontent.com/10726162/179022568-81509990-1570-45ec-af3d-4b7922440a3d.png)

**Comment by michaliskambi** [comment]
I see you use XFCE. 

1. I wonder is the same problem on Windows? 

2. We had to set `ShowInTaskBar` to `stAlways` on various forms in editor, possibly this is also necessary on dialog forms. But we use standard LCL `MessageDlg` for this question, like

    ```
    MessageDlg('Question', Message, mtConfirmation, [mbYes, mbNo], 0) = mrYes
    ```

    So it would be a pain to change it -- we would have to fork implementation of `MessageDlg`. Alternatively, we could submit patch to LCL to add such option to `MessageDlg`.(But it's probably uneasy, API of `MessageDlg` has already a number of parameters, and it should be Delphi-compatible probably.)

3. I don't see a problem on GNOME 3, but it doesn't mean much :) There's no default panel on GNOME 3. I use https://micheleg.github.io/dash-to-dock/ , but it's still not a regular application list like XFCE panel. However, it shows CGE editor application as active during this dialog box.

![Zrzut ekranu z 2022-07-14 18-55-38](https://user-images.githubusercontent.com/1076978/179037529-ec89bb87-3c88-42c6-b118-d9f58dd7d29b.png)


To be clear, you can still access the modal box using Alt+Tab? It's just not present on the task bar at the bottom?

**Comment by eugeneloza** [comment]
Yeah, the same issue on Windows:
![cge-editor-on-windows](https://user-images.githubusercontent.com/10726162/179349593-a95e8caa-68e5-468b-830a-52ea606b0016.png)
