### ISSUE TITLE
Issue with 2 viewports in design file

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#402]
See attached project. It throws `EBox3DEmpty` exception if I run the app.
![image](https://user-images.githubusercontent.com/7451778/184655267-aaadc2a2-ccee-4b93-b783-16bdff229c0a.png)
Some insights:
- If I remove Viewport1, then it loads fine.
- castle-editor has no issue loading the file.

Test on Windows 10 with NVIDIA RTX 2060 graphics card

[test.zip](https://github.com/castle-engine/castle-engine/files/9337816/test.zip)

**Comment by michaliskambi** [comment]
Thank you, fixed!
