### ISSUE TITLE
Request "forward compatibility" context to get latest OpenGL version on macOS

### ISSUE THREAD

**Issue by Lykdraft** [castle-engine/castle-engine#409]
_System: Desktop MacPro OSX 10.15 Catalina (and  Macbook Pro 10.14 Mojave)_

Hey there.

`Rendering Initialized: OpenGL 2.1`

Huh..?  :D  I took a screenshot, let me know what you think...

Best,
tL

![scnGGE1](https://user-images.githubusercontent.com/18437561/199089284-a2854b13-b760-49c3-a323-5e5da4122ae0.png)

**Comment by eugeneloza** [comment]
Quick duckduckgoogling hints it's a MAC-specific issue:

"_glxinfo goes through the X11 server. The OpenGL support of the X11 server which is shipping with OS X is rather limited._" (from https://stackoverflow.com/questions/18141327/open-gl-version-2-1-instead-of-3-2-on-os-x-10-8)

https://stackoverflow.com/questions/63129097/open-gl-version-2-1-instead-of-4-1-in-mac-os-10-15

**Comment by Lykdraft** [comment]
Yeah. Ok, I get it. But it seems to me that it is only CGE-specific. *Not* a mac-specific issue.
(I.e.: When I use GL3 in Godot, it *will* use GL3, or specifically GL3.3. Godot has 2 options, you know... GL2 or GL3.

And when I check the GL3 option, then the log will show GL3. Not GL2, or GL2.1.  It doesn't. Others use GL4.x, but I can't remeber which. (By the way: Apple has canceled OpenGL altogether, so this is a moot point anyway... We need to go  Vulkan/MoltkenVK/WGpu/etc. for Mac anyway sooner or later... ) 

Also my 2c: I can't stress enough: CGE is the last on my long, looong list of Game Engines.
And I had no problem at all with anything before. Just with CGE.  

Best,
tL.

**Comment by eugeneloza** [comment]
Indeed. What I've meant is that it looks like CGE issue with MAC (or even with certain versions of MAC) to be more specific :) It's not only CGE's issue (these issues don't make it to StackOverflow yet :D), but just others have already fixed this issue.

And indeed there was a mention that upgrading to Metal on MAC is beneficial. However, upgrading a rendering backend is a huge task, while fixing how Open GL works - I'm not sure of it's complexity, but most likely easier than implementing a new renderer. And while indeed Open GL is deprecated on MAC (long ago) they don't seem to rush removing its support altogether in any foreseeable future, so for now it should be safe enough to stick with Open GL (see e.g. https://github.com/castle-engine/castle-engine/issues/230#issuecomment-735498808).

**Comment by Lykdraft** [comment]
Ah, okay. Yeah, I understand now. That might be the thing. 

Best,
tL.

**Comment by michaliskambi** [comment]
1. Long story short: Ignore it. The fact that on macOS you see "OpenGL 2.1" reported doesn't have any adverse effects.

    CGE will function as usual, and when needed (but we generally don't need them for "normal stuff") will access optional functionality from higher OpenGL versions through extensions.

    If you actually miss something from documented CGE functionality, or something behaves worse or slower than on equivalent systems with Linux/Windows, of course please report it :) But everything should really work the same.

2. Longer explanation: Apple decided (as usual...) to do things in a way that is somewhat incompatible with other platforms. Namely, they give us OpenGL context with version > 2.1 only if we request "forward compatibility context". And for historic reasons, CGE doesn't request "forward compatibility context" -- although we *almost* can, as *almost* everything would work well (except last bits of shadow volume implementation that should be updated, we have a PR for this already). But we didn't finish it, because, again, there are no practical adverse effects of this.

    See https://www.khronos.org/opengl/wiki/OpenGL_Context and all it's mentions of Apple specifics:

    > Platform Issue (MacOSX): When MacOSX 10.7 introduced support for OpenGL beyond 2.1, they also introduced the core/compatibility dichotomy. However, they did not introduce support for the compatibility profile itself. Instead, MacOSX gives you a choice: core profile for versions 3.2 or higher, or just version 2.1. There is no way to get access to features after 2.1 and still access the Fixed Function Pipeline.

    > Recommendation: You should use the forward compatibility bit only if you need compatibility with MacOS. That API requires the forward compatibility bit to create any core profile context.

3. I'm renaming this ticket. Following the above recommendations, we should

    - request forward compatibility bit on macOS
    - (and fix the shadow volume rendering first, to make sure forward compatibility bit is OK)
    - and then we will see later OpenGL version.

    But I emphasize: There are no practical bad effects of current state as of now. Just keep using CGE as usual, everything will work :)

4. Note, addressing some additional things you discussed above:

    - We don't use glX to access OpenGL on macOS, not anymore :) We use Cocoa, we initialize OpenGL context using NSOpenGLContext.

    - As for Apple warning developers that they will deprecate OpenGL (and OpenGLES): I'm watching what happens.

        It would be a bummer if they actually choose to do it, i.e. if Apple will make Metal the only "official" API on macOS/iOS and remove OpenGL/OpenGLES. While it may be possible to add Metal renderer to CGE, it would be a significant work, and this significant work would benefit only Apple platforms. I would much rather spend time e.g. on Vulkan renderer (that can work everywhere, Linux, Windows, Android, Nintendo Switch... except on Apple).

        That said, CGE would be then in a similar situation as a lot of other software. In particular, Apple's own Safari, that has to support WebGL, would be in a similar situation. To support WebGL in an easy way, they need the system to support OpenGL or OpenGLES. Or an abstraction layer, that provides OpenGL/OpenGLES API on top of Metal *without causing any noticeable speed loss*. And actually there is such layer already: https://github.com/kakashidinho/metalangle, part of ANGLE already.

        So, if Apple really removes OpenGL/OpenGLES from their devices at some point, our first course of action will be to use ANGLE. And we'll be in good company, along with lots of other software, including likely Apple's Safari.

**Comment by Lykdraft** [comment]
> Short answer: Ignore it. The fact that on macOS you see "OpenGL 2.1" reported doesn't have any adverse effects.

Will do. :) 

> But I emphasize: There are no practical bad effects of current state as of now. Just keep using CGE as usual, everything will work :)

Yes, I also thought that this is not really an urgent thing that must be solved.

> We don't use glX to access OpenGL on macOS, not anymore :) We use Cocoa, we initialize OpenGL context using NSOpenGLContext.

That's good to know. Thanks.

> It would be a bummer if they actually choose to do it, i.e. if Apple will make Metal the only "official" API on macOS/iOS and remove OpenGL/OpenGLES. 

Yeah, I think so, **too.**

> While it may be possible to add Metal renderer to CGE, it would be a significant work, and this significant work would benefit only Apple platforms. I would much rather spend time e.g. on Vulkan renderer (that can work everywhere, Linux, Windows, Android, Nintendo Switch... except on Apple; I mean, it can work through a layer like MoltenVK, but not directly).

Good thinking regarding Vulkan. I think other devs/people are moving also to solutions 
that bypass the openGL/apple debacle and solve universally other problems with other backends. (i.e.: WGPU in Rust)
 

>  our first course of action will be to use ANGLE
That would also be a good thing. I have heard this on the libGDX dev-forum also a few times.


Anyway, thank you for your time and the clear explanation. ;)

Best
tL.

**Comment by michaliskambi** [comment]
Note:

1. This task is in progress. I'm working on https://github.com/castle-engine/castle-engine/tree/shadow-volumes-new branch that, despite the name, feature a number of generally-useful improvements to our rendering code. Most of all, our rendering code can use modern OpenGL 3.3 "core" profile, without any deprecated bits, which means that we will be able to request _forward-compatible context_ on macOS.

2. Also, I converted my answer "what will happen if Apple will deprecate OpenGL (and OpenGLES)" to a section in our docs, https://castle-engine.io/macos#_apple_says_that_opengles_is_deprecated_what_happens_if_they_remove_opengles_from_macos_and_ios , since it is rightfully an often-asked question by people interested in macOS / iOS + CGE.

**Comment by michaliskambi** [comment]
We now use "core" OpenGL profile, both with TCastleWindow and TCastleControl, on macOS by default. So in your applications, as well as in CGE editor, you'll see later OpenGL version. (I got 4.1.)

Attaching a few screens :) 
![Zrzut ekranu z 2023-02-20 02-10-56](https://user-images.githubusercontent.com/1076978/220009876-b3759e86-0762-4e80-93e3-18b8a58a4415.png)
![Zrzut ekranu z 2023-02-20 02-11-38](https://user-images.githubusercontent.com/1076978/220009880-5e57ac6f-a14a-435a-b464-a09ba6acd9d5.png)
![Zrzut ekranu z 2023-02-20 02-14-50](https://user-images.githubusercontent.com/1076978/220009885-6eb3dd5e-af68-477b-9026-8a94b02ee7d8.png)
![Zrzut ekranu z 2023-02-20 04-42-52](https://user-images.githubusercontent.com/1076978/220009886-575bc03f-4ee4-441c-a76c-ccc6f49f04f6.png)
![Zrzut ekranu z 2023-02-20 05-23-48](https://user-images.githubusercontent.com/1076978/220009892-7f3a605b-e552-4510-bb83-c4650a38974a.png)
![Zrzut ekranu z 2023-02-20 05-24-20](https://user-images.githubusercontent.com/1076978/220009894-cced9694-dc32-47db-b459-57b4e12b39aa.png)
