### ISSUE TITLE
Build Tool: After one of the package commands for Linux target executable remains in the project folder

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#412]
I didn't test which exactly `package` command creates an executable (build Linux archive or Debian package), but one of them doesn't clean up after itself, most likely the Debian one.

![Executable-remains-after-package](https://user-images.githubusercontent.com/10726162/201229378-ddcd57ee-cc6c-438d-9c39-d05eb4e24bef.png)

**Comment by michaliskambi** [comment]
The `package` definitely leaves the executable lying, as `package` executes `compile` as the first step in normal circumstances:

```pascal
      if Command = 'package' then
      begin
        if not AssumeCompiled then
        begin
          if not Fast then
            Project.DoClean;
          Project.DoCompile(OverrideCompiler, Target, OS, CPU, Mode, CompilerExtraOptions);
        end;
        Project.DoPackage(Target, OS, CPU, Mode, PackageFormat, PackageNameIncludeVersion, UpdateOnlyCode);
      end else
```

So before `package`, we do

- `clean` (unless `--assume-compiled` or `--fast`)
- `compile` (unless `--assume-compiled`)

And this actually OK IMHO. "package" does "compile", and as a result overwrites your executable.

Do you have an example workflow when this actually a problem?

**Comment by eugeneloza** [comment]
It's not an actual "problem". Just a bit unexpected end state ("dirty") after packaging. E.g. after running a package script (e.g. this one https://gitlab.com/EugeneLoza/vinculike/-/blob/grandmaster/docker.sh) I end up with... some executable for some OS. Only now I realized that I already delete `castle-engine-output` manually in the end.

**Comment by michaliskambi** [comment]
> Only now I realized that I already delete castle-engine-output manually in the end.

If you cleanup using `castle-engine clean`, it will clean both executable(s) and `castle-engine-output`.

In general, I'd say this is acceptable. `package`  does `compile`, and so it creates the executable. There's no compelling reason to delete it automatically, IMHO, when you can do `castle-engine clean`. We do not want to hide the fact that `package` does `compile` (e.g. we make no effort to save your previous executable).

Note that, if you want to really build and have an unmodified project dir, then use --output option, like

```
rm -Rf /tmp/temp-cge-output
mkdir /tmp/temp-cge-output
castle-engine xxx --output=/tmp/temp-cge-output
# get from /tmp/temp-cge-output what you need
rm -Rf /tmp/temp-cge-output
```

**Comment by eugeneloza2factor** [comment]
Ok, 1.5 years later I've finally gotten to actually implement this in my script :D And it works almost perfect except for DLLs which stay in the project folder even if the output folder is specified explicitly.

Before build:

![dockerbeforebuild](https://github.com/castle-engine/castle-engine/assets/73470521/e04da36b-0eb2-4c81-941d-b9741aef09b3)

After build:

![dockerafterbuild](https://github.com/castle-engine/castle-engine/assets/73470521/cfd2c43c-e4f9-422e-a9e2-deecb52e93df)

**Comment by michaliskambi** [comment]
> And it works almost perfect except for DLLs which stay in the project folder even if the output folder is specified explicitly.

Fixed in https://github.com/castle-engine/castle-engine/commit/ec8555c7209d044c32c50b67be7c429fbf751f1f , thanks!

So now:

```
$ cd ~/sources/castle-engine/castle-image-viewer

$ mkdir -p /tmp/o

$ castle-engine package --fast --os=win64 --cpu=x86_64 --output=/tmp/o

$ ls *.dll
ls: cannot access '*.dll': No such file or directory
# good, no DLLs in project dir

$  ls /tmp/o/
castle-engine-output                        
castle-image-viewer.exe  
zlib1.dll
castle-image-viewer-2.0.0-win64-x86_64.zip  
libpng14-14.dll
# good, all DLLs in dir specified by --output, alongside EXE
# zip file also contains both DLLs and EXE correctly
```
