### ISSUE TITLE
Obsolete link to GLSL documentation

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#42]
http://michalis.ii.uni.wroc.pl/cge-www-preview/x3d_extensions_screen_effects.php
GLSL documentation leads to obsolete page
http://www.opengl.org/documentation/glsl/
Looks like the correct link is
https://www.opengl.org/sdk/docs/man4/index.php
However, they've merged API and GLSL documentation.

**Comment by michaliskambi** [comment]
As a sidenote, it's a little unfortunate how they describe GLSL.

- The merge of GLSL and OpenGL references is uncomfortable for shader authors.

- And there seems to be no good official webpage describing "what is GLSL" in simple terms. There is https://www.khronos.org/opengl/wiki/OpenGL_Shading_Language , but it's a bit hard to read. I don't think it's useful to people who don't have any prior knowledge about "shading languages"...

The only good description of GLSL that I know of, right now, is inside the GLSL specifications. But these are only in PDF formats, and they are different for every GLSL version, so I don't want to directly link to it.

**Comment by michaliskambi** [comment]
Thank you! I have updated the docs. The http://michalis.ii.uni.wroc.pl/cge-www-preview/x3d_extensions_screen_effects.php will reflect the GIT state shortly:)
