### ISSUE TITLE
[Editor] Minor issue: Empty window in GTK2

### ISSUE THREAD

**Issue by bbrtj** [castle-engine/castle-engine#426]
I'm having a small issue with the editor ever since I fixed my from-source compilation to use gtk2 instead of qt.
For a long time I've been seeing an empty half-transparent window when:
- castle-editor is first run
- castle-editor is recompiled with custom components

The window contains nothing and I have to manually close it for the editor to actually open. Seems like it will hang on it indefinetly:

https://user-images.githubusercontent.com/44323413/208679399-c76e77d3-bbd5-4650-bd92-d490eebb1e91.mp4

My environment is Lazarus 2.2.2 (qt) on FPC 3.2.2, FreeBSD 12.3 and X.Org with suckless dwm. This did not happen when I was compiling with qt widgets on the same env.

**Comment by michaliskambi** [comment]
Thank you -- I'm not reproducing it, but I have a different setup (Linux, FPC 3.2.2, X with GNOME 3). 

I'll try to reproduce it by making environment closer to yours :)

Off the top of my head, I don't have an idea what this transparent empty window could be.

**Comment by bbrtj** [comment]
If it helps at all, the window disappears after ~20-30 sec. When I see this window, castle-editor command is seen on htop, and it shows quite high resource usage (up to 45% of my CPU). Once the window disappears, CPU usage drops to 0 and process id stays the same.

**Comment by bbrtj** [comment]
I think this is a splash screen. I get this in other gtk2-lazarus programs as well. This is not a proper bugtracker for this report, sorry for confusion.

**Comment by michaliskambi** [comment]
Thanks for coming back to this. Sorry I didn't have time to investigate it more after the initial attempt.

Note that CGE editor doesn't show any splash screen (instead, our initial window to "choose project" should display ultra-fast). But I understand you suspect some general (outside of the control of our application) splash screen being added always to all GTK2 applications?

Note: In the long run, we'll have to move away from GTK2, I know :) It is deprecated and slowly gets removed from various distros. I am looking at various options.

- Ideally, Lazarus LCL could have stable GTK3 (or even GTK4) backend.
- It is also possible we could switch to Qt. 
    - The major issue with Qt LCL backend, from what I see, is that it requires libqtpasXXX installation (on each user's system), which would also cause a number of reports from users who don't have it. Though this problem could be "offset" by providing an easier installation way for CGE (e.g. using Snap on Linux, FreeBSD ports etc.).
-  Reimplementing CGE editor using our own UI is very much on my mind lately. It would give us some big gains (independence from GTK2 / Qt, but also CGE editor that can work on web in the future). But also it comes with some big obstacles to defeat (it's a big work, for starters; and it will not look native, and it will take time to make it look "close enough to native"). 

Comments welcome :)

**Comment by bbrtj** [comment]
@michaliskambi 

> But I understand you suspect some general (outside of the control of our application) splash screen being added always to all GTK2 applications?

Definetly, it's something that every lazarus gtk2 app I compile has. For Lazarus, I have its own splash screen and this empty window both at once and they both disappear at once.

> It is also possible we could switch to Qt. 

I like qt5 looks and would rather use it, but there's this problem: https://github.com/castle-engine/castle-engine/issues/391
Looks like your MR was merged, so once it gets released (if it wasn't already) it would be ideal option for me personally.

> Reimplementing CGE editor using our own UI is very much on my mind lately. It would give us some big gains (independence from GTK2 / Qt, but also CGE editor that can work on web in the future). But also it comes with some big obstacles to defeat (it's a big work, for starters; and it will not look native, and it will take time to make it look "close enough to native").

If you mean developing CGE editor using CGE UI controls then it seems like a really big endeavor. I used some textfields in my project and they are very raw as of now. They would have to be improved substantially to be sufficient. Well, at least they would be really polished after that :)
