### ISSUE TITLE
[Editor] Undo (Ctrl+Z) does not work when an input is focused

### ISSUE THREAD

**Issue by bbrtj** [castle-engine/castle-engine#428]
Ctrl+Z does not undo when an input (on the right, for example Translation) is focused.

It isn't a problem by itself. A bigger problem is that whereever I click (when I last focused such input), the input is automatically focused. Same when clicking Ctrl+Z - it also focuses the last modified input, so it often isn't possible to undo twice in a row. So maybe it shouldn't autofocus the input? Don't know.

I'm compiling from source, currently at commit 15d1d20519ce656067472ff427cb1407c3ca39f9. 

To reproduce: open any project in the editor, open a design, click a label, click on its "caption" property. Then move it around a couple of times, and try to undo those edits by clicking Ctrl+Z repeatedly.

**Comment by michaliskambi** [comment]
Reproduced and fixed, thank you!

When restoring the design (which happens e.g. after Ctrl+Z, but also after e.g. stopping physics simulation) we indeed focused the edit, using `ActiveInspector.SetItemIndexAndFocus`. Part of it was useful -- selecting last selected property is useful -- part of it not (making it focused isn't useful, as we may even focus something that wasn't in focus). We now reliably focus the `CastleControl`, thus making repeated Ctrl+Z work always.

Thanks as always for precise bugreport!
