### ISSUE TITLE
[Editor] Translation from Layout tab does not work

### ISSUE THREAD

**Issue by bbrtj** [castle-engine/castle-engine#429]
This translation property does not work. The object's position is updated, but as soon as I click away (so that the object is no longer selected) it is reset to its initial position (before editing).

![image](https://user-images.githubusercontent.com/44323413/209437993-934c77bf-83d0-4890-a54b-08c6cbf2ced6.png)

Same `Translation` property from `All` tab works fine. Other properties does not seem to suffer from this (tested `Center` and `Scale`)

**Comment by bbrtj** [comment]
Actually, it works now. Maybe a temporary bug. Will close and reopen if I reproduce it again.

**Comment by michaliskambi** [comment]
If it occurs again, let me know. There really should be no difference in how `Translation` works, regardless of on which tab it is visible :)
