### ISSUE TITLE
Strange problem with 2D games using TCastleCollider

### ISSUE THREAD

**Issue by Freedomax** [castle-engine/castle-engine#454]
![GIF 2023-02-22 08-52-36](https://user-images.githubusercontent.com/26040454/220493146-0cba7fa9-dae7-4a98-a40d-75717a2ed416.gif)

No collision occurs when Size.Z of `TCastleBoxCollider` is 2.
When Size.Z is 4, the previous one is directly passed through.
So, what is the recommended minimum Size.Z?

test case:
[test-collider.zip](https://github.com/castle-engine/castle-engine/files/10799030/test-collider.zip)

**Comment by michaliskambi** [comment]
1. For 2D games, when you typically operate on units like "a few thousands", the recommended sizes in Z start from 10, and generally are "as large as possible". Even Z = 1000.

    This isn't any hard rule, because it has to be chosen experimentally -- unfortunately underlying physics engine may indeed ignore collisions when 2D objects are too thin. On the other hand, things will also go wild if you specify too crazy size in Z, like 1000 * 1000.

2. But what I *really* want to recommend is "let AutoSize = `true` on collider".
 
    ( Though I know it currently behaves poorly when model is animated and you toggle AutoSize in editor -- it will use bbox from current animation frame, when you set `AutoSize`. ) 

    I have improved now the way it works. It will use `TCastleCollider.AutoSizeMinThickness2DDepth`, which is 100, as box collider size in Z.
