### ISSUE TITLE
Internal error occured = build + renenerate project

### ISSUE THREAD

**Issue by e1e5en-gd** [castle-engine/castle-engine#461]
If you run the build (for example, for Android), and during execution click _Code_ – _Regenerate Project (overwrites LPI, DPR, DPROJ, CastleAutoGenerated)_. Then we get an error.
![image](https://user-images.githubusercontent.com/7114353/223105555-46e91527-f86d-4b4d-96c6-6a51634ce60d.png)

There is not enough additional checking or locking of the button when performing the operation. At the same time, the assembly continues, but the user does not want to see it. =)

**Comment by michaliskambi** [comment]
Fixed, thank you!
