### ISSUE TITLE
The object is not drawn when the value Material := pmUnit is set for AMD graphics cards

### ISSUE THREAD

**Issue by e1e5en-gd** [castle-engine/castle-engine#462]
**Sequence:**
1. creating an empty project;
2. add a `Viewport (2D`) to the `Group` (`TCastleuserInterface`), or separately add a camera and an object, for example, a `TCastleSphere`. The object (plane or sphere) has the value `Material := pmUnit`.

**Problem:**
When using an Nvidia graphics card, the object is visible in the preview mode on the camera and is visible during compilation. If an AMD graphics card is used (in particular, I have a built-in `AMD Ryzen 7 4800H with Radeon Graphics` processor), then the object is not displayed.
The screenshot shows that the display takes place in the editor, because it uses an Nvidia graphics card. And the compiled project does not show anything, because it uses an AMD graphics card.
![image](https://user-images.githubusercontent.com/7114353/223344870-54258000-1db3-4c9c-b0a1-1b895e718ec6.png)

**Note:**
If you disable the `RenderOptions` – `PhongShading` option in the object settings (set to `false`), then the object is displayed.

**Materials:**
- project: 
[my-new-project-2d-camera.zip](https://github.com/castle-engine/castle-engine/files/10906212/my-new-project-2d-camera.zip)

- log: 
[my-new-project-2d-camera.log](https://github.com/castle-engine/castle-engine/files/10906213/my-new-project-2d-camera.log)

**Comment by e1e5en-gd** [comment]
I noticed another difference in running on different video cards:
- when running on the built-in AMD graphics card, by default, the limit is set to 60 frames per second;
![image](https://user-images.githubusercontent.com/7114353/223396649-af851bdd-8929-42ef-a5c7-ad08d5e7ea51.png)

- when running on an Nvidia video card – 30 frames per second.
![image](https://user-images.githubusercontent.com/7114353/223396670-fed79189-0f58-456a-9032-5ca711ebd550.png)

**Comment by michaliskambi** [comment]
Great news - I was able to get my hands on a machine with ATI GPU where I can reproduce this :) Unlit object can disappear, gizmos in editor disappear (connected older bugreport: https://trello.com/c/QH9d9A8o/92-bug-unable-to-see-and-use-gizmos ).

Will work on fixing this ASAP. 

Note that the FPS being "locked" to 30 on Nvidia GPU (that you mentioned in the comment) is likely something unrelated, and specific to the Nvidia graphic card preferences. (you can maybe tweak it using "Control Panel" or such.) I cannot reproduce this limit (on Nvidia or ATI cards), but it's also definitely not coming from CGE (we have no limit to 30 or 60 anywhere in code; we only have Application.LimitFps at 100 by default.)

**Comment by michaliskambi** [comment]
Fixed :) 

As usual, the fix is committed and pushed to GitHub "master" branch, and it will be available ina few hours in downloads on https://castle-engine.io/download .
