### ISSUE TITLE
Calling `glGetError` results in full CPU usage

### ISSUE THREAD

**Issue by Freedomax** [castle-engine/castle-engine#468]
Recently, I found that my game cpu usage has always been 10%, and it used to be below 2%. 
By backtracking the git commit, I found https://github.com/castle-engine/castle-engine/commit/fd8aae2b43dace96358c5f4a64c1d18b9bb6e6ef, which led to this result.
My game calls this every frame (since I'm passing the position of the light on the character to the shader).

```
procedure TGLSLUniform.SetValue(const Value: TGLint);
...
begin
 ...
  if GLFeatures.Shaders then
  begin
    glUniform1i(Location, Value);

    {$ifdef CASTLE_WORKAROUND_KNIGHT}
    ErrorCode := glGetError();
    ...
    {$endif}
  end;
end; 
```

**Comment by michaliskambi** [comment]
An update: I spend time investigating this today, to find the reason *why* I needed that `CASTLE_WORKAROUND_KNIGHT` workaround, IOW why sometimes some `glUniform1i` that pass texture to sampler fail.

Bisection easily shows that this commit is the fault: https://github.com/castle-engine/castle-engine/commit/42f78b0ea892209bb4a9c414a72f52ad43871461 . Which makes sense, i.e. this commit indeed changes stuff that could affect OpenGL commands correctness. I experimented with simple fixes (adding `ActiveTexture(0); glClientActiveTexture(GL_TEXTURE0);` to `ViewportRenderBegin/End`) but no success so far.

But I'm likely close to fixing this, commit https://github.com/castle-engine/castle-engine/commit/42f78b0ea892209bb4a9c414a72f52ad43871461 isn't that big to analyze and break down. Stay tuned :)
