### ISSUE TITLE
Unused units in 3d_sound_game

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#47]
https://github.com/castle-engine/castle-engine/tree/master/examples/3d_sound_game seems to use 2 unused (and inexistent) units gamesounds.pas and thunder.pas in Project Inspector (contained in `.LPI` file).
![2017-02-26-150617_1366x768_scrot](https://cloud.githubusercontent.com/assets/10726162/23352916/8ea26f34-fcd2-11e6-805d-74cea7e03776.png)

**Comment by michaliskambi** [comment]
Removed them from lpi, thank you!
