### ISSUE TITLE
Errors compiling on Delphi 10.2.3

### ISSUE THREAD

**Issue by limelect** [castle-engine/castle-engine#475]
On D10.2.3
I added
type
  PUint32        =  ^ Uint32 ;
On Dom.pas
line 558   FreeAndNil(Child);
[dcc32 Error] dom.pas(558): E2197 Constant object cannot be passed as var parameter

Could not compile base

**Comment by phomm** [comment]
Probably line 545 could be changed to not have 'const':
procedure TDOMDocument.AppendChild(const Child: TDOMNode);
and corresponding declaration if needed

**Comment by michaliskambi** [comment]
Thank you for the report! That particular `FreeAndNil(Child)` in DOM unit should not be there at all.

As I don't have access to Delphi 10.2 (only 10.4 or 11.x), I will need your help with testing :) 

I have pushed now 2 fixes related to this issue to branch delphi-10-2 in GitHub, https://github.com/castle-engine/castle-engine/tree/delphi-10-2 . Can you check out that branch from GitHub, and see if it compiles with Delphi 10.2 or are there further errors? Just testing by compiling packages + `examples/delphi/vcl` should be enough.

If this is good, I'll merge it to master branch of CGE and then it will be available in downloads on https://castle-engine.io/download . But let's test from branch first.

**Comment by limelect** [comment]
Compile OK
could not install base

![Screenshot - 27_04_2023 , 19_22_21](https://user-images.githubusercontent.com/4199131/234927742-82692906-5e3f-4a57-a9af-e8f11e8c1203.jpg)

**Comment by limelect** [comment]
I closed Delphi and reopen
Now a new error before the above
![Screenshot - 27_04_2023 , 19_29_37](https://user-images.githubusercontent.com/4199131/234929405-48fc3aa2-644a-454c-be09-f52e3bb677c0.jpg)

**Comment by michaliskambi** [comment]
Hm, we don't have any reference to `inflateValidate` in our code, including in our DLLs. And our DLLs (including `zlib1.dll` are all optional -- if they are missing, we just don't use them). Actually we only ever open `zlib1.dll`, not `zlib.dll` as in your message.

The only explanation I have is that you have in your system (in Delphi directory, or in Windows directory) a `libpng*.dll` that is being accessed by CGE, and it links to `zlib.dll` but you have outdated (incompatible) `zlib.dll` version. The issue may be unrelated to Delphi version in this case, just to something you have installed in your system.

Please search your system (Delphi installation directory, and Windows directory like `c:/windows/system32` and `c:/windows/syswow64`) for files matching `libpng*.dll` and `zlib.dll`. My current guess is something (unrelated to CGE) installed one them, something else installed/updated the other, and now you have 2 DLLs that are incompatible. With CGE we distribute compatible libpng and zlib (see https://castle-engine.io/compiling_from_source.php#section_Windows ) but in case we're installed in Delphi IDE, it shouldn't matter, we don't need to use these DLLs at all.

**Comment by limelect** [comment]
I got one error on d10.2.3
compile deprecated_space_filling_curve OK
Run error
on unit CastleInternalFreeTypeH;
line 526
    FreeTypeLibrary := TDynLib.Load('freetype.dll', false);

![Screenshot - 29_04_2023 , 09_42_24](https://user-images.githubusercontent.com/4199131/235288032-a64eec84-3856-4165-8e6e-c11c55f52c4e.jpg)

**Comment by limelect** [comment]
If i **nil** problem line (just for testing) then i get a new error
on unit X3DNodes;.pas line 814    FontsInitialization;
  DefaultFontData[ffTypeWriter, true , true ] := TextureFont_DejaVuSansMonoBoldOblique_20;
![Screenshot - 29_04_2023 , 09_50_25](https://user-images.githubusercontent.com/4199131/235288380-05c604c6-d60d-41a7-b2c3-3674ef3f2489.jpg)

**Comment by limelect** [comment]
F7 shows
![Screenshot - 29_04_2023 , 09_57_36](https://user-images.githubusercontent.com/4199131/235289370-620ea4c2-56f3-4daa-b663-37790d009302.jpg)

**Comment by michaliskambi** [comment]
> Run error
> on unit CastleInternalFreeTypeH;
> line 526
> FreeTypeLibrary := TDynLib.Load('freetype.dll', false);

This is the same error, missing `inflateValidate` in `zlib.dll`.

As nothing in CGE looks for `inflateValidate` and we don't even open `zlib.dll` (we only open `zlib1.dll`), my suggestions from https://github.com/castle-engine/castle-engine/issues/475#issuecomment-1526523852 still stands -- search your system (Delphi installation directory, and Windows directory like `c:/windows/system32` and `c:/windows/syswow64`) for files matching `libpng*.dll` and `zlib.dll`. Looks like something installed DLLs that don't play well with each other.

Also, try placing proper DLLs in the directory of the example you build. 

1. The simplest way to do this is to compile the example once using CGE editor. It can use Delphi or FPC for compilation, doesn't matter -- at the end it will copy proper DLLs alongside your EXE.
2. Or manually copy all DLLs used by CGE into your example folder (from https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/external_libraries/i386-win32 or https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/external_libraries/x86_64-win64 , depending on whether you target win32 or win64).

**Comment by limelect** [comment]
OR drop the whole thing which means I am not going to use it. too much of a headache.
I am a Delphi prof since Delphi#1
see my site www.limelect.com you will find there many free goodies. All work flawlessly

**Comment by michaliskambi** [comment]
I understand time is limited. Still, if you want to retest it please report. I believe both things I suggested (check your system for faulty zlib.dll, compile example once to place proper DLLs) are quick to do.

You can also download and run one of our ready games, like https://castle-engine.itch.io/platformer . See if it works for you (if yes, then it means you really should do what I suggest above -- you missed adding DLLs to the examples you compiled).

I have merged the changes to make it compile with Delphi 10.2 . If anyone would like to confirm it works for the  I'll be grateful.
