### ISSUE TITLE
Delphinius doesn't support 11.3CE (10.4.2CE too I guess)

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#479]
I noticed when trying 10.2.3 that Delphinius locates your Installed Delphi versions then the installer says it's building your package - that threw up a big concern (CE has no DCC)

Sure enough attempting an install results in...

![d11 3ce](https://user-images.githubusercontent.com/1549219/236960175-15db1307-7043-4be0-9f7d-0eba9c519f28.png)

Note that no Delphi is found even though you can see it behind the dialog

There is a solution and that's to build the release 32 bit package from castle_engine.dproj then install it (note release - not debug unless you're modding the component - on advice from @JimMcKeefe when writing about P4D). When doing this you get a nag dialog...

![d11 3ce-license](https://user-images.githubusercontent.com/1549219/236960707-a61a2cb5-ecd4-4546-b71a-ffaa82fb3aa1.png)

Once installed in the palette you have a component but nothing will compile as it stands. You have to supply those castle paths I noted in Discord. After that Windows 32 and 64 will now compile (without nag-dialog - poss only happens on package install?)

Hey presto...

![test](https://user-images.githubusercontent.com/1549219/236960985-3eae255d-f900-46e7-8d92-6b898c65a687.png)

[The empty spaces are where the Steam version displays info - wasn't feeling that brave]

**Comment by michaliskambi** [comment]
I guess this limitation of CE is not possible to avoid when using Dephinus Websetup, the Delphinus docs ( https://github.com/Memnarch/Delphinus/wiki/Installing-Delphinus ) state also :

> **If you have a Professional Edition or Higher**, you can simply use the Webinstaller from my Blog: [Delphinus](http://memnarch.bplaced.net/blog/delphinus)

(emphasis mine).

One "solution", as you mention, is just to not use Delphinus -- and install `castle_engine.dproj` manually. And then indeed you need to add paths manually, which is a pain, and we want to avoid it.

So another solution, and I would recommend this, it to install Delphinus in Delphi by getting Delphinus sources, and install Delphinus package in the Delphi IDE. I documented this procedure at https://castle-engine.io/download#delphinus , under the sentence _"Alternative way is to install from sources (it’s really straightforward, no worries)"_.  This approach should work in Delphi CE.

I updated the text on https://castle-engine.io/download#delphinus to clearly state that you need to use this way to install Delphinus in Delphi CE. I don't think we can do more about it.

( Please note that I want to have CGE available in GetIt at some point too, so this will be another alternative to Delphinus. We'll see which will be better :) For now Delphinus is our best way to install CGE components in Delphi. )

**Comment by peardox** [comment]
For RELEASE versions...

Delphinuis creates BPL etc files so it should be fine to compile a 11.3 package and release those vvia GetIt which is also available in CE

For GIT the paths could be set via a little app that could be included that writes the required paths to Registry - that's not too hard to do (I wrote most of such an app for P4D purposes)

**Comment by michaliskambi** [comment]
> Delphinuis creates BPL etc files so it should be fine to compile a 11.3 package and release those vvia GetIt which is also available in CE

Indeed.

> For GIT the paths could be set via a little app that could be included that writes the required paths to Registry - that's not too hard to do (I wrote most of such an app for P4D purposes)

I'd say to use Delphinus for this. The less we need to maintain in CGE, the better -- we don't want to maintain in CGE a code to manipulate Delphi settings, when Delphinus can already do it. Delphinus is exactly doing this already. And it can remove the paths (when uninstalling) and update the paths (when upgrading).

**Comment by peardox** [comment]
OK, a slightly better idea - looking at Delphinus.Install.json all the required info is in there in the search_pathes (mis-spelling per json) key. That could be used as a source of data for an app that simply adds or updates the Delphi registry so only that needs maintaining.

The keys that need updating are the [platform] keys in "HKCU\SOFTWARE\Embarcadero\BDS\[verkey]\Library\[platform]\Search Path"

This simply needs performing iteratively on all sub-keys [verkeys above] of verkey (or specific ones I guess) with the benefit that it'd fix path for both the unsupported CE and 'real' Delphi versions

P4D used an IDE plugin for the same thing - way too much work + compiler specific...

An additional comment here is that the delphi dproj should ideally specify Release as the default build on load.

If these were done then install instruction for Delphi would simply be build + install castle_engine.dproj then run the included fix_paths application

Also - known bug with Delphinius - https://github.com/Memnarch/Delphinus/issues/85 - it wil not install in C:\Program Files (x86)\Delphinius - annoying and may confuse some ppl...

**Comment by michaliskambi** [comment]
> The keys that need updating are the [platform] keys in "HKCU\SOFTWARE\Embarcadero\BDS[verkey]\Library[platform]\Search Path"

While it is a possible solution for the future, for now I would not want to maintain this in CGE. It would be yet another thing to maintain, and experience shows these things are always harder to maintain than they seem to make :), esp. once we need to support all promised Delphi versions and their CE/non-CE variants, and Embarcadero could change things between Delphi versions and we'll have to test and adjust...

Let's leave modifying Delphi settings to Delphinus and GetIt (which bring additional benefits -- uninstall, upgrade, extra exposure of CGE to new people). They already do a good job of it :)

For Delphi CE and Delphinus, I don't see the solution with "install Delphinus from sources" as a big deal. It's not as comfortable as "just run Delphinus Websetup" but it's also not much work, and we document it clearly on https://castle-engine.io/download#delphinus .
