### ISSUE TITLE
CGE doesn't compile with Delphi 10.0.1

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#486]
Basically this one is identical to XE7 when breaking - just 10.1 to do and either that or 10.2.3 will be the lowest currently supported version

**Comment by michaliskambi** [comment]
Same as https://github.com/castle-engine/castle-engine/issues/482 :

> Thank you for testing -- for now I say to officially cut these older Delphi versions. The effort isn't really trivial, as any special hacks would need to be maintained / tested, and the usefullness for users is anyway not big -- since non-Windows platforms would not be supported with these older Delphis anyway, so the big CGE feature "cross platform" would not in practice be relevant for people with these old Delphis.
