### ISSUE TITLE
CGE doesn't compile with Delphi 10.1.2

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#488]
Errors...

Once again...

  {$warn COMBINING_SIGNED_UNSIGNED64 off}
##############################
Assertion type mismatch

  function StackTipCalc(const Angle: Single): TVector3;
  begin
    // Result := Vector3(0, Cos(Angle) * SkySphereRadius, 0);
    { simpler and more accurate version, since StackTipCalc is only called with
      Angle = 0 or Pi }
    if Angle = 0 then
      Result := Vector3(0,  SkySphereRadius, 0) else
    begin
//      Assert(Angle = Single(Pi)); // <- This Assertion fails
      Result := Vector3(0, -SkySphereRadius, 0);
    end;
  end;

##############################
Result assignment causes type mismatch

function SpecularFactor(const M: TMaterialInfo): TCastleColorRGB;

Result :=
MaterialSpecularColor *
(Node.FdIntensity.Value *
  Power( Max(TVector3.DotProduct(Normal, CameraAndLightHalfway), Single(0.0)),
	MaterialShininessExp));
##############################

It is notable that 10.1.2 still uses Interbase XE7 so making XE7 or XE4 work seems the most cover for the least hassle

**Comment by michaliskambi** [comment]
Same as https://github.com/castle-engine/castle-engine/issues/482 :

> Thank you for testing -- for now I say to officially cut these older Delphi versions. The effort isn't really trivial, as any special hacks would need to be maintained / tested, and the usefullness for users is anyway not big -- since non-Windows platforms would not be supported with these older Delphis anyway, so the big CGE feature "cross platform" would not in practice be relevant for people with these old Delphis.
