### ISSUE TITLE
Wrong buttons position in the html font example

### ISSUE THREAD

**Issue by tsr8** [castle-engine/castle-engine#49]
There is a bug in the castle-engine/examples/fonts/html_text.lpr
Buttons are in wrong positions. This is possibly caused by TCastleButton that don't recalculate button width when caption has changed.

**Comment by michaliskambi** [comment]
Fixed, thank you!

(The sizes are recalculated, but are available in `TCastleButton.CalculatedWidth`, while `TCastleButton.Width` stays unchanged. I changed this during CGE 6.0 development, and forgot to fix all cases.)
