### ISSUE TITLE
Suggestion : Delphi Spcific Tool

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#493]
Firstly - this suggestion is only for simplifying Delphi CGE end-users installation process. It is not great for library devs.

With #492 there now exists the possibility to install Packages for all currently supported Delphi versions (10.2 to 11.3 inc CE). The contents of this PR are path-agnostic but source-unaware.

I've now identified the final steps in this task - making the PR source-aware. My definition of Source Aware in this context relates to enabling Delphi to find the Declaration of a CGE method etc from within the IDE which is a useful feature.

Delphi has it's own "Environment Variables" (stored in the registry under a key of that name) - adding / changing one is therefore easy enough. I intend to add a new such key called CGE_BASE (??) which will point at the CGE root

Anoither important registry key is Library - there exists one of these for each platform (I'll check whether un-installed platforms are defined soon). A subkey of this is "Browsing Path". This is where Delphi gets it's "Find Declaration" etc functionality from. Adding $(CGE_BASE)\\src\\subdir (quite a lot) to "Browsing Path" therefore supplies Delphi with the data it needs.

Lastly each main installed version of Delphi (e.g. 10.2, 10.3, 10.4 + 11) have their own keys that contain the above sub-keys meaning each Delphi is isolated from the others (only applies to those of us with multiple installations of course). Note that it is not possible to have both the CE + full Delphis for identical or sub-releases (10.2 + 10.4.2CE are fine but  11.2 + 11.3CE are not for example - wierd major version numbering...)

Bearing all the above in mind a tool can be written that makes the proper registry entries for all installed versions of Delphi including the CE versions Delphinius doesn't support (which undoubtably will be a large percentage of users)

While I'm fully capable and willing of writing such a tool the simplest (personal use) method is a registry hack - it's how I'll test before writing anyway.

The exact same tool may also be capable of generating GetIt a package - or at least a helper for it (where is the documentation on GetIt - can't find it... Googling "delphi getit package manager" results in a load of junk)

Another addition to this idea is that it could auto-generate the dpk, drpoj etc needed by #492

Finally I could have the option to add the path to the "Search Path" key. This would act in the same way as current (Delphinius dow#es this but without shortening paths via an "Environment Variable")

Everything will be properly documented and tested on all applicable Delphi versions.

One question
---
If I recurse thru src/ there will be some directories I don't want (internals etc). Is there a list of these? Or possibly the reverse - a list of must haves? JSON would be nice... Ideally have an option to include internals for lib devs?

**Comment by peardox** [comment]
Well #487 informs you that Delphinius does NOT handle upgrade, or uninstallation and also doesn't even recognise CE (likely a large portion of Delphi users).

The GitHub for Delphinius has not been updated in ages, last commit = Dec 3, 2020  so things happening upstream seem unlikely.

**Comment by peardox** [comment]
Delphinius needs to support CE in some manner - even if it's just to set the registry entries. As it doesn't support 11.3 CE at all I've only been able to test on full Delphis

Maybe it should be available via GetIt (a wierd idea - use one package manager to install another) specifically for CE?

Being able to write its own "Environment Variables" would also be good to enable shortening paths to e.g. $(CGE_BASE)

**Comment by peardox** [comment]
Not tried compilation within CE, it's not exactly highlighted - if this works a section on usage with CE is essential as otherwise people won't try it (I only tried Websetup and I know what the problems are...)

I'll go save my CE and load a previous (wish we had git for VMs...) clean version - more info after I give it a go

**Comment by michaliskambi** [comment]
> Not tried compilation within CE, it's not exactly highlighted - if this works a section on usage with CE is essential as otherwise people won't try it (I only tried Websetup and I know what the problems are...)

The https://castle-engine.io/download#delphinus says _" Note that the Delphinus Websetup cannot work Delphi Community Edition (free), so if you use Delphi CE — use the installation from sources described below."_ .  We talked about this before, I added this explicit sentence as a result of our talk :)

**Comment by peardox** [comment]
The sentence implies that Delphinius won't work with CE - I'm investinating (note in Discord with current thinking on the subject)
