### ISSUE TITLE
Delphi 10.2.3 package error

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#496]
And this worked before...

src/compatibility/delphi-only/URIParser.pas

function EncodeURI(const URI: TURI): String;

First error - line 89
> Result := Result + InternalURIEscape(URI.Path, ValidPathChars);

[dcc32 Error] uriparser.pas(89): E2034 Too many actual parameters

**Comment by peardox** [comment]
Oh, crap - you've altered https://github.com/castle-engine/castle-engine/blob/master/src/files/castleuriutils.pas 3 hours ago (guess that's the issue then)

**Comment by michaliskambi** [comment]
Ups! Yes, thanks, fixed.
