### ISSUE TITLE
(waiting for Delphinus fixes) Delphinius Install wastes 1.5G+ of disk space

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#497]
See grab below

The only folders _REQUIRED_ for package installation are src and packages (44MB). The pointless file copies also take some time which makes installation appear far slower than it actually needs to take. It's gotta recurse thru every single dir + file after all to get all the stuff that you should ideally immediately delete when it's finished

![del](https://github.com/castle-engine/castle-engine/assets/1549219/3e2477fa-d8bd-4de4-b858-ce9290e1aa8c)

**Comment by michaliskambi** [comment]
This waits now for Delphinus:

- We need Delphinus to be able to install CGE packages ( https://github.com/Memnarch/Delphinus/issues/93 )
- We need Delphinus to be able to download CGE ( https://github.com/castle-engine/castle-engine/issues/84 )

Once this works, we can make a best decision what to copy with Delphinus. This depends on whether we consider our main Delphinus use-case "people download and install CGE using Delphinus" or "people use Delphinus to install in Delphi CGE that they already have downloaded". For now neither option works with Delphinus, let's wait.

**Comment by peardox** [comment]
IMHO this is unlikely to be resolved any time remotely soon as Delphinius has 30 issues and 5 prs going back to 2017 with no new commits in 943 days (basically, the same situation as a few months ago)

Getit, OTOH, is already possible from my tests
