### ISSUE TITLE
Report : Deliberately installing wrong package for Delphi Version

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#499]
This was completed using the main repo's Delphinius, Reults will differ if using #492 or [split-delphi-design-time-package](https://github.com/castle-engine/castle-engine/compare/split-delphi-design-time-package)

These resaults _may_ look good but that would be a misconception. The end result is a working system _but_ this is entirely down to Delphinius either doing wrong things or possibly being misconfigured. Delphinius creates a Comps/castle-engine/lib folder that contains the correct DCUs for the _correct_ version and additionally a source folder that is set in Search Path. The end result of this is that CGE will be compiled in its entirety each time. If the lib folder was in Search Path then no re-compliation would be required (but then again this test would fail as well)

Methodology
---------------
I took clean installations of both 10.2 and 10.3 - these being about the only things installed in seperate VMs. Both systems had CGE added via Delphinius. The resulting Dcp, Bpl and Comps folders were then copied out to host allowing transfer back in to other hosts.
By doing this the system is able to artificially have the 10.2 package installed in 10.3 (which was the requested test)

Once this was done a very simple test VCL project (as per Discord, but modified somewhat to allow testing with/without component - will GitHub the source later...)

Results....

Starting Delphi with the wrong package
![badbcp](https://github.com/castle-engine/castle-engine/assets/1549219/f38ff808-5567-4227-babc-c22aae744907)

Attempting to load simple CGE test project
![projload](https://github.com/castle-engine/castle-engine/assets/1549219/68b0f390-fa13-4b9a-ae82-3e50b2e42b43)

Compiling and running CGE test project (only works owing to complete library compilation)
![projrun](https://github.com/castle-engine/castle-engine/assets/1549219/7bf0f477-8505-41e9-8b60-1d30eca465d5)
This seemingly successful resault was achieved with runtime control instantiation and is functional owing to complete library compilation. This project also has a TCastleContol which Delphi removed (runs by virtue of instantiation at runtime)

There is of course no Palette entry for the component.

If source were unavailable this wouldn't run (i.e. via the other eperimental builds mentioned above)

**Comment by peardox** [comment]
Test code - simple but useful

https://github.com/peardox/CGEFormTest

**Comment by michaliskambi** [comment]
Thank you - so when loading incompatible package, Delphi just says "Can't load package ... The specified module could not be found." . 

Let's move the conclusions to https://github.com/castle-engine/castle-engine/pull/492 that sparked this question.
