### ISSUE TITLE
CastleRandom warning

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#50]
I've got a warning on compiling `CastleRandom` unit:

`...castle-engine/src/base/castlerandom.pas(170,12) Warning: (5066) Symbol "GetTickCount64" is deprecated: "to measure time, better use Timer + TimerSeconds or ProcessTimer + ProcessTimerSeconds"`

Actually `GetTickCount64` is a good method to get a "very" accurate amount of CPU ticks (we need it to initialize random as fine as possible and getticksount is the best candidate). However, if you intend to remove  `GetTickCount64` from CGE, maybe, I should change it to freepascal's `GetTickCount` (AFAIR they also have a 64 bit version, which we, actually would rarely need - if I recall it correctly, it'll take around 3000 days (more than 8 years) of up-time to overflow a 32-bit gettickcount :)). Or, maybe move the `GetTickCount64` function to CastleRandom unit if it's the only unit using it? I remember you've written about problems with getting time on Android devices.
Or, maybe just wrap it inside {$Warn 5066 OFF} if its intended?

**Comment by michaliskambi** [comment]
For measuring time using the engine, I want to encourage people to use Timer or ProcessTimer. But your CastleRandom is a valid exception to this: you want to initialize rand seed with time.

As for using FPC:

- Their GetTickCount is deprecated also, suggesting to use their GetTickCount64.
- But their GetTickCount64 is not available in FPC 2.6.4...

So, my plan is: once we will stop supporting FPC 2.6.4, we can

- Rename our own GetTickCount64 to GetTickCountInternal and make it non-public, that is only in the implementation of CastleTimeUtils. It's still a little better than FPC's GetTickCount64 as it avoids problems on some broken Android devices. It is internally used in CastleTimeUtils, to implement Timer and ProcessTimer on Windows.
- Your CastleRandom can then just use FPC's GetTickCount64.

For now, we could wrap it in {$Warn 5066 OFF} indeed.

**Comment by eugeneloza** [comment]
I've got it. I'll try to fix it tomorrow and commit on Thursday.

**Comment by eugeneloza** [comment]
Done. Plus added some comments on cryptography and a minor improvement to initialization algorithm.
I've also improved random_threads_test.lpr a bit to look more dramatic :) Now it's obvious that random is absolutely different for equal GetTickCount64 and works perfectly for threads as simultaneous as they can be.
See https://github.com/eugeneloza/castle-engine/commit/0b90c5beb7eeb9f8b61a8cc3c9f708d9c69392cb and https://github.com/eugeneloza/castle-engine/commit/e8ca30bbdb528a07c675f7444819fff53f5f377c

**Comment by michaliskambi** [comment]
I reviewed the changes in eugeneloza@0b90c5b and eugeneloza@e8ca30b . Perfect -- I'll happily merge them:)

I see that you're committing to your fork on https://github.com/eugeneloza/castle-engine . Will you make a pull request to merge work on this, and #51, together?
