### ISSUE TITLE
Delphi 11.3 Getit test

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#510]
Note - this test was NOT CE

Mostly the same as #507 apart from eye_of_beholder WORKS

Now need to establish whether 10.2.3 works and if so try 10.2.2 then 10.2.1 until EOB fails again

While this is a fairly extreme edge case if 10.2.3 works it will also affect lower versions so it worth checking to identify SPF (Single Point of Failure)

**Comment by michaliskambi** [comment]
Thank you! Closing this issue then, nothing to do, all good here -- we'll solve 10.2.0 in https://github.com/castle-engine/castle-engine/issues/507 .
