### ISSUE TITLE
Castle Editor (Delphi)

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#519]
Good and not so good news

I build Editor and Engine then placed them in the CGE bin dir - had to manually set CGE dir of course (what happens if I've got multiple Delphi versions installed?)

It would be beneficial if CastleEngineManifest.xml became CastleEngineManifest.castle-xml as this way Editor could be associated with them and allow seamless integration

Good - 10.2.1 compiles and runs

Bad - it's almost unusable owing to compilation speed (OK I'm in a VM but the relative timings will still apply)

Via Editor
1299979 lines, 738.33 seconds, 14372032 bytes code, 2899248 bytes data.

Via Delphi IDE
Elapsed time: 00:00:58.5

i.e. Hittin Run in editor takes > 12.5 times as long to compile

Fairly obviously this can be improved by passing the dproj to Delphi

**Comment by peardox** [comment]
I guess my VM could be at fault - I'll have a play

**Comment by peardox** [comment]
It was my VM that was causing the bad timings

I've cleaned out my Steam Deck (with Win11 Pro for an OS + hooked up to Kbd, Mouse + Monitor) so I've got a proper real machine for some tests. Steam deck is a middling performance PC like this so a reasonable test machine.

As tests on hardware will require the removal of old Delphis I want to write a Delphi wiper app - UnInstall leaves a lot of crap around - all needs removing for proper tests...

There are instructions at https://blogs.embarcadero.com/manual-uninstall-of-rad-studio-delphi-cbuilder-10-4-sydney/ but it misses some stuff.

**Comment by michaliskambi** [comment]
> It was my VM that was causing the bad timings

OK, closing the issue.

> There are instructions at https://blogs.embarcadero.com/manual-uninstall-of-rad-studio-delphi-cbuilder-10-4-sydney/ but it misses some stuff.

Thanks. I recall having troubles switching between CE and non-CE Delphi versions on the same machine, Embarcadero explicitly discourages that (instead recommending new VM for each). The https://blogs.embarcadero.com/manual-uninstall-of-rad-studio-delphi-cbuilder-10-4-sydney/ will be helpful, and if you'll automate and/or extend this process -- all the better.
