### ISSUE TITLE
castle-sprite-sheet issue

### ISSUE THREAD

**Issue by RAT-Daddy01** [castle-engine/castle-engine#527]
As mention in discord create a castle-sprite-sheet within the editor, input some sprites after which add the castle-sprite-sheet url to a TCastleScene in my instance, Now the animation should work as expect yet if you create a new folder and input the castle-sprite-sheet along with the sprites png inside the new folder then reload the url based on the new path the editor spits out:
```
Animation "Fire" not found on scene  (loaded from )
Animation "Casing" not found on scene WeaponEffect2 (loaded from )
Animation "Fire" not found on scene  (loaded from )
Animation "Fire" not found on scene  (loaded from )
Animation "Casing" not found on scene WeaponEffect2 (loaded from )
Animation "Fire" not found on scene  (loaded from )
Animation "Casing" not found on scene WeaponEffect2 (loaded from )
```
Inturn causing issues such as being unable to reload the url aka the sprite animation unless you restart the editor but regardless on any changes you will need to restart everytime.

Project here [Animation Not Found.zip](https://github.com/castle-engine/castle-engine/files/12185770/Animation.Not.Found.zip) 

Couldn't reproduce exactly what was happening in my own project though have a feeling it's related, if you double click on the  castle-sprite-sheet to edit the animation you'll get a warning every time in the logs

**Comment by michaliskambi** [comment]
> Couldn't reproduce exactly what was happening in my own project though have a feeling it's related, if you double click on the castle-sprite-sheet to edit the animation you'll get a warning every time in the logs

Thank you for reporting, I fixed the warnings about missing animations.

> Inturn causing issues such as being unable to reload the url aka the sprite animation unless you restart the editor but regardless on any changes you will need to restart everytime.

If you modified the sprite sheet (using CGE sprite sheet editor), it was indeed not reloaded automatically in the design. This was not really related to the warning -- it was just our TODO to detect file changes (whether done by sprite sheet editor, or any external application, e.g. when Blender writes glTF file) and automatically reload files at design-time. To reload explicitly, you can right-click on the TCastleScene object in hierarchy, and choose "Reload URL" from the context menu. Or close + open again the design. Or indeed restart the editor.

That said: I decided it's time finally implement automatic file watching :) It's now done. Saving new sprite sheet will automatically update the design. Changing any file in an external application will also automatically reload it in CGE at design-time.

**Comment by michaliskambi** [comment]
P.S. The new CGE version will be automatically build by Jenkins really soon, hopefully (Jenkins server seems a bit overloaded now).

You can watch the page https://github.com/castle-engine/castle-engine/compare/snapshot...master to know when it is available. If the commit _"Monitor files for changes, to automatically reload"_ will no longer be visible on that page, that means it is part of the release now and you can download latest CGE from https://castle-engine.io/download .

Note that you may need to press "Load more commits" on https://github.com/castle-engine/castle-engine/compare/snapshot...master to make sure you see all commits.
