### ISSUE TITLE
spelling mistakes found by Debian lintian 

### ISSUE THREAD

**Issue by paulgevers** [castle-engine/castle-engine#53]
While working on an update Debian package for castle-engine the Debian package checker Lintian reported several spelling mistakes.

Please find a patch fixing the issues attached to this bug.

[fix-typos-found-by-lintian.patch.txt](https://github.com/castle-engine/castle-engine/files/835135/fix-typos-found-by-lintian.patch.txt)

**Comment by michaliskambi** [comment]
Thank you! Applied:)
