### ISSUE TITLE
TCastleScene.WasVisible has children but is not returning True

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#539]
I've got this in the Render event...

> if Assigned(ActiveScene) then
>     begin
>       if  ActiveScene.WasVisible then
>         InfoLabel.Caption := 'Visible'
>       else
>         InfoLabel.Caption := 'Loading';
>     end;
> 

ActiveScene is an empty TCastleScene but has hundreds of TCastleScene children. The children are rendered but the above always displays 'Loading'.

Technically I suppose ActiveScene isn't rendered as it's just a holding scene for the children. It is obvious that the tree has many child nodes would all return WasVisible as True if tested which implies that in this situation the parent is unaware of its children's status.

**Comment by peardox** [comment]
Hmm : Testing TCastleScene(ActiveScene.Items[0]).WasVisible actually also returned false so maybe there's another problem?

**Comment by michaliskambi** [comment]
It's a deliberate feature that TCastleScene.WasVisible doesn't check whether children scenes are visible. The general rule is: 

- TCastleScene-specific features (like this WasVisible) do not care/apply to children scenes.
- Only TCastleTransform features  (like TCastleTransform.Exists) apply to children as well.

I know it's not ideal (it would be easier to say "everything affects children" or "nothing affects children"), but this is a practical situation that is flexible and comfortable, so we'll keep this.

I see the docs have not been clear about it, fixed.

> Hmm : Testing TCastleScene(ActiveScene.Items[0]).WasVisible actually also returned false so maybe there's another problem?

I tested `examples\viewport_and_scenes\test_was_visible\`, it correctly changes `WasVisible`. Please submit a testcase if this doesn't work for you.

**Comment by peardox** [comment]
Found my problem with Children not having WasVisible

I was calling it in Render rather than Update :(

Of course, in Render, it won't have been set yet it seems as swithcing to Update fixed it
