### ISSUE TITLE
Inline shader failure

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#541]
Using the mask.x3dv from demo_model I've added this issue (to the ever expanding) https://github.com/peardox/SimpleDelphiTest01.git

Uncomment line 7...
//  {$define testmask}
Run and there's no mask
Open the model in view3dscene and it'll be fine

From what I can see this only happens with inline shaders

**Comment by michaliskambi** [comment]
Fixed :) And a new auto-test added, to make sure this problem will never return.

https://github.com/peardox/SimpleDelphiTest01 with `testmask` now works cool, mask works as you expect (just like observed e.g. in view3dscene).

Thanks for all 3 reports around https://github.com/peardox/SimpleDelphiTest01 ! All 3 fixed now. 

![obraz](https://github.com/castle-engine/castle-engine/assets/1076978/4565d2e4-75c5-496a-a458-48d574f95e7b)
