### ISSUE TITLE
URIMimeType failure with valid URL

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#547]
OK, it's obvious why this fails but the URL is valid and so URIMimeType should be able to handle it....

https://cards.scryfall.io/large/front/0/9/092c48bd-b648-4c9e-aa99-cac3c407911d.jpg?1692936576

Such an example presumably also messes up other extension-based code 

Yes, I could work around it but it's a bug so reported...

**Comment by michaliskambi** [comment]
Thank you! Fixed now, i.e. `URIMimeType('https://cards.scryfall.io/large/front/0/9/092c48bd-b648-4c9e-aa99-cac3c407911d.jpg?1692936576')` will answer `image/jpeg`.

I added some new logic + automatic tests of new `URIMimeType`.
