### ISSUE TITLE
libpng implementation of TCastleImage and video (av) recording with Free Pascal

### ISSUE THREAD

**Issue by cpicanco** [castle-engine/castle-engine#548]
Hi everyone,

I am sorry if this is not the best place for all those questions. However, I think some of them may be of interest for you as they are related to general image and video processing.

TLDR
- What is the fastest way you know to make a copy of some part of the screen (like a window) for video recording?
- The libpng implementation of TCastleImage would be fast for reading from screen and writing to file?
- Do you known any up-to-date av (ffmpeg) bindings for Free Pascal?
- I saw you have a video recording for Castle Engine, a wrapper around ffmpeg for calling it with `TProcess` and save some short effects. Do you know if you could use this same approach to save a continuous stream of frames?
- Just for curiosity, I am sharing my PyAv blueprints for a video recorder in Free Pascal.
- Just for curiosity, I am sharing some ideas for an image conversor/compressor based on TBitmap from Graphics (LCL).
___

I am trying to write a fast screen recorder for https://github.com/cpicanco/stimulus-control-sdl2. This program is an experiment builder and I am dealing with eye movements tracking. For my urgent needs (recording of timestamped frames), I did some tests with Windows APIs (mainly based on reading a device context (DC), then `BitBlt` and `GetDIBits`). This approach is fast (~30ms for copying from memory and save to file), but 4mb bitmap files are not feasible, I am expecting 40min-60min recordings. So, I need some fast compression before saving a frame.

I also did some tests with `TBitmap` from `Graphics` unit (LCL) and its dependencies (`FPImage` writers and readers). It was really easy to create a "Conversor" class, for example:

```pascal
unit GraphicsBMPtoPNG;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, Graphics, IntfGraphics, FPImage, FPWritePNG, FPReadBMP;

type

  { TBMPtoPNGConversor }

  TBMPtoPNGConversor = class(TBitmap)
  protected
    class function GetWriterClass: TFPCustomImageWriterClass; override;
    procedure InitializeWriter(AImage: TLazIntfImage; AWriter: TFPCustomImageWriter); override;
  end;

implementation

uses ZStream;

{ TBMPtoPNGConversor }

class function TBMPtoPNGConversor.GetWriterClass: TFPCustomImageWriterClass;
begin
  Result := TFPWriterPNG;
end;

procedure TBMPtoPNGConversor.InitializeWriter(AImage: TLazIntfImage;
  AWriter: TFPCustomImageWriter);
var
  LFPWriterPNG : TFPWriterPNG;
begin
  inherited InitializeWriter(AImage, AWriter);
  LFPWriterPNG := AWriter as TFPWriterPNG;
  LFPWriterPNG.CompressionLevel := clmax;
  LFPWriterPNG.GrayScale := False;
  LFPWriterPNG.UseAlpha := False;
end;

end.
```

So, I thought I could write a reader/writer based on libpng to test if it will improve the speed of my frame by frame recorder:
```pascal
// TVideoWriter = class (TThread)
procedure TVideoWriter.Execute;
var
  LConversor : TBMPtoPNGConversor;
  LStart  : Int64;
  LEnd    : Int64;

  function Elapsed : string;
  begin
    Result := 'recording'+DirectorySeparator+FloatToStrF(
      FFrame.Timestamp - StartTimestamp, ffFixed, 0, 9)+'.png';
  end;

begin
  NameThreadForDebugging(ClassName);
  LConversor := TBMPtoPNGConversor.Create;
  try
    while not Terminated do begin
      FFrame.Timestamp := ET.Elapsed;
      LConversor.LoadFromDevice(FFrame.WindowDeviceContext);
      LConversor.SaveToFile(Elapsed);
    end;
  finally
    LConversor.Free;
  end;
  Log(ClassName+': Terminated ...');
end;
```

After making sure that my frame-by-frame recorder is doing a good work, it would be great to have a proper video recorder writter in Free Pascal. Right now, I have a prototype in PyAv:

```python
import os
import av
import glob
from PIL import Image
from fractions import Fraction

input_dir = os.path.dirname(os.path.abspath(__file__))
image_files = glob.glob(f"{input_dir}/*.png")
image_files_timestamps = [float(os.path.basename(i).replace(',', '.').replace('.png', '')) for i in image_files]
image_files_timestamps_dts = [t - image_files_timestamps[0] for t in image_files_timestamps]
image_files = [(x, t, d) for t, x, d in sorted(zip(image_files_timestamps, image_files, image_files_timestamps_dts))]
video_duration = image_files[-1][1]-image_files[0][1]
fps_p = len(image_files)/video_duration
fps = round(fps_p)

container = av.open("output.mp4", 'w')
video_stream = container.add_stream('libx265', rate=fps)
image = Image.open(os.path.join(input_dir, image_files[0][0]))
video_stream.width = image.width
video_stream.height = image.height
video_stream.codec_context.time_base = Fraction(1, 1000000000)

first_timestamp = None
for (image_file, timestamp, dts) in image_files:
    image_path = os.path.join(input_dir, image_file)

    frame_pts = timestamp
    frame_pts *= 1 + (fps_p - fps) / fps_p

    frame = av.VideoFrame.from_image(Image.open(image_file))
    frame.time_base = video_stream.codec_context.time_base
    frame.pts = int(round(frame_pts / video_stream.codec_context.time_base))
    frame.dts = int(round(dts / video_stream.codec_context.time_base))

    packet = video_stream.encode(frame)
    container.mux(packet)
container.mux(video_stream.encode())
container.close()


```

However, I am not sure if there are any up-to-date av (ffmpeg) bindings for free pascal (compatible with this prototype).

**Comment by michaliskambi** [comment]
Hello!

Note that for more open talk / discussion, our forum or Discord ( https://castle-engine.io/talk.php ) may be a bit better. The GitHub issues are best when there is a clear bug/request that can be "solved" :) That said, don't worry about it too much, really every way to contact me is good, I'm happy to hear from all CGE devs!

> What is the fastest way you know to make a copy of some part of the screen (like a window) for video recording?

Use `TCastleContainer.SaveScreen`, see https://castle-engine.io/apidoc/html/CastleUIControls.TCastleContainer.html#SaveScreen-string- . It has a few overloads, judging from your question you are most likely interested in

```
function SaveScreen(const SaveRect: TRectangle): TRGBImage;
```

So you can grab the screen contents at a specified TRectangle. The resulting `TRGBImage` is a simplest image format, `TRGBImage.RawPixels` are just an array of colors (each pixel - 3 bytes, RGB), one row after another (from bottom to top). You can pass it to other libraries (like ffmpeg) or save to disk using `SaveImage`.

> The libpng implementation of TCastleImage would be fast for reading from screen and writing to file?

The libpng doesn't deal with "reading from screen".

As for "writing to file" -- yes, libpng is very fast. Though ideally you may not need to use it. If you want to record movie efficiently, then communicating with ffmpeg API is likely faster than storing the files on disk.

> Do you known any up-to-date av (ffmpeg) bindings for Free Pascal?

I cannot recommend any particular, as we don't use ffmpeg (as library) in CGE. But https://wiki.freepascal.org/Video_Playback_Libraries has some links. In particular https://github.com/DJMaster/ffmpeg-fpc , http://www.delphiffmpeg.com/downloads/ .

> I saw you have a video recording for Castle Engine, a wrapper around ffmpeg for calling it with TProcess and save some short effects. Do you know if you could use this same approach to save a continuous stream of frames?

We indeed have a simple "saving of videos" in CGE this way. But admittedly this isn't a very good solution. It requires storing lots of data on disk, and communicating with ffmpeg using command-line. You can also take a look at old piece of docs on https://github.com/castle-engine/cge-www/blob/master/htdocs/doc/todo_to_update_and_maybe_restore/manual_recording_movies.php .

For more demanding requirements, I would say that directly using ffmpeg (as a library) API will be better. So I would say to

- not save images to disk
- not depend on CGE TVideo.SaveToFile
- use ffmpeg library as directly as possible.

Note that a lot of depends on your requirements. Do you want to record ready-made animation (then you can use approach like on https://github.com/castle-engine/cge-www/blob/master/htdocs/doc/todo_to_update_and_maybe_restore/manual_recording_movies.php to record perfect 30 FPS) or do you want to record "live", and let player use the application interactively in the meantime? This changes a lot, as in latter case you need to store the data efficiently. I would say to try to feed the data to ffmpeg library, and choose an encoding format for "live" operation that can be fast enough. 

I understand this is exactly what you're playing it -- super, go for it, and let us know :)
