### ISSUE TITLE
Test speed of gzip/non-gzip reading/writing

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#55]
Well... I've made the possibility to compress the game data, but eventually I'm not sure which is faster to load, e.g. a 38kb raw file or 8kb compressed file. While providing almost 5x compression, comparing to "huge" size of textures this hardly counts as a significant. Well... Reading 38kb is slower than reading 8kb, so sequential processing of data should look faster overall. However, decompression takes additional CPU resource. This should be "faster or equal" for Desktops, but for low-speed Android ARM CPU I doubt that it will do any good. So... Which looks "faster" in implementation?
If there is no clear answer (and yes, there should actually be none) then I can make a simple speed test for reading-writing gzipped/raw data which can be run both at Desktop and Android.
On the other hand, exploring the compression issues, I've eventually found out that Save3D and Load3D automatically detect compression based on URL/MimeType (guessed from extension). Maybe, it's better to reimplement the URLWriteXML/URLReadXML (meaning https://github.com/castle-engine/castle-engine/commit/f05778ee903eebca46c24f20b22a516ddb7ec195 and https://github.com/castle-engine/castle-engine/commit/2377d1b7af1893f7ecb83d45772cc0b88cd3b1f3) compression in the same way? WDYT? If yes, then I'm on it :)
P.S. CastleURIUtils lacks ".gz" for archives. Maybe it's a good idea to extend it? Should raw ".gz" extension count as gzipped?

**Comment by michaliskambi** [comment]
> If there is no clear answer (and yes, there should actually be none) then I can make a simple speed test for reading-writing gzipped/raw data which can be run both at Desktop and Android.

Indeed, I do not see here a clear winner looking at the theoretical advantages/disadvantages. Testing it in practice is the way to go.

Although, in my games, this didn't matter in practice -- reading and writing game XML config files was blazingly fast. I suspect that it was so fast that gzipped or not gzipped -- it didn't matter.

>  Maybe, it's better to reimplement the URLWriteXML/URLReadXML (meaning f05778e and 2377d1b) compression in the same way? WDYT? If yes, then I'm on it :)

Yes, it seems better to detect the gzipped/not gzipped looking at the extension. The URLWriteXML/URLReadXML are supposed to be comfortable routines, so they should do such detection. 

> P.S. CastleURIUtils lacks ".gz" for archives. Maybe it's a good idea to extend it? Should raw ".gz" extension count as gzipped?

Yes, the "abc.gz" should be detected as gzipped by CastleURIUtils.

**Comment by eugeneloza** [comment]
Ok, then I'm on it :)

**Comment by eugeneloza** [comment]
Looks like I've done finished extension recognintion (based on your code for Save3D). Everything is working flawlessly for me. I've made a pull request https://github.com/castle-engine/castle-engine/pull/56.
I think I'll make some relative speed tests at weekends.

**Comment by michaliskambi** [comment]
> I think I'll make some relative speed tests at weekends (writing/reading a one huge file, writing/reading hundreds of small files - only "reading" for Android).

OK, great! I have changed the issue title to reflect what is left:)

**Comment by eugeneloza** [comment]
Moving the issue to my fork. Closed this one for now. I'll report here as soon as I've finished.
