### ISSUE TITLE
Warning: Textures: Releasing texture id 2 after OpenGL context is closed. This means that you free some OpenGL resources (like TDrawableImage) too late, you should move their destruction to an event like TCastleWindow.OnClose or TCastleControl.OnGLContextClose.

### ISSUE THREAD

**Issue by eugeneloza2factor** [castle-engine/castle-engine#551]
There is a warning output into log when using Screen Effects, mentioning that some texture is not released when the context is closed.

Minimal reproduction (3 lines added to "default" project and a new unit with Screen Effect manager):

[screen-effect-texture-warning.zip](https://github.com/castle-engine/castle-engine/files/13468344/screen-effect-texture-warning.zip)

**Comment by michaliskambi** [comment]
I can reproduce this too. Looking into it, as I also noticed it when playing with https://github.com/castle-engine/castle-engine/issues/529 . It may be related or even share the same culprit.

**Comment by michaliskambi** [comment]
I posted details about the fix in https://github.com/castle-engine/castle-engine/issues/529#issuecomment-1841227535 .
