### ISSUE TITLE
Cannot build for MacOSX

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [castle-engine/castle-engine#563]
I'm not sure what's going on exactly, at is worked for the previous version, but I noticed there are no MacOS compiler directives, only DARWIN which is a very old MACOS architecture and is not used by Delphi.

Has this been tested for Dephi 12 / Mac OS Target or am I missing something.

**Comment by michaliskambi** [comment]
> I'm not sure what's going on exactly, at is worked for the previous version

As for this statement -- no, Delphi on macOS was never supported. We did support, and still do, macOS with FPC.

**Comment by TheOriginalBytePlayer** [comment]
Thank you for the information.

**Comment by TheOriginalBytePlayer** [comment]
Hmm, interesting.
