### ISSUE TITLE
Have "EnableDragging" on TCastleScrollView basic tab

### ISSUE THREAD

**Issue by eugeneloza2factor** [castle-engine/castle-engine#571]
I'm almost sure it was there but can't find it now:

![2024-02-18 14_20_46-Greenshot](https://github.com/castle-engine/castle-engine/assets/73470521/44a1a804-0714-463a-acb2-d9fa38d097e8)

![2024-02-18 14_20_25-Greenshot](https://github.com/castle-engine/castle-engine/assets/73470521/d044a587-cc2a-4115-bed2-69062ea3fc4f)

It feels like a very important feature of `TCastleScrollView` (and maybe should even be simply enabled by default instead?)

**Comment by michaliskambi** [comment]
Moved to the "Basic" tab - fully agree it's important.

I hesitated whether to make it enabled by default -- while it's standard behavior on mobile (touch devices), it isn't standard on desktop applications. That said, 

- we want to choose something as default, and it's better to have the same default on mobile and desktop. 

- And enabling it seems to not have any adverse effects (in particular, child content still has a chance to process press events first).

So, agreed also, `EnableDragging` is now `true` by default :)
