### ISSUE TITLE
TDebugTransform has no sphere

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#572]
> Like TDebugTransformBox, but visualizes also additional properties.

    Adds visualization of:
    - TCastleTransform.Middle
    - TCastleTransform.Sphere
    - TCastleTransform.Direction
    
Apart from the fact that there's no Sphere (Radius = 0?)

**Comment by michaliskambi** [comment]
There is `TCastleTransform.Sphere`, see https://castle-engine.io/apidoc/html/CastleTransform.TCastleTransform.html#Sphere-Single- . The API docs generated for `TDebugTransform` linked to it. It's a method. 

I have edited the description to mention also `CollisionSphereRadius`, which is the property usually responsible for determining the `Sphere` result, so it makes sense to emphasize it.
