### ISSUE TITLE
Delphi Tests pre alpha3

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#573]
First install

D12 Full from ISO under Win11 Pro registereed (bought a dodgy license) fully updated

![image](https://github.com/castle-engine/castle-engine/assets/1549219/dc519ea6-c549-466e-a544-a85b52f78e39)

ViewTranslationManagerMenu ?

More info...

This happened  on installing castle_engine_design.bpl - i.e. the last in the list having skipped window
I also note that we are installing Win32 DEBUG (on advice [Jim] should really install Release unless you're planning on debugging the design-time package)

Tried compiling a CGE window only which gave me....

[dcc64 Fatal Error] Unit1.pas(7): F2613 Unit 'Vcl.CastleControl' not found.

Mind you can't set paths cos of above error (to Delphi CGE menu)

**Comment by michaliskambi** [comment]
> ViewTranslationManagerMenu ?

Thank you, fixed!

( This was absolutely critical -- the big thing we announced last weekend https://castle-engine.io/delphi_packages was just broken on Delphi 12.0 . Thank you again for reporting it. I'm ashamed I didn't catch it in my tests, it was the single most important test before announcing https://castle-engine.io/delphi_packages and somehow it slipped me... )

> I also note that we are installing Win32 DEBUG (on advice [Jim] should really install Release unless you're planning on debugging the design-time package)

Let the packages be `DEBUG` by default, let users install whatever they want, which means most usually debug by default. Let them run with debug checks for now, and ev. report some errors clearly. The packages don't do anything demanding at design-time in Delphi IDE, so it also doesn't affect performance. We may switch to `RELEASE` in the future.

> Tried compiling a CGE window only which gave me....
> 
> [dcc64 Fatal Error] Unit1.pas(7): F2613 Unit 'Vcl.CastleControl' not found.
> 
> Mind you can't set paths cos of above error (to Delphi CGE menu)

What is "compiling a CGE window only" ? Which exactly example do you compile? 

I'm going to assume you tried to compile a new VCL application -- the error indicates you didn't set all CGE paths. So indeed it is a follow-up of previous problem, D12 fail at `ViewTranslationManagerMenu`. Using new CGE, using "Configure Delphi to use the Engine" menu item should make it fixed.

**Comment by peardox** [comment]
And now you see why I bother with testing as well :) 

> What is "compiling a CGE window only" ? Which exactly example do you compile?

Drop control on form, hit compile

Now goping to run test again on a newly Delphi-less VM
