### ISSUE TITLE
C++Builder CE (Working!!!)

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#579]
Well, I was amazed at quite how easy this was :)

Basically compile in 11.3 then made a backup of win32/64 rel/debug dcu dir and the Users/PublicEmbarcadero/Documents/Studio/22.0 folders (selected bpl, dcp + hpp). Set up the dirs in Delphi Options and register the packages in bpl x 4 and voila...

![image](https://github.com/castle-engine/castle-engine/assets/1549219/9bc6723e-7409-4f42-8b21-569312a46b59)

Both VCL and FMX work fine in both Win32 + 64

This means that a specific C++11CE build is more than feasible - well, for an irregular limited release schedule

It's got the IDE plugin - possibly some irrelevant parts here?

Sorta makes me wonder if a binary distribution is worthwhile doing for C++ once a major milestone?

Can't try Delphi CE til Ian Barker fixes my CE serial (written to him about it)

**Comment by peardox** [comment]
Ooh - looks like dcus are optional

Ian just sorted my D11CE Serial so going to try a binary install of just packages in that

**Comment by peardox** [comment]
DCUs only optional on C++ by the look of it - must get stuff from the hpp's

Anyway FYI a full binary release is about 125M and could handle both CEs so the concept is still valid

Wonder if [CompInstall](https://github.com/digao-dalpiaz/CompInstall) can manage it? I'll have a look...

**Comment by peardox** [comment]
Nope - CompInstall needs a complier by the look if it (and MSBUILD)

However Inno Setup looks like it's capable of handling the job - I'm specifically thinking of the CE version installations here especially CBuilder CE (just also happens to work for D11CE if dcus included)

**Comment by michaliskambi** [comment]
Thank you for testing. I'm closing this -- we don't want to go into distributing binaries compiled for C++ Builder. 

As in https://github.com/castle-engine/castle-engine/issues/576 ,

> Let's first see if there's user interest in C++ Builder + Castle Game Engine.
