### ISSUE TITLE
GameViewMain root element is still Group1

### ISSUE THREAD

**Issue by eugeneloza2factor** [castle-engine/castle-engine#583]
While Castle Editor already nicely names root element of views it creates as RootGroup, the default "empty" template still has GameViewMain with root element named Group1. Very minor, obviously :)

**Comment by michaliskambi** [comment]
Thank you! I actually also noticed it yesterday ("hm, there's Group1 in my new project, didn't we improve that already?"), but was in too much rush to analyze :) Indeed, `Group1` remained in "empty" project and "3d_model_viewer" templates. Fixed now,
