### ISSUE TITLE
Network messages containing non-ascii characters are not sent

### ISSUE THREAD

**Issue by bbrtj** [castle-engine/castle-engine#590]
Using `TCastleTCPClient.Send` when message contains non-ascii characters results in messages not sending at all - without any exception or anything it seems. The characters are viewed fine in the program and in the console. For testing, I'm using Polish letters like `ąśćźóę` - the issue occurs as soon as I include one such letter in the message to be sent.

This problem is reproducible using examples from `network/tcp_connection` without any modification (other than path to Indy sources). I'm using fpc 3.2.2 and my system is FreeBSD 14.0-RELEASE on amd64.

**Comment by michaliskambi** [comment]
Thanks -- fixed :)
![Zrzut ekranu z 2024-04-03 00-00-05](https://github.com/castle-engine/castle-engine/assets/1076978/84ed5567-a555-4a43-b18d-eab7c2fd618f)
![Zrzut ekranu z 2024-04-03 00-00-29](https://github.com/castle-engine/castle-engine/assets/1076978/6db19e5e-46ce-4824-af6c-052911f1b90a)

**Comment by michaliskambi** [comment]
( I reproduced and tested the fix on Linux now. The problem and solution seem cross-platform, so I'm fairly sure the fix will help on FreeBSD as well -- but naturally let me know if it doesn't :) )

**Comment by michaliskambi** [comment]
Note that I have remade UI and code organization of server/client examples (to put code in TViewMain). So don't be surprised they look very different now :) Functionality is the same.

![obraz](https://github.com/castle-engine/castle-engine/assets/1076978/f0225b6c-e1e2-4236-b57a-a54f334f5583)

**Comment by bbrtj** [comment]
I can confirm it works now in my project, thanks :)
