### ISSUE TITLE
Failed to detect VSCode on MacOS

### ISSUE THREAD

**Issue by caryyu** [castle-engine/castle-engine#598]
# Ticket

https://discord.com/channels/389676745957310465/1105477501330931712/1225052612337078332

# Description

Currently, the detection only works on the env-var, however, if it can support `/Application/xxx` detection, that should make things easier. 

![image](https://github.com/castle-engine/castle-engine/assets/4496641/5e18f1db-3a67-4705-b224-982262d4ec7f)

**Comment by michaliskambi** [comment]
Fixed by @janadamec1 in https://github.com/castle-engine/castle-engine/pull/622 - thank you!
