### ISSUE TITLE
error installing castle_window.lpk

### ISSUE THREAD

**Issue by codz01** [castle-engine/castle-engine#599]
i've installed castle_base.lpk ok  but with castle_window.lpk i got those errors  
![error](https://github.com/castle-engine/castle-engine/assets/10813427/5d999e48-b1ef-4f44-a370-8803d5f3772f)

**Comment by michaliskambi** [comment]
It seems you have a mixture of old and new CGE code.

The `Load_WGL_*` routines are indeed removed from CGE (around migration to dOpenGL/CastleGL , January 2024, see https://castle-engine.io/wp/2024/01/28/january-news-ticoban-editor-dragging-castlegl-based-on-dglopengl-tester-improvements-pascal-custom-rtti-attributes-more/ ). But so is any usage of them. 

This is how the latest version of `castleinternalcontextwgl.pas` looks like: https://github.com/castle-engine/castle-engine/blob/master/src/base_rendering/castleinternalcontextwgl.pas .

![obraz](https://github.com/castle-engine/castle-engine/assets/1076978/cdfa2b2e-8fe1-42d8-b9cb-d8cf4eb4cdb5)

As you can see, if's a bit different than what is in your screenshot -- it doesn't use any `Load_WGL_*` routines.

Please make sure to remove all old CGE versions, and install new one from https://castle-engine.io/download .

( I'm closing the issue now, but feel free to add questions and/or reopen if you cannot solve it on your end. )

**Comment by codz01** [comment]
thanks  , you are right , i forgot to delete old builds
