### ISSUE TITLE
typos found by lintian

### ISSUE THREAD

**Issue by paulgevers** [castle-engine/castle-engine#60]
Again two typos found. Please find a patch attached.

Maybe also grep and/or sed on the whole source tree to find/replace successfull (but not successfully). Idem for the typos in issue #53: occured, succeded and charater. They were not fixed in that issue because they didn't show up in the binaries.

[fix-typos-found-by-lintian.patch.txt](https://github.com/castle-engine/castle-engine/files/868556/fix-typos-found-by-lintian.patch.txt)

**Comment by michaliskambi** [comment]
Thank you, applied! I also grepped and fixed various "successfull" occurrences :)
