### ISSUE TITLE
Missing ifdef fpc in castleinternaltools.pas - 519

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#602]
Delphi won't compile current build

Line 519 in castleinternaltools.pas

> FindFiles(TemplateUrl, '*', true, @CopyProcess.FoundFile, [ffRecursive]);

Needs to be

>FindFiles(TemplateUrl, '*', true, {$ifdef FPC}@{$endif}CopyProcess.FoundFile, [ffRecursive]);

**Comment by michaliskambi** [comment]
Thank you, fixed!

**Comment by michaliskambi** [comment]
I also added auto-tests of CastleInternalTools unit. So CI (Jenkins, GH Actions) will now notify us immediately if we commit something to that unit that doesn't compile with one of compilers. We don't want to repeat this mistake in the future :)
