### ISSUE TITLE
Looking for Windows developer setup on GitHub 

### ISSUE THREAD

**Issue by coderextreme** [castle-engine/castle-engine#606]
https://github.com/castle-engine/castle-engine/tree/master/src/window/windows

Add Windows developer setup information as README.md in the above folder.

Or a README.md with links.

I will work on this task.

**Comment by coderextreme** [comment]
I wrote a set of steps i went to to set up VSCode on Windows.  It’s in the VSCode channel on Discord in the short term

**Comment by michaliskambi** [comment]
Simply use the engine as a normal user (follow tutorial, manual from https://castle-engine.io/ ) and if you want to play with engine development follow https://castle-engine.io/compiling_from_source.php . There's no particular "Windows developer setup" to do. If you want to use VS Code, follow https://castle-engine.io/vscode .

I read your doc on Discord, and it contains many statements... some of them not related to CGE. Many of them indicate you struggled to get debugger working -- yet it should work out-of-the-box in my tests, just set the engine path and choose castleDebug . Following https://castle-engine.io/vscode . I welcome a precise bugreport if some things fail.

**Comment by coderextreme** [comment]
Primary things are:

1.  Setting the CASTLE_ENGINE_PATH

Which is well documented.

2.  Noticing the "Run" at the bottom of VS Code.  In previous experience,
the Icon with the right pointing triangle on the left side of the windows
worked, with the combination of the green arrow by fpDebug...

Those are the two keys, as I see it.
