### ISSUE TITLE
Recent MimeType changes seem to be preventing simple file-based URL loads.

### ISSUE THREAD

**Issue by coderextreme** [castle-engine/castle-engine#609]
Sample code (not perfect)
```pascal
var
  Scene: TCastleScene;
  I: Integer;
procedure AppDropFiles(Sender: TCastleContainer; const FileNames: array of string);
begin
  for I := 0 to Length(FileNames) - 1 do
  begin
    Scene.Load('file:/'+FileNames[I]);
  end;
end;```

**Comment by michaliskambi** [comment]
This is an invalid report, and this is a 5th place where you report it.... please, the amount of noise in your communication is overwhelming me. 

As we talk about this on Discord, you likely made a bug in WinAPI code in https://github.com/castle-engine/castle-engine/pull/608 , adding trailing zero to the string. This messes the filename extension, thus messing the MIME detection. If your file will have really the `.x3d` extension (or other supported), it will work.

And don't convert filename to URL like this, use `UriToFilenameSafe`.

If you find a bug, send a complete testcase to reproduce this bug.
