### ISSUE TITLE
Performance of dynamic shadows - testcase

### ISSUE THREAD

**Issue by Didisoftgd** [castle-engine/castle-engine#614]
This is my testcase for the dynamic shadows.
Terrainsize 1000x1000
Items (scenes and translations) 3500
FPS with shadows on = 22 (18-25)
FPS without shadows = 65 (55-75)
Standard walknavigation, X for mouselook on/off
[Terraintest.zip](https://github.com/user-attachments/files/15765089/Terraintest.zip)

**Comment by michaliskambi** [comment]
Almost done!

The initial version of the optimization is done on branch [optimize-shapes-collection](https://github.com/castle-engine/castle-engine/tree/optimize-shapes-collection). It is impactful for me, bumping FPS from ~34 -> ~55 on my system. 

![obraz](https://github.com/user-attachments/assets/14070ca5-1594-465a-8943-5285309d6123)

I will do more testing/polishing of this over the weekend and merge.

**Comment by michaliskambi** [comment]
I merged this optimization into CGE master branch! 

I tested everything. This changes how an important piece of rendering works (we now make 1 pass to collect all shapes, and reuse results of this pass a few times -- 2x without shadow volumes, 4x for shadow volumes (was 5x before the optimization, but I managed to completely remove one)). 

I'll wait for GitHub Actions to build everything (we are after 2 refactors last week, and some examples may need adjustment) and close this ticket then.

Please let me know how did the FPS change for you :) Also let me know if anything looks different -- this rework should not have changed anything in how things look, things should look exactly the same as e.g. recent _7.0-alpha.3_ release.

**Comment by michaliskambi** [comment]
All GitHub Actions are OK again :) So, this is really done now. 

You can test with Castle Game Engine `7.0-alpha.3.snapshot` version:

- downloaded from https://castle-engine.io/download

- or from "snapshots" on GitHub, https://github.com/castle-engine/castle-engine/releases/tag/snapshot , these are the same downloads now 

- or obtained from sources, https://github.com/castle-engine/castle-engine/ , but in this case you will need to recompile everything yourself following https://castle-engine.io/compiling_from_source.php .
