### ISSUE TITLE
Unable to download from Github

### ISSUE THREAD

**Issue by mvoltz** [castle-engine/castle-engine#627]
Chrome Browser says: "File wasn't available on site"  "Try to sign into the site.  Then download again."

Files I tried to download:
castle-engine-setup-7.0-alpha.3.exe
castle-engine-7.0-alpha.3-win64-x86_64-bundle.zip
castle-engine-7.0-alpha.3-win64-x86_64.zip

I'm able to download other github releases/sources

**Comment by michaliskambi** [comment]
Hm, very weird -- I tested now, and 
- the downloads from https://github.com/castle-engine/castle-engine/releases/tag/v7.0-alpha.3 definitely work OK. 
- Same for downloading from https://castle-engine.io/download , also works (these are the same files).
 
The files are there, and naturally don't require sign-in to download. I also know that many other people have downloaded them successfully, stats confirm it :)

I tested now from 
- private window in Firefox and 
- Vivaldi (Chromium-based).

Note that we don't really handle downloads, if you download straight from https://github.com/castle-engine/castle-engine/releases/tag/v7.0-alpha.3 . You download files from GitHub servers, without any CGE servers in the way. 

Ideas:

- Try other options to download:  
    - You can get engine from itch.io : https://castle-engine.itch.io/castle-game-engine . Even better: use [Itch.io app](https://itch.io/app) to download and install the engine -- this makes installation 1-click, and it can easily update in the future.
    - You can get engine from the [deprecated file releases on SourceForge](https://sourceforge.net/projects/castle-engine/files/castle_game_engine/). I emphasize that we don't recommend it, we don't maintain the engine on SourceForge for many years now... Well, but actually we do upload (a subset of releases) of the latest engine there, just in case. So you can download 7.0-alpha.3 release from there, at least for Windows and Linux.
 
- Make sure your Internet connection is stable, the engine downloads are quite large now. (Though if this would be the problem, you would get error like "Download interrupted", not "File wasn't available on site" / "Try to sign into the site. Then download again.")
- Clear your browser's cache
- Try another browser, like Firefox
- Submit a video recording where / how you download. Maybe I misunderstand and you're in some weird place? :)
- From what country do you come? Do you have some VPN?
- If downloads from https://github.com/castle-engine/castle-engine/releases/tag/v7.0-alpha.3 fail, please write to https://support.github.com/ . This is not on our side -- ultimately, GitHub, not CGE servers, host the downloads.

Regardless of the solution, please let me know. I'm closing this -- as I'm rather certain this is some issue on your side (or maybe there was some intermittent GitHub problem? but https://www.githubstatus.com/ is all OK). I'm still interested which solution will work for you.

**Comment by mvoltz** [comment]
I'm happy to hear it's just me.  I tried again this morning (same way) and it worked fine.  I suspect our highly congested wireless may be to blame.  Thanks for following up.
