### ISSUE TITLE
UTF8 problems again :)

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#66]
Hi, Michalis!
I'm again experiencing problems with Cyrillic UTF8 encoding/decoding :) That's gonna be a habit :)
Namely speaking: `TDOMElementHelper.TextData`
In Linux (Lazarus 1.6.2 FPC 3.0.0) getting `ValueNode.TextData` works fine.
But in Windows (Lazarus 1.6.4 FPC 3.0.2) it returns a mess unless I do `UTF8encode(ValueNode.TextData)`.
While specifying `UTF8encode` in Linux returns a mess :)
I don't see any platform-specific stuff in `TDOMElementHelper.TextData` and it already internally uses UTF8encode to convert the result to `AnsiString` as `UTF8Encode((Node as TDOMText).Data)`.

**Comment by michaliskambi** [comment]
Can you submit a testcase for me to test? With Pascal code, and with sample XML data.

P.S. I'm watching your progress with https://decoherencestudio.wordpress.com/ , nice screenshots lately:) I'm eager to see more:)

**Comment by eugeneloza** [comment]
The only result I could achieve is that I can't reproduce the problem anymore :) That's a good result.
