### ISSUE TITLE
Safe threaded loading

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#67]
I've been playing around with safe threaded loading of data and eventually made a special safe-loading wrapping for XML/X3D/Image loading: see https://github.com/eugeneloza/decoherence/blob/master/decoinputoutput.pas#L44
There's still a nasty bug in Debug mode + Linux (see http://forum.lazarus.freepascal.org/index.php/topic,36823.0.html ), but the approach looks altogether useful. Maybe, CGE I/O procedures may be wrapped in Critical Sections as default (tunable with a global compiler directive)?
Even more... maybe the whole render process might be a Critical Section to be able to be released into a thread?

**Comment by eugeneloza** [comment]
Closing for now... looks like the issue is much more complex, than I can handle :)

**Comment by michaliskambi** [comment]
Sorry for the delay -- very busy weekends (and weekdays too!) lately:)

As for the renderer -- it cannot be put in a thread, as the OpenGL wants to be run from the main thread, as far as I remember.

As for the I/O -- hm, depends on what you want to achieve. If you want to call the engine I/O from multiple threads, then indeed you must protect the routines with critical sections (to protect access to some internal global caches). It will work correctly then (if you wrap *all* relevant accesses in a critical section). But the gain is not great then -- you will not be able to use the engine in parallel from 2 threads anyway, as in practice one thread will then wait for the other. So it will work correctly, but all the engine calls will wait for each other anyway. So it will be a gain only if you do some unrelated work in the meantime in the threads. 

Not easy stuff, indeed, and so far I managed to avoid it myself in the engine:)

**Comment by michaliskambi** [comment]
P.S. Contrary to some comments from others on http://forum.lazarus.freepascal.org/index.php/topic,36823.0.html , I think you *are* using critical sections correctly. The purpose of the critical section is to make sure that the given block of code is being executed *at most* by one thread at a time, all others will block waiting. See e.g. https://www.freepascal.org/docs-html/fcl/syncobjs/tcriticalsection.html description. 

So you are *correctly* protecting here the access to a global memory of "caches" used internally e.g. by Load3D. I think that commenters on http://forum.lazarus.freepascal.org/index.php/topic,36823.0.html did not realize that Load3D is not just merely reading data from disk, it also uses a global cache.

So, this is a correct approach... but it has to be applied thoroughly, to every possible access of something global from *any* engine routine. The lack of this has probably caused you problems. Indeed, these problems can be hard to debug, as they can randomly appear/disappear based on optimization settings, OSes...

**Comment by eugeneloza** [comment]
Thanks a lot for your comments!
At this moment I'm too concentrated on Ph.D. Theses defense (just the day after tomorrow!), so not much progress lately. But I'll definitely try something shortly.
Yes, I need parallel loading of files - I'm using "load screens" which load images on their own in a thread, and I have a parallel loading of game data (also in a thread). So making a thread-lock was the first thing I thought of :)
