### ISSUE TITLE
Double Log Stream?

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#68]
Hi, Michalis!
At this time we have LogStream: TStream; which suggests we have only one log stream (e.g. either a file or a console in desktop applications).
But, actually, maybe its possible to have two simultaneous streams (both to file and console)? I'm not sure if this is "needed", my way of thinking is the following:
I usually need just console output to see it real-time.
However, I've several times got my X11 completely hung up by the game (the threads problem I've described earlier) and therefore it's hard to tell at which phase it fails. So a parallel log-file which I'll be able to see after rebooting might be a good hint on where to seek the error.
I'm not sure if log-file will represent the "current" state of the log if the app fails as badly as OS becomes unresponsive :) Neither I am sure it'll be helpful. But anyway, writing log both to a file and to console might come in handy.
What do you think?
If yes, I'll assign this to myself :) Looks like the task I can handle (Yes, I already have a bunch of "started but not finished" things to do, shame on me).
The idea is "if assigned(logstream2)" then add another few writeln procedures (as copy of logstream-related). And an additional ("add secondary log stream") routine to initialize/release logstream2 properly.
However, it'll be a minor efficiency drop for logging. Maybe, not worth it?

**Comment by michaliskambi** [comment]
I don't think I want this -- it complicates the currently simple approach of a single "logging target". Sometimes it goes to the console (and you can always redirect it to the file then), sometimes it goes to the file, sometimes to some device-specific log, see https://castle-engine.sourceforge.io/manual_log.php . This allows us to adjust the logging to the requirements (or conventions) of the current OS. E.g. on Windows, you don't have a console in GUI applications.

If anything, I would try to make it differently (in a way, even more flexible):

- Make the WriteLogRaw (in CastleLog) get a parameter with LogPriority, an enum from (lpVerbose, lpDefault, lpWarning). The current WritelnWarning would pass lpWarning, the current WritelnLog would pass lpDefault but an overloaded version like WritelnVerboseLog would pass lpVerbose.
- WriteLogRaw outputs only logs with LogPriority >= LogDisplayPriority. By default, LogDisplayPriority = lpDefault, so lpVerbose is not displayed.
- WriteLogRaw also passes all the logs to the global callback OnLog that receives LogMessage and LogPriority.

Now, user application can assign something to the OnLog variable, to be notified about the logs, and do whatever it wants with them. E.g. it can store the logs (including lpVerbose) logs to some file, or send them over the network, or send them to Unix syslog or Windows event log... This allows adjusting to application needs. E.g. if you can crash your program, then you may consider sending your data to the syslog. Or, if you can hang your OS, then you may consider even closing/reopening the log file each time (very slow, but then much more reliable in case of OS crash).

**Comment by eugeneloza** [comment]
Thanks a lot!!!
I think this is a nice idea I can handle.

Moving the issue to my fork. Closed this one for now. I'll report here as soon as I've finished.
