### ISSUE TITLE
Build tool not recognize all filename letters.

### ISSUE THREAD

**Issue by tsr8** [castle-engine/castle-engine#7]
If I use non ASCII (but UTF8) letter like "ę" in file name (and manifest) then build tool don't recognizes it correctly.
There is: "Fatal: Can't open file ....lpr" error on output.
Pure FPC and Lazarus works OK with those files.

**Comment by michaliskambi** [comment]
Probably I forgot to convert utf8 to ansi somewhere, I'll look into it on
weekend. It's also interesting whether it does work out of the box with FPC
3.x and new codepage-aware strings.
11.11.2015 12:41 AM "Tomasz W" <notifications@github.com> napisał(a):

**Comment by michaliskambi** [comment]
Sorry for having this open for so long! Castle Game Engine now requires FPC >= 3.0.x. And testing with FPC 3.0.4, on Windows and Linux, it seems everything is cool now. Compiling a project with this manifest works OK:

```
<?xml version="1.0" encoding="utf-8"?>
<project name="drawing_toy"
  caption="Drawing Toy"
  qualified_name="net.sourceforge.castleengine.drawingtoy"
  standalone_source="drawing_toy_źrebię_ćma_standalone.lpr"
  game_units="Game">
  <package>
    <include path="README.txt" />
  </package>
</project>
```

I'm assuming that the change in FPC 3.0.x for codepage-aware AnsiStrings solved it for us:) Please reopen this if you can reproduce it still.
