### ISSUE TITLE
Generic.Collection keeps recompiling at every project compillation

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#72]
Every time I compile a project, the Generic.Collection units keep recompiling over and over again. E.g.:
[GenericRecompiled.txt](https://github.com/castle-engine/castle-engine/files/1204780/GenericRecompiled.txt)

**Comment by michaliskambi** [comment]
In my experience, FPC 3.0.x indeed recompiles `Generics.Collections` once (or twice?) more than necessary... but eventually, it's settled, and it's not being recompiled again :) So it's weird, but not a significant problem.

FPC 3.1.1 doesn't do it, in fact it has `Generics.Collections` precompiled as part of the RTL and it doesn't know their source code anymore. So this problem does not exist with FPC 3.1.1.

I tested this on https://github.com/eugeneloza/decoherence , and it seems that things are indeed "settled" at some point, and recompiling decoherence again and again doesn't recompile anything from CGE. I'm attaching my output, done with FPC 3.0.2 on Linux x86_64. I was just compiling by running `lazbuild decoherence_desktop.lpi` repeatedly. Before that, I cleaned the engine (by `make clean` in castle-engine dir).

[log.txt](https://github.com/castle-engine/castle-engine/files/1209332/log.txt)

Can you test, do you experience the same? Are they eventually "settled" and not recompiled anymore?

If you still experience the problem, then can you upgrade your FPC 3.0.3 to the latest version (soon to be FPC 3.0.4), or try stable FPC 3.0.2? As far as I see, you also use Linux x86_64, same as me. So you should experience the same thing as me.

**Comment by eugeneloza** [comment]
Yes, that's not an important problem, and yes, it won't settle down and FPC would recompile Generic.Collections each time I recompile the code (after changes have been made or project folder purged).

> If you still experience the problem, then can you upgrade your FPC 3.0.3 to the latest version (soon to be FPC 3.0.4), or try stable FPC 3.0.2?

3.0.2. Doesn't work under Debian Linux... (actually that's the reason, why they've packaged 3.0.3 with Lazarus for Debian). I haven't checked FPCDeluxe you've written about yet, and I've failed to install a "different" FPC version from the sources several times (and eventually, gave up :)).
But actually yes, if it's a temporary problem of my FPC installation (and not a serious one) then it's not worth any further attention.
(I'll close this issue then)

**Comment by michaliskambi** [comment]
FPC 3.0.2 absolutely works under Debian Linux, I'm using it for months. It has problems showing the backtrace with line information, but otherwise it works perfectly :)

**Comment by eugeneloza** [comment]
Well I've been getting "Error while linking" unable to compile anything: http://forum.lazarus.freepascal.org/index.php/topic,36093.0.html . That might have been the problem with Debian package itself. But now they package 3.0.3 Linux version of FPC for another bug: https://bugs.freepascal.org/view.php?id=31629
