### ISSUE TITLE
fpcupdeluxe requires svn

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#78]
fpcupdeluxe requires svn (`subversion` package in Debian Linux) installed otherwise it won't work with some explanatory but hard-to-read due to poor color scheme error message :) I think it's worth mentioning at https://github.com/castle-engine/castle-engine/wiki/fpcupdeluxe

**Comment by michaliskambi** [comment]
Mentioned. You should also have access to this wiki page :), you're most welcome to extend the documentation there!

Note that you can also use `trunkgit`, then you don't need SVN, only GIT. As far as I know it uses http://wiki.freepascal.org/git_mirrors .

The poor readability may be probably submitted to https://github.com/newpascal/fpcupdeluxe/ :)

**Comment by eugeneloza** [comment]
> You should also have access to this wiki page

Ooops... as usually I forgot that it's at the same github project :) I'll try to be more attentive next time :)
