### ISSUE TITLE
Background rotation

### ISSUE THREAD

**Issue by tomwiel** [castle-engine/castle-engine#79]
I see a problem if nonzero-angle of background and viewpoint (camera) is equal:
After load of example file, the background gradient looks not complete.
If I rotate the camera interactively (rotations become unequal), painting becomes correct.
[test.x3d.txt](https://github.com/castle-engine/castle-engine/files/1424423/test.x3d.txt)

**Comment by michaliskambi** [comment]
The gradient seems OK on my system (testing on Linux x86_64 with NVidia GPU), see the screenshot.

However, I saw in code that it may be wrong (a black crack may appear between the "sky" and "ground" in X3D terms) on some systems, depending on GPU. So I made it better, to be always correct :) It should fix your issue.

Please try the latest Castle Game Engine from GitHub. You can also take view3dscene from GitHub or from snapshots on https://michalis.ii.uni.wroc.pl/castle-engine-snapshots/ . If the problem still occurs, send the screenshot how does it look like on your system.

Thanks for reporting!

![test_0](https://user-images.githubusercontent.com/1076978/32149748-96d4ad6e-bd09-11e7-8fb1-c46ebe210b1f.png)
